Repository LN-Zap/zap-desktop, pull requests merged in 2018-09, with the labels that each got.

#734 fix(ui): show wallet once balances are loaded
  app/routes/activity/components/Activity.js
Labels: bug

#737 feat(wallet): show node public address if set
  app/components/Wallet/ReceiveModal.scss
  app/routes/app/containers/AppContainer.js
Labels: enhancement

#700 feat(testnet): add pill to UI on testnet
  app/components/Wallet/Wallet.js
  app/components/Wallet/Wallet.scss
Labels: enhancement

#740 fix(fsm): ensure lnd connect before state change
  app/lib/zap/controller.js
Labels: bug

#745 fix(pay): dont focus on value input
  app/components/Form/Pay.js
Labels: bug

#741 fix(grpc): show error on connect to locked wallet
  app/lib/lnd/lightning.js
  app/lib/lnd/methods/index.js
  app/lib/lnd/subscribe/channelgraph.js
  app/lib/lnd/subscribe/invoices.js
  app/lib/lnd/subscribe/transactions.js
  app/lib/lnd/walletUnlocker.js
  app/lib/lnd/walletUnlockerMethods/index.js
  app/lib/zap/controller.js
  app/reducers/info.js
  test/unit/lnd/lightning.spec.js
Labels: bug, enhancement

#744 feat(lnd): update lnd to latest master build
  app/lib/utils/btc.js
  app/lib/zap/controller.js
  app/reducers/invoice.js
  package.json
  resources/rpc.proto
Labels: chore

#743 feat(onboarding): add connection type descriptions
  app/components/Onboarding/ConnectionType.js
  app/components/Onboarding/ConnectionType.scss
Labels: UX/UI, enhancement

#752 fix(lnd): do not require a single lnd process
  app/lib/lnd/util.js
  app/lib/zap/controller.js
  package.json
  yarn.lock
Labels: enhancement

#751 fix(grpc): ensure connection to lnd on init
  app/containers/Root.js
  app/lib/lnd/lightning.js
  app/lib/lnd/neutrino.js
  app/lib/lnd/util.js
  app/lib/lnd/walletUnlocker.js
  app/lib/lnd/walletUnlockerMethods/index.js
  app/lib/zap/controller.js
  app/reducers/ipc.js
  app/reducers/lnd.js
  app/reducers/onboarding.js
  package.json
Labels: bug

#753 feat(lnd): update lnd to latest master build
  package.json
Labels: chore

#733 feat(channels): warn when opening multiple channels to the same node
  app/components/Contacts/SubmitChannelForm.js
  app/components/Contacts/SubmitChannelForm.scss
  app/reducers/contactsform.js
  app/routes/app/containers/AppContainer.js
Labels: enhancement

#747 fix(ui): autofocus forms
  app/components/AmountInput/AmountInput.js
  app/components/Contacts/AddChannel.js
  app/components/Contacts/SubmitChannelForm.js
  app/components/Form/Pay.js
  app/components/Form/Request.js
  test/unit/components/Form/Pay.spec.js
  test/unit/components/Form/Request.spec.js
Labels: bug, enhancement

#758 feat(lnd): update lnd to latest master build
  app/lib/lnd/neutrino.js
  app/lib/zap/controller.js
  app/reducers/invoice.js
  package.json
  resources/lnd.conf
  resources/rpc.proto
  test/unit/lnd/neutrino.spec.js
Labels: chore

#748 feat(autopilot): use new routing flag
  resources/lnd.conf
Labels: enhancement, needs rebase

#769 fix(validation): improve hostname/ip validation
  app/lib/lnd/util.js
  test/unit/__mocks__/dns.js
  test/unit/lnd/util.spec.js
Labels: bug, enhancement

#768 fix(log): log lnd stderr output as errors
  app/lib/lnd/neutrino.js
  app/lib/utils/log.js
Labels: enhancement

#756 Chore/update all dependencies
  app/package.json
  app/routes.js
  app/routes/app/containers/AppContainer.js
  app/yarn.lock
  package.json
  yarn.lock
Labels: chore

#771 refactor(styles): use portable scss include path
  app/components/Activity/Activity.scss
  app/components/Activity/ActivityModal/ActivityModal.scss
  app/components/Activity/Countdown/Countdown.scss
  app/components/Activity/InvoiceModal/InvoiceModal.scss
  app/components/Activity/PaymentModal/PaymentModal.scss
  app/components/Activity/Transaction/Transaction.scss
  app/components/Activity/TransactionModal/TransactionModal.scss
  app/components/App/App.scss
  app/components/Contacts/AddChannel/AddChannel.scss
  app/components/Contacts/ChannelForm/ChannelForm.scss
  app/components/Contacts/ConnectManually/ConnectManually.scss
  app/components/Contacts/ContactModal/ContactModal.scss
  app/components/Contacts/ContactsForm/ContactsForm.scss
  app/components/Contacts/Network/Network.scss
  app/components/Contacts/SubmitChannelForm/SubmitChannelForm.scss
  app/components/Contacts/SuggestedNodes/SuggestedNodes.scss
  app/components/Form/Form.scss
  app/components/Form/Pay/Pay.scss
  app/components/Form/Request/Request.scss
  app/components/GlobalError/GlobalError.scss
  app/components/LoadingBolt/LoadingBolt.scss
  app/components/Onboarding/Alias/Alias.scss
  app/components/Onboarding/Autopilot/Autopilot.scss
  app/components/Onboarding/BtcPayServer/BtcPayServer.scss
  app/components/Onboarding/ConnectionConfirm/ConnectionConfirm.scss
  app/components/Onboarding/ConnectionDetails/ConnectionDetails.scss
  app/components/Onboarding/ConnectionType/ConnectionType.scss
  app/components/Onboarding/FormContainer/FormContainer.scss
  app/components/Onboarding/InitWallet/InitWallet.scss
  app/components/Onboarding/Login/Login.scss
  app/components/Onboarding/NewWalletPassword/NewWalletPassword.scss
  app/components/Onboarding/NewWalletSeed/NewWalletSeed.scss
  app/components/Onboarding/ReEnterSeed/ReEnterSeed.scss
  app/components/Onboarding/RecoverForm/RecoverForm.scss
  app/components/Onboarding/Signup/Signup.scss
  app/components/Onboarding/Syncing/Syncing.scss
  app/components/Settings/Fiat/Fiat.scss
  app/components/Wallet/ReceiveModal/ReceiveModal.scss
  app/components/Wallet/Wallet.scss
  webpack.config.renderer.dev.dll.js
  webpack.config.renderer.dev.js
  webpack.config.renderer.prod.js
Labels: refactor

#770 refactor(webpack): move config files out of root
  .eslintrc
  internals/webpack/webpack.config.base.js
  internals/webpack/webpack.config.eslint.js
  internals/webpack/webpack.config.main.prod.js
  internals/webpack/webpack.config.renderer.dev.dll.js
  internals/webpack/webpack.config.renderer.dev.js
  internals/webpack/webpack.config.renderer.prod.js
  package.json
Labels: refactor

#782 ci(appveyor): remove node/yarn caches
  appveyor.yml
Labels: devops

#779 test(coverage): disable text coverage reporter
  package.json
Labels: devops

#777 Ci/prevent duplicate builds
  .travis.yml
  appveyor.yml
Labels: devops

#778 ci(jest): remove detectOpenHandles flag
  package.json
Labels: devops

#783 build(flow): ignore config-chain/test/broken.json
  .flowconfig
Labels: devops

#784 test(jest): run jest with --forceExit flag
  package.json
Labels: devops

#785 test(coverage): coverage only for unit tests
  package.json
Labels: devops

#789 chore(deps): remove babel-preset-react-hmre
  package.json
  yarn.lock
Labels: devops

#790 build(ci): per env build config
  .travis.yml
  appveyor.yml
  package.json
  yarn.lock
Labels: devops

#788 ci(release): release per platform
  .travis.yml
  appveyor.yml
Labels: devops

#791 chore(deps): remove react-addons-test-utils
  package.json
  yarn.lock
Labels: devops

#794 test(unit): fix failing test case
  test/unit/components/LoadingBolt.spec.js
Labels: bug

#759 feat(lnd): add lnd release scripts
  internals/scripts/lnd-release/.goreleaser.yml
  internals/scripts/lnd-release/README.md
  internals/scripts/lnd-release/canary.sh
Labels: devops

#792 fix(i18n): parse fiat amounts to number type
  app/lib/utils/btc.js
Labels: bug

#795 fix(wallet): hide zero channel balance
  app/components/Contacts/Network/Network.js
Labels: UX/UI

#781 feat(lnd): update lnd to v0.5-beta
  package.json
Labels: bug, chore, enhancement

#793 chore(fs): remove unused util code
  app/lib/utils/index.js
  app/lib/utils/usd.js
  test/unit/utils/usd.spec.js
Labels: chore

#800 fix(channels): display currencyName in network
  app/components/Contacts/Network/Network.js
Labels: bug

#803 test(e2e): combine e2e test setup/teardown steps
  test/e2e/e2e.spec.js
Labels: devops

#796 fix(channels): fetch in activity mount not app
  app/components/Activity/Activity.js
  app/components/App/App.js
  app/containers/Activity.js
Labels: bug

#798 style(loading): fade out loading bolt
  app/components/LoadingBolt/LoadingBolt.js
  app/components/LoadingBolt/LoadingBolt.scss
  app/containers/Root.js
  app/lib/zap/controller.js
  package.json
  test/unit/zap/controller.spec.js
  yarn.lock
Labels: enhancement

#802 fix(wallet): fix console error in request form
  app/components/Form/Request/Request.js
Labels: bug

#806 fix(wallet): dereference window after closing
  app/lib/zap/controller.js
  app/main.dev.js
Labels: bug

#807 fix(ui): improve login button style
  app/components/Onboarding/Login/Login.js
  app/components/Onboarding/Login/Login.scss
Labels: UX/UI, enhancement

#809 style(sync): vertically centre sync page title
  app/components/Onboarding/Syncing/Syncing.js
  app/components/Onboarding/Syncing/Syncing.scss
Labels: UX/UI

#810 style(onboarding): ensure constant button position
  app/components/Onboarding/FormContainer/FormContainer.scss
Labels: UX/UI

#808 feat(lnd): use free port for lnd
  app/lib/lnd/neutrino.js
  app/lib/zap/controller.js
  package.json
  test/unit/lnd/neutrino.spec.js
  yarn.lock
Labels: enhancement

#811 fix(wallet): hide expired toggle for empty wallet
  app/components/Activity/Activity.js
Labels: UX/UI, enhancement

#812 fix(ui): ensure draggable titlebar
  app/components/App/App.scss
  app/components/Onboarding/FormContainer/FormContainer.js
  app/components/Onboarding/FormContainer/FormContainer.scss
Labels: UX/UI, bug
