Repository LN-Zap/zap-desktop, pull requests merged in 2018-12, with the labels that each got.

#975 feat(grpc): use @grpc/grpc-js grpc implementation
  app/lib/lnd/lightning.js
  app/lib/lnd/methods/index.js
  app/lib/lnd/subscribe/channelgraph.js
  app/lib/lnd/subscribe/invoices.js
  app/lib/lnd/subscribe/transactions.js
  app/lib/lnd/util.js
  app/lib/lnd/walletUnlocker.js
  app/package.json
  app/yarn.lock
  package.json
  yarn.lock
Labels: chore, devops, enhancement

#999 perf(devtools): strip large data from devtools
  app/reducers/network.js
  app/store/configureStore.dev.js
Labels: enhancement

#998 fix(channels): fetch balance on receiving channels
  app/reducers/channels.js
Labels: bug

#1008 fix(pay): ensure lightning: links validate
  app/components/Pay/Pay.js
  app/reducers/pay.js
Labels: bug

#1013 Fix/wallet name
  app/components/Home/WalletHeader.js
  app/components/Home/WalletLauncher.js
  app/components/Home/WalletName.js
  app/components/Home/WalletUnlocker.js
  app/components/Home/WalletsMenu.js
  app/components/Home/index.js
  stories/containers/home.stories.js
  stories/containers/home/WalletHeader.stories.js
  stories/containers/home/WalletName.stories.js
  stories/containers/onboarding/onboarding.component.stories.js
  test/unit/components/Home/WalletHeader.spec.js
  test/unit/components/Home/WalletName.spec.js
  test/unit/components/Home/__snapshots__/WalletHeader.spec.js.snap
  test/unit/components/Home/__snapshots__/WalletName.spec.js.snap
Labels: bug, next

#1019 fix(syncing): add link to support site when resyncing
  app/components/Syncing/Syncing.js
  app/components/Syncing/messages.js
  app/components/UI/QRCode.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  stories/containers/syncing.stories.js
  test/unit/components/UI/__snapshots__/QRCode.spec.js.snap
Labels: enhancement, next

#1028 feat(wallet): delete wallet from filesystem
  app/components/GlobalError/GlobalError.js
  app/preload.js
  app/reducers/info.js
  app/reducers/wallet.js
Labels: enhancement, next

#1029 feat(ui): add warning about keeping seed private
  app/components/Icon/Warning.js
  app/components/Onboarding/Steps/SeedView.js
  app/components/Onboarding/Steps/messages.js
  app/components/UI/Message.js
  app/icons/warning.svg
  app/styles/variables.scss
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  test/unit/components/UI/__snapshots__/Message.spec.js.snap
Labels: enhancement, next

#1031 fix(wallet): display wallet name in settings menu
  app/components/Home/WalletHeader.js
  app/components/Home/WalletsMenu.js
  app/components/Home/index.js
  app/components/Pay/PaySummaryLightning.js
  app/components/Pay/PaySummaryOnChain.js
  app/components/Request/RequestSummary.js
  app/components/UI/index.js
  app/components/Util/Truncate.js
  app/components/Util/WalletName.js
  app/components/Util/index.js
  app/components/Wallet/Wallet.js
  app/containers/Activity.js
  stories/containers/home/WalletName.stories.js
  test/unit/components/UI/Truncate.spec.js
  test/unit/components/Util/WalletName.spec.js
  test/unit/components/Util/__snapshots__/WalletName.spec.js.snap
Labels: enhancement, next

#1030 fix(sync): progress bar only consider remaining sync
  app/components/Syncing/Syncing.js
  app/reducers/lnd.js
Labels: enhancement, next

#1036 feat(ui): add status indicator to settings menu
  app/components/Contacts/Network/Network.js
  app/components/Contacts/Network/Network.scss
  app/components/Settings/Settings.js
  app/components/Settings/Settings.scss
  app/components/UI/StatusIndicator.js
  app/components/UI/index.js
  app/components/Wallet/Wallet.js
  app/components/Wallet/Wallet.scss
  app/themes/base.js
  stories/components/statusindicator.stories.js
  test/unit/components/UI/StatusIndicator.spec.js
  test/unit/components/UI/__snapshots__/StatusIndicator.spec.js.snap
Labels: UX/UI, next

#1009 fix(readme): update screenshot to current designs
  README.md
Labels: documentation

#1040 perf(grpc): debounce channel fetching
  app/reducers/channels.js
  package.json
  yarn.lock
Labels: enhancement

#1044 fix(ui): autohide scrollbars
  .storybook/config.js
  app/components/Settings/Fiat/Fiat.scss
  app/components/Settings/Locale/Locale.scss
  app/components/UI/GlobalStyle.js
  app/components/UI/MainContent.js
  app/components/UI/Panel.js
  test/unit/components/UI/__snapshots__/MainContent.spec.js.snap
  test/unit/components/UI/__snapshots__/Modal.spec.js.snap
  test/unit/components/UI/__snapshots__/Panel.spec.js.snap
Labels: UX/UI

#1045 perf(grpc): throttle calls to fetch channels
  app/reducers/channels.js
  package.json
  yarn.lock
Labels: bug, next

#1056 fix(pay): allow sending without route info
  app/components/Pay/Pay.js
  app/components/Pay/messages.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: enhancement, next

#1065 build(node): increase node engine version to >=8.11.2
  package.json
Labels: chore, next

#1057 fix(invoice): include route hints for local nodes
  app/reducers/invoice.js
Labels: bug, next

#1055 chore(i18n): update onboarding language strings
  app/components/Onboarding/Steps/ConnectionType.js
  app/components/Onboarding/Steps/messages.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: UX/UI, next

#1062 docs(readme): update contributor list
  README.md
Labels: chore

#1070 style(network): clean up network list
  app/components/Contacts/AddChannel/AddChannel.js
  app/components/Contacts/Network/Network.js
  app/components/Wallet/Wallet.js
Labels: UX/UI, next

#1074 perf(init): initialise wallets from db early
  app/reducers/wallet.js
Labels: enhancement, next

#1073 fix(i18n): notification translatability
  app/components/Activity/InvoiceModal/InvoiceModal.js
  app/components/Activity/InvoiceModal/messages.js
  app/components/Request/RequestSummary.js
  app/components/Request/messages.js
  app/components/Syncing/Syncing.js
  app/components/Syncing/messages.js
  app/components/Wallet/ReceiveModal/ReceiveModal.js
  app/components/Wallet/ReceiveModal/messages.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: bug, next

#1077 style(panel): explicitly enable panel scroll bars
  app/components/Activity/Activity.js
  app/components/Contacts/AddChannel/AddChannel.js
  app/components/Contacts/Network/Network.js
  app/components/Pay/Pay.js
  app/components/Request/Request.js
  app/components/Syncing/Syncing.js
  app/components/UI/Modal.js
  app/components/UI/Panel.js
  test/unit/components/UI/__snapshots__/Modal.spec.js.snap
  test/unit/components/UI/__snapshots__/Panel.spec.js.snap
Labels: UX/UI, next

#1066 fix(onboarding): launch onboarding if no wallets
  app/containers/Initializer.js
Labels: bug, next

#1085 fix(redux): dont mutate network data
  app/store/configureStore.dev.js
Labels: bug, next

#1083 fix(network): always show channel balances
  app/components/Contacts/Network/Network.js
Labels: enhancement, next

#1099 fix(main): fix url parsing issue with lightning links
  app/main.dev.js
Labels: bug, next

#1101 build(webpack): copy empty.html to final build
  internals/webpack/webpack.config.renderer.prod.js
Labels: bug

#1106 fix(lnd): use static ports for production builds
  app/lib/lnd/neutrino.js
  resources/lnd.conf
Labels: enhancement

#1109 fix(electron): include preload.js in production build
  .eslintrc.js
  app/main.dev.js
  app/package.json
  app/yarn.lock
  internals/webpack/webpack.config.main.prod.js
  package.json
Labels: bug

#1111 fix(wallet): ensure describe network on timer
  app/components/App/App.js
Labels: bug

#1114 style(theme): fix issues with light theme
  app/components/Activity/InvoiceModal/InvoiceModal.js
  app/components/Activity/PaymentModal/PaymentModal.js
  app/components/Activity/TransactionModal/TransactionModal.js
  app/components/Wallet/ReceiveModal/ReceiveModal.js
  app/components/Wallet/ReceiveModal/ReceiveModal.scss
Labels: bug

#1116 fix: load wallet settings from store
  app/lib/zap/controller.js
  app/reducers/channels.js
  app/reducers/invoice.js
  app/reducers/lnd.js
  app/reducers/onboarding.js
Labels: bug

#1126 fix(windows): ensure yarn dev works on windows
  package.json
Labels: devops, windows

#1129 build(electron): set autoupdate channel to "beta"
  app/lib/zap/updater.js
Labels: chore, devops

#1122 fix(activity): ensure activity dates are correct
  app/reducers/payment.js
  app/reducers/ticker.js
  app/reducers/transaction.js
Labels: bug

#1113 fix(home): show connection errors
  app/components/Home/Home.js
  app/components/Home/WalletLauncher.js
  app/containers/Home.js
  app/reducers/lnd.js
Labels: bug

#1118 fix(wallet): save seed in wallet import
  app/components/Onboarding/Onboarding.js
  app/components/Onboarding/Steps/ConnectionType.js
  app/components/Onboarding/Steps/Recover.js
  app/containers/Onboarding.js
  app/preload.js
  app/reducers/lnd.js
  app/store/db.js
Labels: bug

#1112 fix(wallet): ucfirst error strings
  app/lib/utils/userFriendlyErrors.js
  app/reducers/payment.js
  app/reducers/transaction.js
Labels: enhancement

#1140 fix(electron): clean up and fix app quit process
  app/lib/zap/controller.js
  app/main.dev.js
Labels: bug, enhancement

#1151 fix(migrate): migrate old wallets early
  app/store/db.js
Labels: bug

#1155 chore: bump version to 0.3.1-beta
  app/package.json
  package.json
Labels: chore

#1153 fix(wallet): fix lightning/lndconnect links
  app/main.dev.js
Labels: bug

#1154 fix(wallet): display correct amount on send button
  app/components/Pay/Pay.js
Labels: bug

#1161 chore(version): bump version to v0.3.2-beta
  app/package.json
  package.json
Labels: chore

#1167 fix(pay): update bolt11 to support millisatoshis
  package.json
  yarn.lock
Labels: bug

#1174 fix(boot): redirect to launchpad on failed connect
  app/components/Home/WalletLauncher.js
  app/containers/Initializer.js
  app/containers/Root.js
Labels: bug

#1159 fix(app): reset onboarding after app refresh
  app/containers/Initializer.js
  app/containers/Logout.js
  app/lib/zap/controller.js
  app/reducers/app.js
  app/reducers/onboarding.js
  app/reducers/wallet.js
Labels: bug

#1203 fix(ui): set global error z-index to 99999
  app/components/GlobalError/GlobalError.js
Labels: type: bug
