Repository LN-Zap/zap-desktop, pull requests merged in 2018-10, with the labels that each got.

#827 ci(jest): set maxWorkers to 2
  package.json
  test/e2e/e2e.spec.js
Labels: devops

#832 ci(jest): use forceExit
  package.json
Labels: devops

#829 fix(channels): handle suggested nodes load failure
  app/components/Contacts/SuggestedNodes/SuggestedNodes.js
  app/components/Contacts/SuggestedNodes/messages.js
  app/reducers/channels.js
  app/translations/en.json
Labels: bug, enhancement

#828 fix(lnd): show error on problem connecting to lnd
  app/containers/Root.js
  app/lib/zap/controller.js
  app/reducers/onboarding.js
Labels: bug, enhancement

#835 ci(jest): increase timeouts
  test/e2e/e2e.spec.js
Labels: devops

#801 Chore/update deps
  app/main.dev.js
  app/package.json
  package.json
  yarn.lock
Labels: chore

#831 style(scss): use function to apply z-index
  .stylelintrc
  app/components/Contacts/ChannelForm/ChannelForm.scss
  app/components/Contacts/ConnectManually/ConnectManually.scss
  app/components/Contacts/Network/Network.scss
  app/components/Form/Form.scss
  app/components/Form/Pay/Pay.scss
  app/components/Form/Request/Request.scss
  app/components/GlobalError/GlobalError.scss
  app/components/LoadingBolt/LoadingBolt.scss
  app/components/Settings/Settings.scss
  app/styles/app.global.scss
  app/styles/tooltip.scss
  app/styles/variables.scss
  package.json
  yarn.lock
Labels: UX/UI

#842 build(yarn): regenerate yarn.lock files
  app/yarn.lock
  yarn.lock
Labels: chore

#836 Change autopilot strings
  app/components/Onboarding/Autopilot/Autopilot.js
  app/components/Onboarding/Autopilot/messages.js
  app/translations/bg-BG.json
  app/translations/cs-CZ.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/hr-HR.json
  app/translations/ja-JP.json
  app/translations/nl-NL.json
  app/translations/pt-BR.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: UX/UI, needs rebase

#851 fix(ui): ensure settings menu shows on top
  app/components/Contacts/ChannelForm/ChannelForm.scss
  app/components/Contacts/ConnectManually/ConnectManually.scss
  app/components/Contacts/Network/Network.scss
  app/components/Form/Form.scss
  app/components/Settings/Settings.scss
  app/styles/tooltip.scss
Labels: UX/UI, bug

#852 chore(version): bump to 0.2.3-beta
  app/package.json
  package.json
Labels: chore

#846 chore(deps): update babel to v7
  .babelrc
  app/lib/lnd/lightning.js
  app/lib/lnd/walletUnlocker.js
  app/lib/zap/controller.js
  app/main.dev.js
  app/store/configureStore.dev.js
  app/store/configureStore.prod.js
  babel.config.js
  internals/webpack/webpack.config.eslint.js
  internals/webpack/webpack.config.renderer.dev.js
  package.json
  test/unit/zap/controller.spec.js
  yarn.lock
Labels: chore

#850 fix: reduce main bundle size (exclude locale data)
  app/components/Settings/Locale/Locale.js
  app/index.js
  app/lib/i18n/index.js
  app/lib/i18n/locale.js
  app/lib/i18n/translation.js
  app/lib/utils/i18n.js
  app/lib/zap/menuBuilder.js
  app/reducers/locale.js
  app/reducers/ticker.js
Labels: enhancement

#854 fix(styles): clean up and standardize buttons
  app/components/Activity/Activity.js
  app/components/Activity/Activity.scss
  app/components/App/App.js
  app/components/Contacts/AddChannel/AddChannel.js
  app/components/Contacts/AddChannel/AddChannel.scss
  app/components/Contacts/ConnectManually/ConnectManually.js
  app/components/Contacts/ConnectManually/ConnectManually.scss
  app/components/Contacts/SubmitChannelForm/SubmitChannelForm.js
  app/components/Contacts/SubmitChannelForm/SubmitChannelForm.scss
  app/components/Form/Pay/Pay.js
  app/components/Form/Pay/Pay.scss
  app/components/Form/Request/Request.js
  app/components/Form/Request/Request.scss
  app/components/Onboarding/FormContainer/FormContainer.js
  app/components/Onboarding/FormContainer/FormContainer.scss
  app/components/Onboarding/Login/Login.js
  app/components/Onboarding/Login/Login.scss
  app/components/Onboarding/Login/messages.js
  app/components/Settings/Theme/Theme.js
  app/components/Wallet/Wallet.js
  app/components/Wallet/Wallet.scss
  app/containers/Activity.js
  app/containers/App.js
  app/containers/Root.js
  app/index.js
  app/lib/lnd/subscribe/channelgraph.js
  app/reducers/index.js
  app/reducers/settings.js
  app/reducers/theme.js
  app/styles/app.global.scss
  app/translations/en.json
  test/unit/components/Form/Pay.spec.js
  test/unit/reducers/__snapshots__/settings.spec.js.snap
Labels: UX/UI, enhancement

#857 fix(styles): clean up global error style
  app/components/Activity/Activity.scss
  app/components/GlobalError/GlobalError.js
  app/components/GlobalError/GlobalError.scss
  app/components/UI/GlobalStyle.js
  app/components/UI/Notification.js
  app/containers/Root.js
  app/styles/app.global.scss
  test/unit/components/UI/__snapshots__/Notification.spec.js.snap
Labels: UX/UI, enhancement

#856 feat(ui): add Page components
  app/components/UI/MainContent.js
  app/components/UI/Page.js
  app/components/UI/Sidebar.js
  stories/components/page-elements.stories.js
  test/unit/components/UI/MainContent.spec.js
  test/unit/components/UI/Page.spec.js
  test/unit/components/UI/Sidebar.spec.js
  test/unit/components/UI/__snapshots__/MainContent.spec.js.snap
  test/unit/components/UI/__snapshots__/Page.spec.js.snap
  test/unit/components/UI/__snapshots__/Sidebar.spec.js.snap
Labels: Feature, UX/UI

#859 feat(ui): add Menu components
  app/components/UI/Menu.js
  app/components/UI/MenuItem.js
  app/components/UI/MenuItemGroup.js
  package.json
  stories/components/menu.stories.js
  test/unit/components/UI/Menu.spec.js
  test/unit/components/UI/__snapshots__/Menu.spec.js.snap
  yarn.lock
Labels: Feature

#866 feat(settings): use indexedDb for persistent data
  app/containers/Root.js
  app/index.js
  app/lib/i18n/index.js
  app/lib/lnd/config.js
  app/lib/zap/controller.js
  app/lib/zap/menuBuilder.js
  app/main.dev.js
  app/reducers/address.js
  app/reducers/channels.js
  app/reducers/info.js
  app/reducers/invoice.js
  app/reducers/lnd.js
  app/reducers/loading.js
  app/reducers/locale.js
  app/reducers/onboarding.js
  app/reducers/theme.js
  app/reducers/ticker.js
  app/store/db.js
  app/themes/index.js
  package.json
  test/unit/__mocks__/dexie.js
  test/unit/lnd/lightning.spec.js
  test/unit/lnd/lnd-config.spec.js
  test/unit/lnd/neutrino.spec.js
  test/unit/reducers/ticker.spec.js
  test/unit/zap/controller.spec.js
  yarn.lock
Labels: Feature, enhancement

#841 feat(lnd): update lnd to v0.5-beta-247-g68d96488
  app/lib/lnd/neutrino.js
  package.json
  resources/rpc.proto
Labels: enhancement

#873 fix(boot): issue with fetching user settings
  app/empty.html
  app/main.dev.js
  internals/webpack/webpack.config.renderer.dev.js
  internals/webpack/webpack.config.renderer.prod.js
  package.json
  yarn.lock
Labels: bug

#869 style(storybook): update storybook styles
  .storybook/addons.js
  .storybook/config.js
  .storybook/preview-head.html
  package.json
  yarn.lock
Labels: UX/UI, enhancement

#870 chore(deps): update electron packages
  package.json
  yarn.lock
Labels: chore
