Repository LN-Zap/zap-desktop, pull requests merged in 2018-07, with the labels that each got.

#548 Ensure that we fetch the correct block height in the case where BTCd is mid way through syncing
  app/api/index.js
  app/components/Onboarding/Syncing.js
  app/containers/Root.js
  app/lnd/lib/neutrino.js
  app/lnd/lib/util.js
  app/reducers/ipc.js
  app/reducers/lnd.js
  app/routes/app/containers/AppContainer.js
  app/zap.js
  package.json
  webpack.config.renderer.dev.js
  webpack.config.renderer.prod.js
  yarn.lock
Labels: bug

#538 Handle case where BTCd node is not fully synced with the blockchain
  app/components/Onboarding/Syncing.js
  app/components/Onboarding/Syncing.scss
  app/containers/Root.js
  app/lnd/lib/neutrino.js
  app/reducers/ipc.js
  app/reducers/lnd.js
  app/zap.js
Labels: enhancement

#550 Don't log successful results from lnd as errors
  app/lnd/methods/index.js
Labels: bug

#551 Don't show sent for received tx
  app/components/Activity/TransactionModal.js
Labels: bug

#552 Ensure there are sensible default values for onboarding screens
  app/reducers/onboarding.js
Labels: bug, enhancement

#515 Update docs to suggest building before running tests
  ADVANCED.md
Labels: documentation

#549 Show channel filter when there is an empty active filter
  app/components/Contacts/Network.js
Labels: bug

#553 refactor: add received prop to transaction
  app/components/Activity/TransactionModal.js
  app/reducers/activity.js
  app/reducers/transaction.js
  app/routes/activity/components/components/Transaction/Transaction.js
Labels: enhancement

#556 chore(deps): update electron to latest versions
  package.json
  yarn.lock
Labels: enhancement

#559 fix(accessibility): don't use white on yellow text
  app/components/Contacts/ConnectManually.scss
  app/components/Contacts/SubmitChannelForm.scss
  app/components/Form/Pay.scss
  app/components/Form/Request.scss
Labels: UX/UI

#557 fix(ui): increase currency selector z-index
  app/components/Form/Pay.scss
  app/components/Form/Request.scss
Labels: bug

#558 feat(ui): show activity type icon in activity list
  app/routes/activity/components/components/Activity.scss
  app/routes/activity/components/components/Invoice/Invoice.js
  app/routes/activity/components/components/Payment/Payment.js
  app/routes/activity/components/components/Transaction/Transaction.js
Labels: UX/UI

#570 fix: don't show channel suggestions if pending channels exist
  app/components/Contacts/Network.js
  app/reducers/channels.js
Labels: bug

#573 fix: ensure conditional display uses boolean
  app/components/Contacts/Network.js
Labels: bug

#572 fix(onboarding): default to create new wallet
  app/reducers/onboarding.js
Labels: enhancement

#571 fix(onboarding): remove seed password
  app/components/Onboarding/NewAezeedPassword.js
  app/components/Onboarding/NewAezeedPassword.scss
  app/components/Onboarding/Onboarding.js
  app/containers/Root.js
  app/lnd/methods/walletController.js
  app/reducers/onboarding.js
Labels: enhancement

#568 fix(channel-form): improve copy
  app/components/Contacts/SubmitChannelForm.js
Labels: enhancement

#562 feat(btcpayserver): add support for BTCPayServer
  app/components/Onboarding/BtcPayServer.js
  app/components/Onboarding/BtcPayServer.scss
  app/components/Onboarding/ConnectionConfirm.js
  app/components/Onboarding/ConnectionConfirm.scss
  app/components/Onboarding/ConnectionType.js
  app/components/Onboarding/ConnectionType.scss
  app/components/Onboarding/Onboarding.js
  app/containers/Root.js
  app/lnd/config/index.js
  app/lnd/lib/lightning.js
  app/lnd/lib/util.js
  app/package.json
  app/reducers/onboarding.js
  app/yarn.lock
  app/zap.js
Labels: Feature

#575 fix: only notify if we have not seen the transaction before
  app/reducers/transaction.js
Labels: bug

#585 fix(transaction notification): fix that state access was off the mark
  app/reducers/transaction.js
Labels: bug

#588 chore(deps): update electron-builder
  package.json
  yarn.lock
Labels: bug

#569 build: auto download lnd-binary on install
  app/lnd/config/index.js
  internals/scripts/fetch-lnd-for-packaging.js
  package.json
  webpack.config.renderer.prod.js
  yarn.lock
Labels: enhancement

#353 Generate code coverage reports
  .gitignore
  README.md
  package.json
  yarn.lock
Labels: documentation

#606 fix: honour currency when opening channel
  app/reducers/channels.js
Labels: bug

#603 fix(onboarding): improve existing wallet found message
  app/components/Onboarding/Onboarding.js
  app/containers/Root.js
  app/lnd/walletUnlockerMethods/index.js
  app/reducers/onboarding.js
Labels: enhancement

#605 docs: update advanced documentation
  ADVANCED.md
Labels: documentation

#626 fix(activity): show settled date for paid invoices
  app/routes/activity/components/components/Invoice/Invoice.js
Labels: bug

#634 refactor(grpc): use @grpc/proto-loader
  app/lnd/lib/lightning.js
  app/lnd/lib/walletUnlocker.js
  package.json
  yarn.lock
Labels: bug

#633 refactor(neutrino): more consistent naming in Neutrino class
  app/containers/Root.js
  app/lnd/lib/neutrino.js
  app/reducers/ipc.js
  app/reducers/lnd.js
  app/reducers/onboarding.js
  app/zap.js
Labels: enhancement

#627 fix(activity): show icon for paid invoices
  app/routes/activity/components/components/Invoice/Invoice.js
Labels: bug

#599 build: auto release
  .travis.yml
  appveyor.yml
  package.json
  resources/icons/icon.icns
  resources/icons/icon.ico
  resources/icons/icon.png
Labels: devops

#619 build: auto update
  app/main.dev.js
  app/updater.js
  app/utils/log.js
  package.json
  yarn.lock
Labels: devops

#638 docs(readme): add appveyor build status badge
  README.md
Labels: devops
