Repository LN-Zap/zap-desktop, pull requests merged in 2018-08, with the labels that each got.

#576 feat(onboarding): require explicit external connection configuration
  ADVANCED.md
  app/lnd/index.js
  app/main.dev.js
  app/package.json
  app/yarn.lock
  app/zap.js
  package.json
Labels: enhancement

#547 feat(ux): keep app running when main window closed
  app/lnd/index.js
  app/lnd/lib/lightning.js
  app/lnd/subscribe/channelgraph.js
  app/lnd/subscribe/index.js
  app/lnd/subscribe/invoices.js
  app/lnd/subscribe/transactions.js
  app/lnd/walletUnlockerMethods/index.js
  app/main.dev.js
  app/reducers/channels.js
  app/reducers/ipc.js
  app/reducers/onboarding.js
  app/reducers/requestform.js
  app/zap.js
  package.json
  yarn.lock
Labels: enhancement

#649 chore(deps): update eslint-plugin-json package
  package.json
  yarn.lock
Labels: devops

#647 Update flow typed and ensure our code is processed properly
  .flowconfig
  package.json
  yarn.lock
Labels: devops

#536 Update react to latest v16.x
  app/components/Activity/InvoiceModal.js
  app/components/Activity/PaymentModal.js
  app/components/Activity/TransactionModal.js
  app/components/Contacts/ConnectManually.js
  app/components/Contacts/ContactModal.js
  app/components/Contacts/ContactsForm.js
  app/components/Contacts/Network.js
  app/components/Contacts/SubmitChannelForm.js
  app/components/Form/Pay.js
  app/components/Form/Request.js
  app/components/GlobalError/GlobalError.js
  app/components/Onboarding/Autopilot.js
  app/components/Onboarding/ConnectionDetails.js
  app/components/Onboarding/ConnectionType.js
  app/components/Onboarding/Login.js
  app/components/Onboarding/NewWalletPassword.js
  app/components/Onboarding/Signup.js
  app/components/Wallet/ReceiveModal.js
  app/components/Wallet/Wallet.js
  app/containers/Root.js
  app/index.js
  app/routes/activity/components/Activity.js
  app/routes/activity/components/components/Invoice/Invoice.js
  package.json
  test/components/AnimatedCheckmark.spec.js
  test/components/CryptoIcon.spec.js
  test/components/CurrencyIcon.spec.js
  test/components/Form.spec.js
  test/components/Form/Pay.spec.js
  test/components/Form/Request.spec.js
  test/components/LoadingBolt.spec.js
  webpack.config.renderer.dev.js
  yarn.lock
Labels: enhancement

#656 test(runner): reorganise test suites
  .flowconfig
  app/package.json
  package.json
  test/example.js
  test/runTests.js
  test/unit/components/AnimatedCheckmark.spec.js
  test/unit/components/CryptoIcon.spec.js
  test/unit/components/CurrencyIcon.spec.js
  test/unit/components/Form.spec.js
  test/unit/components/Form/Pay.spec.js
  test/unit/components/Form/Request.spec.js
  test/unit/components/LoadingBolt.spec.js
  test/unit/reducers/__snapshots__/balance.spec.js.snap
  test/unit/reducers/__snapshots__/channels.spec.js.snap
  test/unit/reducers/__snapshots__/form.spec.js.snap
  test/unit/reducers/__snapshots__/info.spec.js.snap
  test/unit/reducers/__snapshots__/invoice.spec.js.snap
  test/unit/reducers/__snapshots__/payment.spec.js.snap
  test/unit/reducers/__snapshots__/peers.spec.js.snap
  test/unit/reducers/__snapshots__/ticker.spec.js.snap
  test/unit/reducers/balance.spec.js
  test/unit/reducers/channels.spec.js
  test/unit/reducers/form.spec.js
  test/unit/reducers/info.spec.js
  test/unit/reducers/invoice.spec.js
  test/unit/reducers/payment.spec.js
  test/unit/reducers/peers.spec.js
  test/unit/reducers/ticker.spec.js
  test/unit/utils/usd.spec.js
  yarn.lock
Labels: refactor

#657 Add backend support for multiple connections
  app/containers/Root.js
  app/lib/lnd/config.js
  app/lib/lnd/index.js
  app/lib/lnd/lightning.js
  app/lib/lnd/neutrino.js
  app/lib/lnd/util.js
  app/lib/lnd/walletUnlocker.js
  app/lib/lnd/walletUnlockerMethods/index.js
  app/lib/utils/log.js
  app/lib/zap/controller.js
  app/reducers/onboarding.js
  package.json
  test/unit/__mocks__/grpc.js
  test/unit/lnd/lnd-config.spec.js
  yarn.lock
Labels: Feature

#658 feat(lnd): update BTCD and LND to latest versions
  app/components/Onboarding/Syncing.js
  app/containers/Root.js
  app/lib/lnd/neutrino.js
  app/lib/zap/controller.js
  app/reducers/ipc.js
  app/reducers/lnd.js
  package.json
  resources/lnd.conf
  resources/rpc.proto
  test/unit/lnd/neutrino.spec.js
  yarn.lock
Labels: devops

#668 fix(app): quit when window closed on non-darwin
  app/lib/zap/controller.js
Labels: bug, linux

#667 fix(activity): correct tooltips in activity log
  app/routes/activity/components/components/Invoice/Invoice.js
  app/routes/activity/components/components/Payment/Payment.js
  app/routes/activity/components/components/Transaction/Transaction.js
Labels: UX/UI

#672 fix(invoice): only notify on settled invoices
  app/reducers/invoice.js
Labels: bug

#690 fix(lnd): only connect to single btcd host
  app/lib/lnd/neutrino.js
Labels: enhancement, sync

#691 fix(lnd): don't treat filters as filter headers
  app/lib/lnd/neutrino.js
Labels: bug

#688 fix(lnd): prevent full chain sync on wallet init
  app/components/Onboarding/Onboarding.js
  app/containers/Root.js
  app/lib/lnd/methods/walletController.js
  app/reducers/onboarding.js
Labels: enhancement, sync

#679 fix(grpc): ensure full disconnect on window close
  app/lib/lnd/config.js
  app/lib/lnd/lightning.js
  app/lib/lnd/subscribe/channelgraph.js
  app/lib/lnd/subscribe/invoices.js
  app/lib/lnd/subscribe/transactions.js
  app/lib/lnd/util.js
  app/lib/zap/controller.js
  app/main.dev.js
  test/e2e/e2e.spec.js
  test/unit/__mocks__/electron.js
  test/unit/lnd/lightning.spec.js
  test/unit/lnd/lnd-config.spec.js
  test/unit/lnd/neutrino.spec.js
Labels: bug

#683 feat(lnd): show error message if lnd exits
  app/lib/lnd/neutrino.js
  app/lib/zap/controller.js
  test/unit/lnd/neutrino.spec.js
Labels: enhancement

#684 fix(lnd): disable lnd REST interface on port 8080
  resources/lnd.conf
Labels: enhancement

#693 fix(ux): show loading bolt while seed is generated
  app/reducers/onboarding.js
Labels: UX/UI

#687 fix(lnd): update lnd to latest version
  package.json
  resources/rpc.proto
Labels: enhancement

#692 fix(ui): increase line-height in seed reentry form
  app/components/Onboarding/ReEnterSeed.scss
  app/components/Onboarding/RecoverForm.scss
Labels: UX/UI, linux

#689 fix(invoice-amt-paid): settled invoices show amt_paid
  app/components/Activity/InvoiceModal.js
  app/lib/utils/btc.js
  app/reducers/invoice.js
  app/routes/activity/components/components/Invoice/Invoice.js
Labels: bug

#703 chore(deps): update jest to v23.5.0
  package.json
  yarn.lock
Labels: devops

#702 build(flow): include node_modules in flow config
  .flowconfig
Labels: bug

#701 fix(wallet): ensure clean state after refresh
  app/lib/zap/controller.js
Labels: bug

#695 fix(wallet): fetch updated channels and balance after a new transaction
  app/lib/lnd/subscribe/channelgraph.js
  app/reducers/transaction.js
  test/unit/reducers/__snapshots__/transaction.spec.js.snap
  test/unit/reducers/transaction.spec.js
Labels: bug

#705 feat(components): add new AmountInput component
  app/components/AmountInput/AmountInput.js
  app/components/AmountInput/AmountInput.scss
  app/components/AmountInput/index.js
  app/components/Contacts/SubmitChannelForm.js
  app/components/Form/Pay.js
  app/components/Form/Request.js
  app/routes/app/containers/AppContainer.js
  test/unit/components/AmountInput.spec.js
  test/unit/components/Form.spec.js
  test/unit/components/Form/Pay.spec.js
  test/unit/components/Form/Request.spec.js
Labels: bug, enhancement

#707 fix(lnd): ensure graceful shutdown
  app/lib/lnd/lightning.js
  app/lib/zap/controller.js
Labels: bug

#714 feat(lnd): update lnd to v0.4.2-beta-913-g26f68da5
  app/lib/lnd/config.js
  app/lib/lnd/neutrino.js
  package.json
  resources/rpc.proto
  test/unit/lnd/lnd-config.spec.js
Labels: enhancement

#710 feat(errors): create a util for making error messages more user-friendly
  app/components/GlobalError/GlobalError.js
  app/components/GlobalError/GlobalError.scss
  app/lib/utils/userFriendlyErrors.js
  test/unit/utils/userFriendlyErrors.spec.js
Labels: enhancement

#719 fix(lnd): ensure graceful shutdown
  app/lib/lnd/lightning.js
  app/lib/lnd/neutrino.js
  app/lib/zap/controller.js
  package.json
  test/unit/lnd/neutrino.spec.js
  yarn.lock
Labels: enhancement

#718 fix(lnd): do not resolve after rejecting
  app/lib/lnd/methods/channelController.js
  app/lib/lnd/methods/index.js
  app/lib/lnd/methods/invoicesController.js
  app/lib/lnd/methods/networkController.js
  app/lib/lnd/methods/paymentsController.js
  app/lib/lnd/methods/peersController.js
  app/lib/lnd/methods/walletController.js
  app/lib/lnd/push/closechannel.js
  app/lib/lnd/push/openchannel.js
  app/lib/lnd/push/subscribeinvoice.js
Labels: bug

#697 feat(toggle-expired-requests): add button to show/hide expired requests
  app/reducers/activity.js
  app/routes/activity/components/Activity.js
  app/routes/activity/components/Activity.scss
  app/routes/activity/containers/ActivityContainer.js
Labels: Feature

#720 fix(channels): closing channels link to closing_txid
  app/components/Contacts/Network.js
Labels: enhancement

#728 fix(grpc): use Numbers to represent long values
  app/lib/lnd/lightning.js
  app/lib/lnd/walletUnlocker.js
Labels: bug

#729 chore(version): bump to 0.2.2-beta
  app/package.json
  package.json
Labels: chore

#678 chore(deps): update grpc to v1.14.1
  app/package.json
  app/yarn.lock
Labels: chore

#730 Update maintainers and contributors list in README
  README.md
Labels: chore
