Repository LN-Zap/zap-desktop, pull requests merged in 2019-03, with the labels that each got.

#1640 feat(channels): categorise opening/funding transactions
  app/components/Activity/Transaction/Transaction.js
  app/components/Activity/Transaction/messages.js
  app/lib/lnd/methods/channelController.js
  app/lib/lnd/methods/index.js
  app/reducers/activity.js
  app/reducers/channels.js
  app/reducers/transaction.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  test/unit/reducers/__snapshots__/activity.spec.js.snap
  test/unit/reducers/__snapshots__/channels.spec.js.snap
Labels: scope: channels, type: feature

#1675 Fix/currency dropdown opacity
  app/components/Channels/ChannelCapacity.js
  app/components/UI/Dropdown.js
Labels: scope: channels, type: bug

#1674 fix(ui): make node search case insensitive
  app/reducers/contactsform.js
Labels: scope: channels, type: enhancement

#1673 fix(ui): include suggested nodes in search results
  app/reducers/contactsform.js
Labels: scope: channels, type: enhancement

#1678 fix(ui): fix last item dropshadow glitch in channel summary list
  app/components/Channels/ChannelSummaryList.js
Labels: scope: channels, type: bug

#1664 fix(sync): ensure QR code shown when syncing
  app/components/Syncing/Syncing.js
  app/reducers/info.js
  app/reducers/lnd.js
Labels: type: bug

#1677 feat(activity): new activity search and filters
  app/components/Activity/Activity.js
  app/components/Activity/ActivityActions/ActivityActions.js
  app/components/Activity/ActivityActions/ActivityFilter.js
  app/components/Activity/ActivityActions/ActivityRefresh.js
  app/components/Activity/ActivityActions/ActivitySearch.js
  app/components/Activity/ActivityActions/index.js
  app/components/Activity/ActivityActions/messages.js
  app/components/Activity/ActivityListItem.js
  app/components/Activity/Transaction/Transaction.js
  app/components/Activity/Transaction/messages.js
  app/components/Activity/messages.js
  app/components/Icon/Sync.js
  app/components/UI/Button.js
  app/components/Util/hooks/index.js
  app/components/Util/hooks/useDebounce.js
  app/containers/Activity.js
  app/containers/Activity/ActivityActions.js
  app/icons/sync.svg
  app/reducers/activity.js
  app/reducers/channels.js
  app/reducers/transaction.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  stories/icons/icon.stories.js
  test/unit/components/UI/__snapshots__/Dialog.spec.js.snap
  test/unit/reducers/__snapshots__/activity.spec.js.snap
  test/unit/reducers/activity.spec.js
Labels: scope: ui/ux, scope: wallet, type: enhancement

#1695 feat(channels): show closing transaction in channel detail
  app/components/Channels/ChannelCardList.js
  app/components/Channels/ChannelCardListItem.js
  app/components/Channels/ChannelData.js
  app/components/Channels/ChannelDetail.js
  app/components/Channels/Channels.js
  app/components/Channels/ChannelsViewSwitcher.js
  app/components/Channels/constants.js
  app/components/Channels/messages.js
  app/reducers/channels.js
  test/unit/reducers/__snapshots__/channels.spec.js.snap
Labels: scope: channels, type: enhancement

#1665 feat(channels): validate channel amount input
  app/components/Channels/ChannelCreateForm.js
  app/components/Channels/messages.js
  app/components/UI/CurrencyFieldGroup.js
  app/components/UI/Input.js
  app/components/UI/NodePubkeyInput.js
  app/components/UI/RadioGroup.js
  app/components/UI/TextArea.js
  app/containers/Channels/ChannelCreateForm.js
  app/lib/lnd/methods/index.js
  app/reducers/balance.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  stories/Provider.js
  stories/containers/pay.stories.js
  test/unit/reducers/__snapshots__/balance.spec.js.snap
  test/unit/reducers/balance.spec.js
Labels: scope: channels, type: enhancement

#1696 feat(wallet): show confirmations in transaction detail
  app/components/Activity/TransactionModal/TransactionModal.js
  app/components/Activity/TransactionModal/messages.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: scope: wallet, type: enhancement

#1699 feat(channels): remember use selected channel view mode
  app/containers/Initializer.js
  app/containers/Root.js
  app/reducers/channels.js
  app/reducers/locale.js
  app/reducers/onboarding.js
  app/reducers/settings.js
  app/reducers/theme.js
  app/reducers/ticker.js
  app/reducers/utils.js
  app/reducers/wallet.js
Labels: scope: channels, scope: ui/ux, type: enhancement

#1680 fix(activity): show limbo amount for force close transactions
  app/components/Activity/Transaction/Transaction.js
  app/components/Activity/TransactionModal/TransactionModal.js
  app/components/Activity/TransactionModal/messages.js
  app/reducers/activity.js
  app/reducers/transaction.js
Labels: scope: channels, type: enhancement

#1707 chore(i18n): extract new translation strings
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: type: chore

#1693 refactor(react): update hot reload implementation
  app/containers/Root.js
  app/reducers/info.js
  app/store/configureStore.dev.js
  internals/webpack/webpack.config.renderer.dev.js
  package.json
  yarn.lock
Labels: status: needs rebase, type: refactor

#1703 refactor: move hocs and hooks to app top level
  .flowconfig
  app/components/Activity/ActivityActions/ActivitySearch.js
  app/components/Channels/ChannelCardListItem.js
  app/components/Channels/ChannelCloseDialog.js
  app/components/Channels/ChannelCreateSummary.js
  app/components/Channels/ChannelHeader.js
  app/components/Channels/ChannelNodeSearch.js
  app/components/Channels/ChannelSummaryListItem.js
  app/components/Home/DeleteWalletDialog.js
  app/components/UI/CryptoAmountInput.js
  app/components/UI/FiatAmountInput.js
  app/components/UI/Input.js
  app/components/UI/OpenDialogInput.js
  app/components/UI/TextArea.js
  app/components/withEllipsis/index.js
  app/components/withLoading/index.js
  app/components/withNumberInputMask/index.js
  app/components/withOpenDialog/index.js
  app/components/withRequiredValidation/index.js
  app/containers/ModalStack.js
  app/containers/Onboarding.js
  app/containers/Root.js
  app/containers/Syncing.js
  app/hocs/index.js
  app/hocs/withEllipsis.js
  app/hocs/withLoading.js
  app/hocs/withNumberInputMask.js
  app/hocs/withOpenDialog.js
  app/hocs/withRequiredValidation.js
  app/hooks/index.js
  app/hooks/useCloseOnUnmount.js
  app/hooks/useDebounce.js
  app/hooks/useOnKeydown.js
Labels: type: refactor

#1711 fix(ui): implement tx confirmation count update
  app/components/App/App.js
  app/components/Util/hooks/useInterval.js
  app/containers/App.js
  app/hooks/index.js
  app/hooks/useInterval.js
Labels: scope: wallet, status: needs rebase, type: bug, type: refactor

#1701 refactor: remove unused getLegacyStatus method
  app/reducers/channels.js
Labels: type: refactor

#1704 refactor: mark non-required props as such
  app/components/UI/CurrencyFieldGroup.js
  app/containers/Channels/ChannelCloseDialog.js
Labels: type: refactor

#1712 fix(ui): standardize hr line weights
  app/components/Activity/Activity.js
  app/components/Activity/InvoiceModal/InvoiceModal.js
  app/components/Activity/PaymentModal/PaymentModal.js
  app/components/Activity/TransactionModal/TransactionModal.js
  app/components/Channels/ChannelCardListItem.js
  app/components/Channels/ChannelCreate.js
  app/components/Channels/ChannelCreateForm.js
  app/components/Channels/ChannelCreateSummary.js
  app/components/Channels/ChannelData.js
  app/components/Channels/ChannelHeader.js
  app/components/Channels/ChannelNodeSearch.js
  app/components/Pay/Pay.js
  app/components/Pay/PaySummaryLightning.js
  app/components/Pay/PaySummaryOnChain.js
  app/components/Request/Request.js
  app/components/Request/RequestSummary.js
  app/components/UI/Bar.js
  app/components/Wallet/ReceiveModal/ReceiveModal.js
  app/themes/base.js
  test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
  test/unit/components/Pay/__snapshots__/PaySummaryOnchain.spec.js.snap
  test/unit/components/UI/Bar.spec.js
  test/unit/components/UI/__snapshots__/Bar.spec.js.snap
Labels: scope: ui/ux, type: enhancement, type: refactor

#1713 fix(ui): use consistent pay form icon
  app/components/Icon/Hand.js
  app/components/Icon/PaperPlane.js
  app/components/Icon/Receive.js
  app/components/Icon/Send.js
  app/components/Pay/PayHeader.js
  app/icons/hand.svg
  app/icons/paper-plane.svg
  app/icons/receive.svg
  app/icons/send.svg
  stories/icons/icon.stories.js
  test/unit/components/Pay/__snapshots__/PayHeader.spec.js.snap
Labels: scope: wallet, type: enhancement

#1708 chore(devops): configure welcome-bot
  .github/config.yml
Labels: type: chore

#1719 refactor: mark non-required properties as such
  app/containers/Initializer.js
Labels: type: refactor

#1722 fix(ui): repair delete wallet action
  app/reducers/wallet.js
Labels: type: bug 🐛

#1727 fix(app): retain wallets & settings data on logout
  app/containers/Settings.js
  app/reducers/index.js
  app/reducers/settings.js
  app/reducers/settingsmenu.js
  test/unit/reducers/__snapshots__/settingsmenu.spec.js.snap
  test/unit/reducers/settingsmenu.spec.js
Labels: type: bug 🐛

#1717 chore(i18n): update Spanish translation strings
  app/translations/es-ES.json
Labels: type: chore

#1718 feat(ui): add ability to edit remote connections that use lndconnect
  app/components/Home/WalletLauncher.js
  app/components/Home/WalletSettingsFormRemote.js
  app/components/Home/messages.js
  app/components/Onboarding/Steps/ConnectionDetailsString.js
  app/components/Onboarding/Steps/SeedConfirm.js
  app/components/UI/LndConnectionStringEditor.js
  app/components/UI/LndConnectionStringInput.js
  app/components/UI/TextArea.js
  app/components/UI/index.js
  app/lib/utils/connectionString.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: scope: wallet, type: feature

#1732 fix(home): increase sidebar width
  app/components/Home/Home.js
  app/components/UI/Sidebar.js
Labels: scope: onboarding, scope: ui/ux

#1745 refactor: auto-determine stable version
  CONTRIBUTING.md
  app/lib/utils/index.js
  app/lib/utils/isStableVersion.js
  config/default.js
  test/unit/utils/isStableVersion.spec.js
Labels: type: refactor

#1738 fix(ui): properly detect active submenu
  app/containers/Settings.js
Labels: type: bug 🐛

#1737 feat(ui): add contextual help component
  app/components/Request/Request.js
  app/components/Request/messages.js
  app/components/UI/Input.js
  app/components/UI/TextArea.js
  app/components/UI/Tooltip.js
  app/components/UI/index.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  stories/_general/_welcome.stories.js
Labels: scope: ui/ux, type: feature

#1724 feat(wallet): support bitcoin payment uris (bip-21)
  app/components/App/App.js
  app/components/Pay/Pay.js
  app/components/UI/CurrencyFieldGroup.js
  app/components/Wallet/Wallet.js
  app/containers/App.js
  app/containers/Initializer.js
  app/lib/utils/sanitize.js
  app/main.js
  app/reducers/app.js
  app/reducers/info.js
  app/reducers/ipc.js
  app/reducers/modal.js
  app/reducers/pay.js
  app/reducers/utils.js
  package.json
  test/unit/reducers/__snapshots__/info.spec.js.snap
  yarn.lock
Labels: scope: wallet, type: feature

#1755 refactor: add ArrowDown and ArrowUp icon
  app/components/Icon/ArrowDown.js
  app/components/Icon/ArrowUp.js
  app/icons/arrow-down.svg
  app/icons/arrow-up.svg
  stories/icons/icon.stories.js
Labels: type: refactor

#1742 feat(ui): implement better getting started ui
  app/components/Icon/BoltOnboarding.js
  app/components/Icon/ConnectOnboarding.js
  app/components/Icon/ImportOnboarding.js
  app/components/Icon/PlusOnboarding.js
  app/components/Icon/ZapLogoBolt.js
  app/components/Onboarding/Steps/ConnectionDetails.js
  app/components/Onboarding/Steps/ConnectionType.js
  app/components/Onboarding/Steps/ConnectionTypeItem.js
  app/components/Onboarding/Steps/SeedView.js
  app/components/Onboarding/Steps/index.js
  app/components/Onboarding/Steps/messages.js
  app/components/UI/Radio.js
  app/components/UI/Wizard.js
  app/icons/bolt-onboarding.svg
  app/icons/connect-onboarding.svg
  app/icons/import-onboarding.svg
  app/icons/plus-onboarding.svg
  app/translations/en.json
  test/e2e/pages/onboarding.js
  test/unit/components/UI/__snapshots__/Radio.spec.js.snap
Labels: scope: onboarding, scope: ui/ux, type: enhancement

#1759 fix(ui): fix connection details tabcontrol
  app/components/UI/Bar.js
  app/components/UI/Tabs.js
Labels: scope: onboarding, type: bug 🐛

#1757 fix(wallet): ensure pay form auto submits on valid address
  app/components/Pay/Pay.js
Labels: type: bug 🐛

#1756 fix(wallet): ensure tickers are ready before displaying app
  app/reducers/app.js
Labels: type: bug 🐛

#1760 fix(deps): update lnd to v0.5.1-beta-847-gc4a438e
  package.json
Labels: type: chore

#1766 chore(ux): adjust connection type tab copy
  app/components/Onboarding/Steps/messages.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: scope: ui/ux, type: chore

#1764 chore(ux): adjust processing transaction copy
  app/components/Activity/Payment/messages.js
  app/components/Activity/Transaction/messages.js
  app/translations/da-DK.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/ga-IE.json
Labels: scope: ui/ux, type: chore

#1740 chore(version): bump version to v0.4.0-beta
  app/package.json
  package.json
Labels: type: chore

#1752 feat(wallet): ability to set on-chain transaction fees
  app/components/Channels/ChannelCreateForm.js
  app/components/Channels/messages.js
  app/components/Pay/Pay.js
  app/components/Pay/constants.js
  app/components/UI/TransactionFeeInput.js
  app/components/UI/constants.js
  app/components/UI/index.js
  app/components/UI/messages.js
  app/containers/Pay.js
  app/containers/UI/CryptoSelector.js
  app/containers/UI/CryptoValue.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: scope: btcpay, scope: wallet, type: feature

#1780 feat(channels): use unconfirmed outputs in funding transaction
  app/lib/lnd/methods/channelController.js
Labels: scope: channels, type: enhancement

#1773 chore(ui): adjust wording on LndConnect tab
  app/components/Wallet/ReceiveModal/ReceiveModal.js
  app/components/Wallet/ReceiveModal/messages.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: scope: ui/ux, type: enhancement

#1772 fix(wallet): include pending channel balance in wallet balance
  app/lib/lnd/methods/index.js
  app/reducers/balance.js
  test/unit/reducers/__snapshots__/balance.spec.js.snap
  test/unit/reducers/balance.spec.js
Labels: scope: ui/ux, type: enhancement

#1782 style: fix typo in translation key
  app/components/Home/NoWallets.js
  app/components/Home/messages.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  test/unit/components/Home/__snapshots__/NoWallets.spec.js.snap
Labels: type: refactor

#1769 feat(onboarding): user selectable active network
  app/components/Onboarding/Onboarding.js
  app/components/Onboarding/Steps/Network.js
  app/components/Onboarding/Steps/index.js
  app/components/Onboarding/Steps/messages.js
  app/components/UI/Heading.js
  app/components/UI/Message.js
  app/components/UI/Text.js
  app/containers/Onboarding.js
  app/lib/lnd/neutrino.js
  app/lib/lnd/util.js
  app/reducers/lnd.js
  app/reducers/onboarding.js
  app/themes/base.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  resources/lnd.conf
  stories/_general/typography.stories.js
  test/e2e/onboarding-create.spec.js
  test/e2e/onboarding-import.spec.js
  test/e2e/pages/onboarding.js
  test/unit/components/UI/__snapshots__/Dropdown.spec.js.snap
  test/unit/components/UI/__snapshots__/Heading.spec.js.snap
  test/unit/components/UI/__snapshots__/Link.spec.js.snap
  test/unit/components/UI/__snapshots__/Message.spec.js.snap
  test/unit/components/UI/__snapshots__/Text.spec.js.snap
Labels: type: feature

#1787 fix(ui): always use preset font sizes
  app/components/Channels/ChannelCardList.js
  app/components/Channels/ChannelCreateSummary.js
  app/components/Channels/ChannelStatus.js
  app/components/Pay/PaySummaryLightning.js
  app/components/Pay/PaySummaryOnChain.js
  app/components/UI/Header.js
  app/components/UI/Heading.js
  app/components/UI/Message.js
  app/components/UI/Notification.js
  app/components/Wallet/Wallet.js
  test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
  test/unit/components/Pay/__snapshots__/PaySummaryOnchain.spec.js.snap
  test/unit/components/UI/__snapshots__/Header.spec.js.snap
  test/unit/components/UI/__snapshots__/Message.spec.js.snap
  test/unit/components/UI/__snapshots__/Notification.spec.js.snap
Labels: scope: ui/ux, type: bug 🐛

#1793 fix(wallet): include limbo balance in wallet total
  app/reducers/balance.js
  app/reducers/channels.js
Labels: scope: channels, scope: wallet, type: bug 🐛

#1794 style: lint icons after generation
  app/components/Icon/PlusOnboarding.js
  package.json
Labels: type: refactor

#1797 fix(ui): adjust language in onboarding network step
  app/components/Onboarding/Steps/Network.js
  app/components/Onboarding/Steps/messages.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  stories/containers/onboarding/onboarding.component.stories.js
Labels: scope: ui/ux, type: enhancement

#1798 fix(sync): clean up text on sync screen
  app/components/Onboarding/Steps/WalletCreate.js
  app/components/Syncing/Syncing.js
  app/components/Syncing/messages.js
  app/components/UI/Modal.js
  app/components/UI/messages.js
  app/containers/Syncing.js
  app/preload.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  stories/containers/syncing.stories.js
  stories/helpers.js
Labels: scope: ui/ux, type: enhancement

#1796 feat(wallet): set defatult currency to sats
  app/reducers/settings.js
  app/reducers/ticker.js
  config/default.js
Labels: scope: ui/ux, scope: wallet

#1805 fix(deps): update lnd to v0.5.1-beta-869-g131959ef
  package.json
Labels: type: chore

#1811 fix(lnd): enable assumechanvalid on mainnet
  app/lib/lnd/neutrino.js
Labels: type: enhancement

#1814 fix(ui): resolve inconsistency in channel forms
  app/components/Channels/ChannelCreateForm.js
  app/components/Channels/ChannelCreateHeader.js
  app/components/Channels/ChannelCreateSummary.js
  app/components/Channels/messages.js
  app/containers/Channels/ChannelCreateForm.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: scope: channels, scope: ui/ux, type: enhancement

#1818 feat(channels): include loading channels in listings
  app/components/Channels/ChannelCardListItem.js
  app/components/Channels/ChannelData.js
  app/components/Channels/ChannelSummaryListItem.js
  app/lib/lnd/methods/channelController.js
  app/lib/lnd/methods/index.js
  app/lib/lnd/push/openchannel.js
  app/reducers/channels.js
  app/reducers/ipc.js
  app/reducers/lnd.js
  app/reducers/ticker.js
  app/reducers/transaction.js
  stories/containers/channels/channel-card-list-item.stories.js
  stories/containers/channels/channel-card-list.stories.js
  stories/containers/channels/channel-summary-list.stories.js
  test/unit/reducers/__snapshots__/channels.spec.js.snap
  test/unit/reducers/channels.spec.js
Labels: scope: channels, type: enhancement

#1829 fix(ui): disable open channel button on submit
  app/components/Channels/ChannelCreateForm.js
  app/containers/Channels/ChannelCreateForm.js
Labels: type: bug 🐛

#1836 fix(deps): update lnd to v0.5.1-beta-926-g764d8525
  package.json
  yarn.lock
Labels: type: chore

#1827 fix(channels): refresh channels after LN payments
  app/reducers/invoice.js
  app/reducers/payment.js
Labels: scope: channels, type: enhancement

#1839 fix(wallet): better payment success/error handling
  app/lib/lnd/methods/index.js
  app/lib/lnd/methods/paymentsController.js
  app/lib/lnd/push/sendpayment.js
  app/reducers/activity.js
  app/reducers/payment.js
Labels: scope: wallet, type: enhancement

#1834 fix(channels): improve channel create messages
  app/components/Channels/ChannelCreateForm.js
  app/components/GlobalNotification/GlobalNotification.js
  app/containers/Channels/ChannelCreateForm.js
  app/reducers/channels.js
  app/reducers/notification.js
  package.json
  yarn.lock
Labels: scope: channels, scope: ui/ux, type: enhancement

#1841 fix(ui): change invoice status color scheme
  app/components/Request/RequestSummary.js
Labels: scope: wallet, type: enhancement

#1846 feat(ui): add opening date to channel details
  app/components/Channels/ChannelData.js
  app/components/Channels/messages.js
  app/containers/Channels/ChannelDetail.js
  app/reducers/transaction.js
  app/reducers/utils.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: scope: channels, type: enhancement

#1850 fix(ui): incorrect currency address name
  app/containers/Wallet/ReceiveModal.js
  app/reducers/ticker.js
Labels: scope: wallet, type: bug 🐛

#1849 feat(lnd): lnd crash recovery (show dialog)
  app/components/Channels/ChannelCloseDialog.js
  app/components/Dialog/DialogLndCrashed.js
  app/components/Dialog/index.js
  app/components/Dialog/messages.js
  app/components/Home/DeleteWalletDialog.js
  app/components/UI/Dialog.js
  app/containers/Dialog/DialogLndCrashed.js
  app/containers/Dialog/index.js
  app/containers/Root.js
  app/lib/zap/controller.js
  app/reducers/ipc.js
  app/reducers/lnd.js
  app/reducers/notification.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  test/unit/components/UI/__snapshots__/Dialog.spec.js.snap
Labels: scope: lnd, type: enhancement

#1854 refactor: ensure totalBalance is a Number type
  app/reducers/balance.js
  app/reducers/channels.js
  test/unit/reducers/__snapshots__/channels.spec.js.snap
Labels: type: bug 🐛, type: refactor

#1852 fix(ui): only show on-chain transaction fee widget for onchain transactions
  app/components/Pay/Pay.js
Labels: scope: wallet, type: bug 🐛

#1858 chore: bump stable version to 0.4.x
  config/default.js
Labels: type: chore

#1859 chore: bump version to 0.5.0-alpha
  app/package.json
  package.json
Labels: type: chore

#1863 fix(lnd): don't reset lnd state on hot-reload
  app/components/Dialog/DialogLndCrashed.js
Labels: scope: devops, type: bug 🐛

#1861 fix(onboarding): don't allow autopilot on mainnet
  app/components/Onboarding/Onboarding.js
Labels: scope: onboarding, type: enhancement

#1865 fix(icon): fix onboarding plus icon color prop
  app/components/Icon/PlusOnboarding.js
  app/icons/plus-onboarding.svg
Labels: scope: onboarding, type: bug 🐛

#1870 fix(lnd): improve lnd version detection
  app/lib/lnd/lightning.js
  app/lib/lnd/walletUnlocker.js
  package.json
  yarn.lock
Labels: scope: lnd, type: bug 🐛

#1868 refactor: use global config
  app/components/Home/WalletLauncher.js
  app/lib/lnd/config.js
  app/lib/lnd/methods/index.js
  app/lib/lnd/methods/invoicesController.js
  app/lib/lnd/neutrino.js
  app/lib/utils/log.js
  app/lib/zap/controller.js
  app/reducers/lnd.js
  app/reducers/onboarding.js
  app/reducers/ticker.js
  config/custom-environment-variables.json
  config/default.js
  config/production.js
  package.json
  resources/lnd.conf
  test/unit/lnd/lnd-config.spec.js
  test/unit/lnd/neutrino.spec.js
Labels: type: bug 🐛, type: refactor

#1881 feat(lnd): update lnd to v0.5.1-beta-982-gf9ba6759
  package.json
  yarn.lock
Labels: type: chore

#1876 refactor: update lnd build script
  scripts/lnd-release/.goreleaser.yml
Labels: scope: lnd, type: refactor

#1903 fix(ui): incorrect fee in pay summary
  renderer/components/Pay/Pay.js
  renderer/components/Pay/PaySummaryOnChain.js
  renderer/components/Pay/messages.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: bug 🐛

#1910 fix(wallet): filter non wallet dirs and files
  utils/localWallets.js
Labels: type: bug 🐛

#1914 fix(ui): fix incorrect next button disabled state
  renderer/components/Channels/ChannelCreateForm.js
  renderer/containers/Channels/ChannelCreateForm.js
Labels: type: bug 🐛

#1925 fix(ui): hide suggested nodes channel when empty
  renderer/components/Channels/NodeCardList.js
Labels: type: enhancement

#1927 fix(deps): update dependency react-spring to v8
  package.json
  renderer/components/Autopay/AutopayCreateForm.js
  renderer/components/Channels/ChannelCreateForm.js
  renderer/components/GlobalNotification/GlobalNotification.js
  renderer/components/LoadingBolt/LoadingBolt.js
  renderer/components/Onboarding/Steps/ConnectionTypeItem.js
  renderer/components/Pay/Pay.js
  renderer/components/UI/Wizard.js
  renderer/containers/ModalStack.js
  yarn.lock
Labels: type: refactor
