Repository LN-Zap/zap-desktop, pull requests merged in 2019-01, with the labels that each got.

#1202 fix(ui): left-align column text
  app/components/Contacts/SuggestedNodes/SuggestedNodes.js
  app/components/Contacts/SuggestedNodes/messages.js
  app/components/Settings/Fiat/Fiat.scss
  app/components/Settings/Locale/Locale.scss
  app/components/Settings/Theme/Theme.scss
  app/translations/en.json
Labels: scope: ui/ux, type: enhancement

#1211 fix(ui): add autofocus to search input field
  app/components/Activity/Activity.js
Labels: scope: ui/ux, type: enhancement

#1221 fix(ui): implement invoice status update in request modal
  app/containers/Request.js
  app/reducers/invoice.js
Labels: scope: ui/ux, type: bug

#1222 chore(version): bump version to v0.3.3-beta
  app/package.json
  package.json
Labels: scope: devops, type: chore

#1220 fix(style): ensure modal covers full page
  app/components/UI/Modal.js
  app/components/UI/Page.js
  test/unit/components/UI/__snapshots__/Modal.spec.js.snap
  test/unit/components/UI/__snapshots__/Page.spec.js.snap
Labels: scope: ui/ux, type: bug

#1229 refactor(deps): remove dependency on react-icons
  app/components/Contacts/Network/Network.js
  app/components/Contacts/SubmitChannelForm/SubmitChannelForm.js
  app/components/Icon/AngleDown.js
  app/components/Icon/AngleLeft.js
  app/components/Icon/AngleRight.js
  app/components/Icon/AngleUp.js
  app/components/Icon/Circle.js
  app/components/Icon/ExternalLink.js
  app/components/Icon/Orbit.js
  app/components/Icon/SystemArrowLeft.js
  app/components/Icon/SystemArrowRight.js
  app/components/Icon/SystemNavNext.js
  app/components/Icon/SystemNavPrevious.js
  app/components/Settings/Fiat/Fiat.js
  app/components/Settings/Locale/Locale.js
  app/components/Settings/Menu/Menu.js
  app/components/Settings/Theme/Theme.js
  app/components/UI/Dropdown.js
  app/components/UI/StatusIndicator.js
  app/components/Wallet/Wallet.js
  app/icons/angle-down.svg
  app/icons/angle-left.svg
  app/icons/angle-right.svg
  app/icons/angle-up.svg
  app/icons/circle.svg
  app/icons/external-link.svg
  app/icons/orbit.svg
  app/icons/skinny-bitcoin.svg
  app/package.json
  app/yarn.lock
  stories/components/button.stories.js
  stories/components/spinner.stories.js
  stories/icons/icon.stories.js
  test/unit/components/UI/__snapshots__/Dropdown.spec.js.snap
  test/unit/components/UI/__snapshots__/StatusIndicator.spec.js.snap
Labels: type: refactor

#1228 fix(ui): make modal scrollable
  app/components/UI/Modal.js
  test/unit/components/UI/__snapshots__/Modal.spec.js.snap
Labels: scope: ui/ux, type: bug

#1232 refactor(styles): remove scss from Wallet components
  app/components/Wallet/Wallet.js
  app/components/Wallet/Wallet.scss
Labels: scope: wallet, type: refactor

#1233 refactor(styles): remove scss from ReceiveModal components
  app/components/Wallet/ReceiveModal/ReceiveModal.js
  app/components/Wallet/ReceiveModal/ReceiveModal.scss
Labels: scope: wallet, type: refactor

#1234 refactor(styles): remove scss from LoadingBolt component
  app/components/LoadingBolt/LoadingBolt.js
  app/components/LoadingBolt/LoadingBolt.scss
  app/components/UI/MainContent.js
  stories/components/loadingbolt.stories.js
  test/unit/components/LoadingBolt.spec.js
  test/unit/components/UI/__snapshots__/MainContent.spec.js.snap
Labels: scope: wallet, type: refactor

#1236 refactor(styles): remove scss from Settings components
  app/components/Settings/Fiat/Fiat.js
  app/components/Settings/Fiat/Fiat.scss
  app/components/Settings/Locale/Locale.js
  app/components/Settings/Locale/Locale.scss
  app/components/Settings/Menu/Menu.js
  app/components/Settings/Menu/Menu.scss
  app/components/Settings/Settings.js
  app/components/Settings/Settings.scss
  app/components/Settings/Theme/Theme.js
  app/components/Settings/Theme/Theme.scss
  app/components/UI/Dropdown.js
  app/components/Wallet/Wallet.js
  app/containers/Activity.js
Labels: scope: wallet, type: refactor

#1235 fix(startup-fetch-activity): fetch activity history when grpc is ready Fix #1193
  app/components/Activity/Activity.js
  app/components/Contacts/Network/Network.js
  app/reducers/activity.js
  app/reducers/lnd.js
Labels: scope: wallet, type: bug

#1196 fix(security): disable electron node integration
  .eslintignore
  .flowconfig
  .gitignore
  .prettierignore
  .vscode/settings.json
  app/empty.html
  app/lib/utils/api.js
  app/lib/zap/controller.js
  app/main.js
  app/package.json
  app/preload.js
  app/reducers/address.js
  app/reducers/balance.js
  app/reducers/channels.js
  app/reducers/info.js
  app/reducers/invoice.js
  app/reducers/lnd.js
  app/reducers/locale.js
  app/reducers/network.js
  app/reducers/onboarding.js
  app/reducers/pay.js
  app/reducers/payment.js
  app/reducers/peers.js
  app/reducers/transaction.js
  app/yarn.lock
  internals/scripts/CheckBuiltsExist.js
  internals/webpack/webpack.config.base.js
  internals/webpack/webpack.config.main.prod.js
  internals/webpack/webpack.config.renderer.dev.dll.js
  internals/webpack/webpack.config.renderer.dev.js
  internals/webpack/webpack.config.renderer.prod.js
  package.json
  test/e2e/e2e.spec.js
  yarn.lock
Labels: scope: security, type: enhancement

#1243 perf(activity): use purecomponent for activity list item and extract it
  app/components/Activity/Activity.js
  app/components/Activity/ActivityListItem.js
Labels: scope: performance, type: enhancement

#1250 Fix settings menu glitchs
  app/components/Settings/Fiat/Fiat.js
  app/components/Settings/Locale/Locale.js
  app/components/Settings/Menu/Menu.js
  app/components/Settings/Settings.js
  app/components/Settings/Theme/Theme.js
  app/components/UI/Dropdown.js
  app/components/Wallet/Wallet.js
  app/containers/Activity.js
  app/containers/Settings.js
  app/reducers/settings.js
  test/unit/reducers/__snapshots__/settings.spec.js.snap
  test/unit/reducers/settings.spec.js
Labels: scope: ui/ux, type: bug

#1255 fix(ui): ensure main content area is scrollable
  app/components/UI/MainContent.js
  test/unit/components/UI/__snapshots__/MainContent.spec.js.snap
Labels: scope: ui/ux, type: bug

#1239 refactor(styles): remove scss from Contact components
  app/components/Contacts/AddChannel/AddChannel.js
  app/components/Contacts/ChannelForm/ChannelForm.js
  app/components/Contacts/ChannelForm/ChannelForm.scss
  app/components/Contacts/ConnectManually/ConnectManually.js
  app/components/Contacts/ConnectManually/ConnectManually.scss
  app/components/Contacts/ConnectManually/messages.js
  app/components/Contacts/SubmitChannelForm/SubmitChannelForm.js
  app/components/Contacts/SubmitChannelForm/SubmitChannelForm.scss
  app/components/Contacts/SubmitChannelForm/messages.js
  app/components/Pay/Pay.js
  app/components/UI/CurrencyFieldGroup.js
  app/components/UI/index.js
  app/components/UI/messages.js
  app/containers/App.js
  app/containers/Contacts/ConnectManually.js
  app/containers/Contacts/SubmitChannelForm.js
  app/reducers/channels.js
  app/reducers/contactsform.js
  stories/containers/contacts.stories.js
Labels: scope: wallet, type: refactor

#1261 fix(onboarding): handle host/cert errors on boot
  app/components/GlobalError/GlobalError.js
  app/components/Home/Home.js
  app/components/Home/WalletLauncher.js
  app/components/Onboarding/Steps/ConnectionConfirm.js
  app/components/Onboarding/Steps/ConnectionDetails.js
  app/containers/Home.js
  app/containers/Initializer.js
  app/containers/Onboarding.js
  app/containers/Root.js
  app/lib/zap/controller.js
  app/reducers/lnd.js
  stories/containers/home.stories.js
Labels: scope: onboarding, type: bug

#1274 fix(wallet): handle invoices with msat amounts
  app/components/Pay/Pay.js
  app/components/Pay/PaySummaryLightning.js
  app/components/UI/Value.js
  app/containers/Pay.js
  app/lib/utils/btc.js
  app/reducers/payment.js
  stories/containers/pay.stories.js
  stories/helpers.js
Labels: scope: wallet, type: bug

#1275 fix(wallet): support uppercase payment requests
  .eslintignore
  .prettierignore
  app/lib/utils/bech32.js
  app/lib/utils/crypto.js
  app/lib/utils/index.js
  app/reducers/network.js
  package.json
  yarn.lock
Labels: scope: wallet, type: bug

#1276 fix(i18n): ensure modal help link is translatable
  app/components/Onboarding/Steps/messages.js
  app/components/UI/Modal.js
  app/components/UI/messages.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: scope: ui/ux, type: bug

#1264 refactor(props): do not pass lndConnect to DOM
  app/components/Onboarding/Steps/ConnectionDetails.js
Labels: scope: onboarding, type: bug

#1256 build(webpack): remove css module support
  .flowconfig
  .lintstagedrc
  .stylelintrc
  app/components/App/App.js
  app/containers/App.js
  app/index.js
  app/styles/.stylelintrc
  app/styles/app.global.scss
  app/styles/variables.scss
  internals/webpack/webpack.config.renderer.dev.dll.js
  internals/webpack/webpack.config.renderer.dev.js
  internals/webpack/webpack.config.renderer.prod.js
  package.json
  yarn.lock
Labels: scope: devops, type: chore

#1278 chore(config): remove duplicate code
  app/lib/lnd/config.js
Labels: type: chore

#1268 refactor(reducer): remove unused arg
  app/reducers/wallet.js
Labels: type: refactor

#1267 style(jsx): add missing curly brace
  app/components/Request/RequestSummary.js
Labels: type: refactor

#1281 fix(ui): increase qrcode size for easier scanning
  app/components/Request/RequestSummary.js
  app/components/Request/messages.js
  app/components/Syncing/Syncing.js
  app/components/UI/QRCode.js
  app/components/Wallet/ReceiveModal/ReceiveModal.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  stories/components/qrcode.stories.js
  stories/containers/pay.stories.js
  stories/containers/request.stories.js
  test/unit/components/UI/QRCode.spec.js
  test/unit/components/UI/__snapshots__/QRCode.spec.js.snap
Labels: scope: ui/ux, type: enhancement

#1280 fix(ui): ensure error messages are visible
  app/components/GlobalError/GlobalError.js
  app/components/Home/WalletLauncher.js
  app/components/UI/Notification.js
  app/containers/Root.js
  app/reducers/error.js
Labels: scope: ui/ux, type: bug

#1277 chore(i18n): update translation files
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: type: chore

#1283 refactor(icons): remove namespace from orbit icon
  app/components/Icon/Orbit.js
  app/icons/orbit.svg
Labels: type: chore

#1305 perf(app): remove irrelevant to render state vars
  app/components/App/App.js
Labels: scope: performance, scope: wallet

#1302 fix(onboarding): handle btcpayserver connection issues
  app/components/Onboarding/Steps/BtcPayServer.js
  app/components/Onboarding/Steps/ConnectionConfirm.js
  app/components/UI/TextArea.js
  test/unit/components/UI/__snapshots__/LightningInvoiceInput.spec.js.snap
Labels: scope: btcpay, scope: onboarding, type: bug

#1301 fix(onboarding): better categorize macaroon error
  app/lib/zap/controller.js
Labels: scope: onboarding, type: bug

#1298 chore(deps): remove unused dependency chalk
  package.json
Labels: type: chore

#1308 test(unit): clean up some warning messages
  app/components/UI/Select.js
  test/unit/components/UI/Countdown.spec.js
  test/unit/components/UI/LightningInvoiceInput.spec.js
Labels: scope: tests

#1312 refactor(ui): introduce dialog component
  app/components/UI/Dialog.js
  app/components/UI/index.js
  stories/components/dialog.stories.js
  test/unit/components/UI/Dialog.spec.js
  test/unit/components/UI/__snapshots__/Dialog.spec.js.snap
Labels: scope: ui/ux, type: enhancement

#1293 fix(payment): timeout payment requests after 60 seconds
  app/components/Activity/Payment/Payment.js
  app/components/UI/Message.js
  app/lib/lnd/methods/index.js
  app/lib/lnd/methods/paymentsController.js
  app/lib/utils/promiseTimeout.js
  test/unit/components/UI/__snapshots__/Message.spec.js.snap
Labels: scope: wallet, type: bug

#1299 perf(boot): load files asynchronously
  app/lib/lnd/lightning.js
  app/lib/lnd/util.js
  app/lib/lnd/walletUnlocker.js
Labels: scope: performance, type: enhancement

#1314 chore(i18n): re extract language strings
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: type: chore

#1323 fix(btc): use correct parameter when converting from millisats to fiat
  app/lib/utils/btc.js
Labels: type: bug

#1324 chore(deps): update bolt11 dependency to v1.2.2
  package.json
  yarn.lock
Labels: type: chore

#1330 fix(ui): loading screen flicker on wallet start
  app/containers/Root.js
Labels: scope: ui/ux, type: bug

#1329 fix(ui): ensure menu can overflow main content
  app/components/Home/Home.js
  app/components/UI/GlobalStyle.js
  app/components/UI/MainContent.js
  test/unit/components/UI/__snapshots__/MainContent.spec.js.snap
Labels: scope: ui/ux, type: bug

#1340 Reconfigure Renovate
  renovate.json
Labels: scope: devops, type: chore

#1325 refactor(ui): introduce actionbar component
  app/components/UI/ActionBar.js
  app/components/UI/index.js
  stories/components/actionbar.stories.js
  test/unit/components/UI/ActionBar.spec.js
  test/unit/components/UI/__snapshots__/ActionBar.spec.js.snap
Labels: type: refactor

#1341 refactor(ui): add danger button variant
  app/themes/dark.js
  app/themes/light.js
  stories/components/button.stories.js
  test/unit/components/UI/__snapshots__/QRCode.spec.js.snap
Labels: type: refactor

#1338 refactor(onboarding): remove unused preSubmit hook
  app/components/Onboarding/Steps/Alias.js
  app/components/Onboarding/Steps/Autopilot.js
  app/components/Onboarding/Steps/BtcPayServer.js
  app/components/Onboarding/Steps/ConnectionConfirm.js
  app/components/Onboarding/Steps/ConnectionDetails.js
  app/components/Onboarding/Steps/ConnectionType.js
  app/components/Onboarding/Steps/Login.js
  app/components/Onboarding/Steps/Name.js
  app/components/Onboarding/Steps/Password.js
  app/components/Onboarding/Steps/Recover.js
  app/components/Onboarding/Steps/SeedConfirm.js
  app/components/Onboarding/Steps/SeedView.js
  app/components/Onboarding/Steps/WalletCreate.js
  app/components/Onboarding/Steps/WalletRecover.js
  app/components/UI/Wizard.js
Labels: type: refactor

#1350 fix(i18n): add intl support for activity header
  app/components/Activity/Activity.js
Labels: type: bug

#1349 refactor(lib): apply notification.onClick properly
  app/lib/utils/notifications.js
Labels: type: bug, type: refactor

#1347 fix(wallet): phots to ltc conversion
  app/lib/utils/btc.js
Labels: type: bug

#1337 fix(wallet): satoshi to millisatoshi conversion
  app/lib/utils/btc.js
Labels: scope: wallet, type: bug

#1353 refactor(ui): add customizability to dialog component
  app/components/UI/Dialog.js
  stories/components/dialog.stories.js
  test/unit/components/UI/Dialog.spec.js
  test/unit/components/UI/__snapshots__/Dialog.spec.js.snap
Labels: type: refactor

#1343 refactor(libs): extract and reuse delay utility method
  app/components/Activity/Activity.js
  app/components/App/App.js
  app/lib/utils/delay.js
  app/lib/zap/controller.js
  app/lib/zap/updater.js
  app/reducers/error.js
  app/reducers/payment.js
  app/reducers/transaction.js
  stories/containers/home.stories.js
  stories/containers/onboarding.stories.js
  stories/containers/pay.stories.js
  stories/containers/request.stories.js
Labels: type: refactor

#1373 fix(btc): correct conversion from msat and mlits to fiat
  app/lib/utils/btc.js
Labels: type: bug

#1342 refactor(ui): introduce checkbox component
  app/components/UI/Checkbox.js
  app/components/UI/index.js
  stories/forms/form.stories.js
  test/unit/components/UI/Checkbox.spec.js
  test/unit/components/UI/__snapshots__/Checkbox.spec.js.snap
Labels: type: refactor

#1374 fix(btc): make sure non-round fiat conversion results are handled well
  app/lib/utils/btc.js
  test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
  test/unit/components/Pay/__snapshots__/PaySummaryOnchain.spec.js.snap
Labels: type: bug

#1370 refactor(ui): extract Tabs component
  app/components/Activity/Activity.js
  app/components/UI/Tabs.js
  app/components/UI/index.js
  app/reducers/activity.js
  app/reducers/payment.js
  app/reducers/transaction.js
  stories/components/tabs.stories.js
  test/unit/reducers/__snapshots__/activity.spec.js.snap
Labels: scope: wallet, type: refactor

#1319 refactor(lnd): promisify lnd calls
  app/lib/lnd/methods/channelController.js
  app/lib/lnd/methods/invoicesController.js
  app/lib/lnd/methods/networkController.js
  app/lib/lnd/methods/paymentsController.js
  app/lib/lnd/methods/peersController.js
  app/lib/lnd/methods/walletController.js
  app/lib/utils/index.js
  app/lib/utils/promisifiedCall.js
Labels: type: refactor

#1295 Add e2e tests for onboarding process
  .eslintrc.js
  .gitattributes
  .testcafe-electron-rc
  .travis.yml
  app/components/Onboarding/Steps/Recover.js
  app/components/Onboarding/Steps/SeedView.js
  app/components/UI/Input.js
  app/components/UI/Wizard.js
  app/containers/Initializer.js
  app/index.js
  app/lib/zap/controller.js
  app/main.js
  app/preload.js
  app/reducers/app.js
  app/reducers/error.js
  app/reducers/ipc.js
  app/reducers/lnd.js
  app/store/db.js
  appveyor.yml
  internals/webpack/webpack.config.renderer.dev.js
  internals/webpack/webpack.config.renderer.e2e.js
  internals/webpack/webpack.config.renderer.prod.js
  package.json
  test/e2e/app.spec.js
  test/e2e/e2e.spec.js
  test/e2e/fixtures/readonly.macaroon
  test/e2e/fixtures/tls.cert
  test/e2e/onboarding-btcpay.spec.js
  test/e2e/onboarding-connect.spec.js
  test/e2e/onboarding-create.spec.js
  test/e2e/onboarding-import.spec.js
  test/e2e/pages/loading.js
  test/e2e/pages/onboarding.js
  test/e2e/pages/syncing.js
  test/e2e/pages/wallet.js
  test/e2e/utils/helpers.js
  test/unit/__helpers__/setup.js
  yarn.lock
Labels: scope: onboarding, scope: tests

#1376 docs(contributing): branches and pull requests
  CONTRIBUTING.md
Labels: scope: documentation

#1378 fix(ui): highlight border of selected inputs
  app/components/UI/Input.js
  app/components/UI/TextArea.js
  app/components/withRequiredValidation/index.js
  app/components/withRequiredValidation/withRequiredValidation.js
  stories/forms/form.stories.js
  test/unit/components/UI/__snapshots__/Input.spec.js.snap
  test/unit/components/UI/__snapshots__/LightningInvoiceInput.spec.js.snap
  test/unit/components/UI/__snapshots__/Select.spec.js.snap
  test/unit/components/UI/__snapshots__/TextArea.spec.js.snap
Labels: scope: ui/ux, type: bug

#1300 feat(ui): add ability to select macaroon and cert file from dialog
  app/components/Icon/FolderOpen.js
  app/components/Onboarding/Steps/ConnectionDetails.js
  app/components/UI/Button.js
  app/components/UI/Input.js
  app/components/UI/OpenDialogButton.js
  app/components/UI/OpenDialogInput.js
  app/components/UI/index.js
  app/components/withOpenDialog/index.js
  app/components/withOpenDialog/withOpenDialog.js
  app/icons/folder-open.svg
  app/preload.js
Labels: scope: onboarding, status: needs rebase, type: feature

#1398 fix(btc): use rounding in fiat conversions
  app/lib/utils/btc.js
  test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
  test/unit/components/Pay/__snapshots__/PaySummaryOnchain.spec.js.snap
Labels: type: bug

#1396 test(btc): add unit tests for btc.js
  test/unit/utils/btc.spec.js
Labels: scope: tests, type: enhancement

#1403 refactor(lint): fix lint warnings
  app/components/UI/Input.js
  app/components/UI/TextArea.js
  app/containers/Activity.js
  app/lib/lnd/methods/index.js
Labels: type: refactor

#1390 perf(ui): only update node data when changed
  app/components/App/App.js
  app/reducers/channels.js
  app/reducers/network.js
Labels: scope: performance, scope: ui/ux

#1406 ci(node): do not build and test on node LTS
  .travis.yml
  appveyor.yml
Labels: scope: devops

#1399 refactor(request): use correct prop type for invoice
  app/components/Request/Request.js
Labels: type: bug

#1393 refactor(ui): decompose network jsx into components
  app/components/Contacts/Network/BrowseChannelButton.js
  app/components/Contacts/Network/ChannelDetails.js
  app/components/Contacts/Network/ChannelItem.js
  app/components/Contacts/Network/ChannelLimits.js
  app/components/Contacts/Network/ChannelPubkey.js
  app/components/Contacts/Network/CloseChannel.js
  app/components/Contacts/Network/ClosingChannel.js
  app/components/Contacts/Network/Header.js
  app/components/Contacts/Network/LoadingChannels.js
  app/components/Contacts/Network/Network.js
  app/components/Contacts/Network/NetworkActionBar.js
  app/components/Contacts/Network/NetworkBalance.js
  app/components/Contacts/Network/SearchBar.js
  app/components/Contacts/Network/Ticker.js
  app/components/Contacts/Network/index.js
Labels: type: refactor

#1410 refactor(main): run app in development mode by default
  app/main.js
  internals/webpack/webpack.config.main.prod.js
Labels: scope: devops

#1391 perf(ui): reduce wallet & activity re-renders
  app/components/Activity/Activity.js
  app/components/Activity/ActivityListItem.js
  app/components/App/App.js
  app/components/Contacts/Network/Network.js
  app/components/Wallet/Wallet.js
  app/containers/Activity.js
  app/containers/Activity/InvoiceContainer.js
  app/containers/Activity/PaymentContainer.js
  app/containers/Activity/TransactionContainer.js
  app/containers/App.js
  app/containers/Wallet.js
  app/reducers/balance.js
Labels: scope: performance, scope: ui/ux

#1392 perf(ui): reduce network pane re-renders
  app/components/Contacts/Network/Network.js
  app/containers/App.js
  app/containers/Contacts/SuggestedNodes.js
  app/reducers/contactsform.js
Labels: scope: performance, scope: ui/ux

#1317 fix(ui): implement themed delete wallet dialog
  app/components/Home/DeleteWalletDialog.js
  app/components/Home/WalletLauncher.js
  app/components/Home/index.js
  app/components/Home/messages.js
  app/components/Icon/Delete.js
  app/containers/Home.js
  app/containers/Home/DeleteWalletDialog.js
  app/icons/delete.svg
  app/preload.js
  app/reducers/wallet.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  test/e2e/utils/helpers.js
  test/unit/components/UI/Dialog.spec.js
  test/unit/components/UI/__snapshots__/Dialog.spec.js.snap
Labels: scope: onboarding, scope: ui/ux, type: enhancement

#1411 fix(ui): ensure copy/paste works in amount fields
  app/components/Request/Request.js
  app/components/UI/AmountInput.js
  app/components/UI/CryptoAmountInput.js
  app/components/UI/FiatAmountInput.js
  app/components/UI/index.js
  test/unit/components/UI/AmountInput.spec.js
Labels: type: bug

#1421 fix(launcher): ensure wallet close on laucnhpad mount
  app/components/Home/Home.js
  app/containers/Home.js
Labels: scope: ui/ux, type: bug

#1424 refactor(cb): add description field to checkbox
  app/components/UI/Checkbox.js
  stories/forms/form.stories.js
  test/unit/components/UI/Checkbox.spec.js
  test/unit/components/UI/__snapshots__/Checkbox.spec.js.snap
Labels: type: refactor

#1402 fix(wallet): handle lndconnect links when app closed (mac)
  app/components/Pay/Pay.js
  app/containers/Initializer.js
  app/containers/Pay.js
  app/lib/zap/controller.js
  app/main.js
  app/reducers/pay.js
Labels: scope: wallet, type: bug

#1429 fix(wallet): handle protocol links when app closed (linux/windows)
  app/main.js
  package.json
Labels: scope: linux, scope: windows, type: bug

#1422 fix(launcher): do not double notify startup errors
  app/components/Home/WalletLauncher.js
  app/components/Onboarding/Onboarding.js
  app/components/Onboarding/Steps/ConnectionDetails.js
  app/containers/Onboarding.js
  app/lib/zap/controller.js
Labels: type: bug

#1432 refactor(ui): add new Card component
  app/components/UI/Card.js
  app/components/UI/index.js
  stories/components/card.stories.js
  test/unit/components/UI/Card.spec.js
  test/unit/components/UI/__snapshots__/Card.spec.js.snap
Labels: scope: channels, scope: ui/ux, type: refactor

#1433 refactor(ui): add new ProgressBar component
  app/components/UI/ProgressBar.js
  app/components/UI/index.js
  app/themes/base.js
  app/themes/dark.js
  app/themes/light.js
  package.json
  stories/components/progressbar.stories.js
  test/unit/components/UI/ProgressBar.spec.js
  test/unit/components/UI/__snapshots__/ProgressBar.spec.js.snap
  test/unit/components/UI/__snapshots__/QRCode.spec.js.snap
  yarn.lock
Labels: scope: channels, scope: ui/ux, type: refactor

#1434 refactor(ui): add new ChannelCapacity component
  app/components/Channels/ChannelCapacity.js
  app/components/Channels/messages.js
  app/components/Icon/FolderOpen.js
  app/components/Icon/ZapSolid.js
  app/components/UI/ProgressBar.js
  app/components/UI/Value.js
  app/icons/zap-solid.svg
  stories/containers/channels/channel-capacity.stories.js
Labels: scope: channels, scope: ui/ux, type: refactor

#1438 fix(ui): fix issue with node duplicates after update
  app/reducers/network.js
Labels: type: bug

#1430 fix(ui): add internal notification when copying payment request
  app/components/Activity/InvoiceModal/InvoiceModal.js
  app/components/GlobalError/index.js
  app/components/GlobalNotification/GlobalNotification.js
  app/components/GlobalNotification/index.js
  app/components/Home/Home.js
  app/components/Home/WalletLauncher.js
  app/components/Home/WalletUnlocker.js
  app/components/Request/Request.js
  app/components/Request/RequestSummary.js
  app/components/Syncing/Syncing.js
  app/components/Wallet/ReceiveModal/ReceiveModal.js
  app/containers/Activity/InvoiceModalContainer.js
  app/containers/App.js
  app/containers/Home.js
  app/containers/Request.js
  app/containers/Root.js
  app/containers/Syncing.js
  app/lib/utils/delay.js
  app/lib/utils/notifications.js
  app/reducers/channels.js
  app/reducers/error.js
  app/reducers/index.js
  app/reducers/invoice.js
  app/reducers/ipc.js
  app/reducers/lnd.js
  app/reducers/network.js
  app/reducers/notification.js
  app/reducers/peers.js
  app/reducers/transaction.js
  app/reducers/wallet.js
  stories/containers/home.stories.js
Labels: scope: ui/ux, type: bug, type: enhancement

#1436 refactor(ui): add new ChannelStatus component
  app/components/Channels/ChannelStatus.js
  app/components/Channels/index.js
  app/components/Channels/messages.js
  app/components/Contacts/Network/ChannelItem.js
  app/components/Contacts/Network/LoadingChannels.js
  app/components/Icon/Circle.js
  app/components/UI/Spinner.js
  app/components/UI/StatusIndicator.js
  stories/containers/channels/channel-capacity.stories.js
  stories/containers/channels/channel-status.stories.js
  test/unit/components/UI/__snapshots__/Spinner.spec.js.snap
  test/unit/components/UI/__snapshots__/StatusIndicator.spec.js.snap
Labels: scope: channels, scope: ui/ux, type: refactor

#1450 perf(activity): optimize activity list rendering
  app/components/Activity/Activity.js
  app/components/Activity/ActivityListItem.js
  app/reducers/activity.js
  package.json
  yarn.lock
Labels: scope: performance, scope: ui/ux, scope: wallet

#1447 refactor(ui): add new ChannelSummaryList component
  app/components/Channels/ChannelCapacity.js
  app/components/Channels/ChannelSummaryList.js
  app/components/Channels/ChannelSummaryListItem.js
  app/components/Channels/index.js
  app/components/UI/Heading.js
  app/components/UI/Text.js
  stories/containers/channels/channel-summary-list.stories.js
  test/unit/components/UI/__snapshots__/Checkbox.spec.js.snap
Labels: scope: channels, scope: ui/ux, type: refactor

#1313 feat(wallet): generate and display lndconnect qrcodes
  app/components/Contacts/AddChannel/AddChannel.js
  app/components/UI/QRCode.js
  app/components/Util/WalletName.js
  app/components/Wallet/ReceiveModal/ReceiveModal.js
  app/components/Wallet/ReceiveModal/messages.js
  app/containers/App.js
  app/lib/lnd/config.js
  app/lib/zap/controller.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  internals/webpack/webpack.config.renderer.dev.dll.js
  package.json
  stories/components/qrcode.stories.js
  test/unit/components/UI/__snapshots__/QRCode.spec.js.snap
  yarn.lock
Labels: scope: onboarding, type: feature

#1455 fix(wallet): prevent crash on currency conversions
  app/components/Pay/Pay.js
  app/components/UI/Value.js
  test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
  test/unit/components/Pay/__snapshots__/PaySummaryOnchain.spec.js.snap
  yarn.lock
Labels: type: bug, type: enhancement

#1457 refactor(ui): use current colour for FolderOpen svg
  app/components/Icon/Circle.js
  app/components/Icon/FolderOpen.js
  app/icons/folder-open.svg
Labels: scope: ui/ux, type: enhancement, type: refactor
