Repository LN-Zap/zap-desktop, pull requests merged in 2019-04, with the labels that each got.

#1923 fix(electron): exit fullscreen before closing
  electron/main.js
Labels: type: bug 🐛

#1915 refactor: remove unused code in channels reducer
  renderer/reducers/channels.js
  test/unit/reducers/__snapshots__/channels.spec.js.snap
  test/unit/reducers/channels.spec.js
Labels: type: refactor

#1913 fix(autopay): use horizontal scroll in active autopays list
  renderer/components/Autopay/Autopay.js
  renderer/components/Autopay/AutopayList.js
  renderer/hooks/index.js
  renderer/hooks/useScrollDrag.js
Labels: scope: autopay, type: enhancement

#1939 build(electron): exclude node modules from production app
  electron/about/index.js
  electron/menuBuilder.js
  webpack/webpack.config.renderer.prod.js
Labels: type: chore

#1940 fix(migrate): properly migrate btcpayserver configs
  renderer/store/db.js
Labels: type: bug 🐛

#1904 feat(autopay): add ability to edit autopay entries
  renderer/components/Autopay/AutopayCreateForm.js
  renderer/components/Autopay/AutopayCreateModal.js
  renderer/components/Autopay/AutopayCreateSettings.js
  renderer/components/Autopay/AutopayLimitBadge.js
  renderer/components/Autopay/AutopayStatus.js
  renderer/components/Autopay/messages.js
  renderer/containers/Autopay/AutopayCreateModal.js
  renderer/containers/Autopay/AutopayList.js
  renderer/reducers/autopay.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: autopay, type: feature

#1943 feat(wallet): add wallet menu quick links
  renderer/components/Settings/Menu/Menu.js
  renderer/components/Settings/Menu/messages.js
  renderer/components/Settings/Settings.js
  renderer/components/Wallet/Wallet.js
  renderer/components/Wallet/WalletBalance.js
  renderer/components/Wallet/WalletButtons.js
  renderer/components/Wallet/WalletLogo.js
  renderer/components/Wallet/WalletMenu.js
  renderer/components/Wallet/messages.js
  renderer/containers/Settings.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: ui/ux, scope: wallet, type: feature

#1951 refactor: remove flow support
  .eslintignore
  .eslintrc.js
  .flowconfig
  .gitignore
  .travis.yml
  .vscode/settings.json
  appveyor.yml
  babel.config.js
  electron/controller.js
  electron/menuBuilder.js
  flow-typed/module_vx.x.x.js
  flow/WebpackAsset.js.flow
  lnd/config.js
  lnd/lightning.js
  lnd/neutrino.js
  lnd/walletUnlocker.js
  package.json
  renderer/store/configureStore.js
  test/unit/lnd/lnd-config.spec.js
  test/unit/lnd/neutrino.spec.js
  test/unit/reducers/channels.spec.js
  test/unit/reducers/invoice.spec.js
  test/unit/reducers/payment.spec.js
  test/unit/reducers/ticker.spec.js
  yarn.lock
Labels: type: refactor

#1947 fix: retry paying invoice after failure
  config/default.js
  renderer/components/Pay/Pay.js
  renderer/reducers/payment.js
Labels: type: bug 🐛, type: enhancement

#1952 feat(wallet): ability to sweep on-chain balance
  lnd/methods/walletController.js
  renderer/components/Pay/Pay.js
  renderer/components/Pay/PaySummaryOnChain.js
  renderer/components/Pay/messages.js
  renderer/containers/Pay.js
  renderer/reducers/transaction.js
  test/unit/components/Pay/__snapshots__/PaySummaryOnchain.spec.js.snap
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: wallet, type: feature

#1950 feat(wallet): add channels menu dropdown
  renderer/components/Channels/ChannelsMenu/ChannelsMenu.js
  renderer/components/Channels/ChannelsMenu/ChannelsMenuHeader.js
  renderer/components/Channels/ChannelsMenu/ChannelsMenuItem.js
  renderer/components/Channels/ChannelsMenu/ChannelsMenuSummary.js
  renderer/components/Channels/ChannelsMenu/index.js
  renderer/components/Channels/ChannelsMenu/messages.js
  renderer/components/UI/Donut.js
  renderer/components/UI/index.js
  renderer/components/Wallet/WalletMenu.js
  renderer/containers/Channels/ChannelsMenu.js
  renderer/hooks/index.js
  renderer/hooks/useOnClickOutside.js
  renderer/reducers/balance.js
  renderer/reducers/channels.js
  stories/Provider.js
  stories/components/donut.stories.js
  stories/containers/channels/channels-menu.stories.js
  test/unit/reducers/__snapshots__/balance.spec.js.snap
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: channels, scope: ui/ux, scope: wallet, type: feature

#1967 fix(wallet): refetch fiat tickers when forms open
  renderer/components/Channels/ChannelCreateForm.js
  renderer/components/Pay/Pay.js
  renderer/components/Request/Request.js
  renderer/containers/Channels/ChannelCreateForm.js
  renderer/containers/Pay.js
  renderer/containers/Request.js
Labels: scope: wallet, type: bug 🐛

#1974 perf: do not store network edges in state
  renderer/reducers/network.js
  renderer/store/configureStore.dev.js
Labels: scope: performance

#1982 fix(readme): update screenshot of app
  README.md
Labels: scope: documentation

#1985 refactor(devops): add redux actions user timing
  renderer/store/configureStore.dev.js
Labels: scope: devops

#1934 refactor: migrate to informed v2
  package.json
  renderer/components/Home/AutopilotAllocation.js
  renderer/components/Home/WalletLauncher.js
  renderer/components/Home/WalletSettingsFormLocal.js
  renderer/components/Onboarding/Steps/ConnectionDetailsManual.js
  renderer/components/Onboarding/Steps/Recover.js
  renderer/components/Onboarding/Steps/SeedConfirm.js
  renderer/components/UI/Checkbox.js
  renderer/components/UI/CryptoAmountInput.js
  renderer/components/UI/FiatAmountInput.js
  renderer/components/UI/Form.js
  renderer/components/UI/Input.js
  renderer/components/UI/LightningInvoiceInput.js
  renderer/components/UI/LndConnectionStringEditor.js
  renderer/components/UI/NodePubkeyInput.js
  renderer/components/UI/OpenDialogInput.js
  renderer/components/UI/PasswordInput.js
  renderer/components/UI/Range.js
  renderer/components/UI/Select.js
  renderer/components/UI/Tab.js
  renderer/components/UI/TextArea.js
  renderer/components/UI/Toggle.js
  renderer/components/UI/index.js
  renderer/hocs/withRequiredValidation.js
  renderer/reducers/onboarding.js
  test/e2e/pages/onboarding.js
  test/unit/components/UI/__snapshots__/LightningInvoiceInput.spec.js.snap
  test/unit/components/UI/__snapshots__/Radio.spec.js.snap
  utils/validateHost.js
  yarn.lock
Labels: type: refactor

#1988 fix(wallet): fix bech32 address validation
  package.json
  test/unit/reducers/__snapshots__/info.spec.js.snap
  yarn.lock
Labels: type: bug 🐛, type: enhancement

#1992 fix: prevent state update during render
  renderer/components/Onboarding/Onboarding.js
  renderer/components/Onboarding/Steps/Network.js
  renderer/components/UI/CryptoAmountInput.js
  renderer/components/UI/OpenDialogInput.js
Labels: type: refactor

#2001 fix(onboarding): typo in wallet unlocker
  renderer/components/Onboarding/Steps/messages.js
  translations/en.json
Labels: scope: onboarding, scope: ui/ux, type: bug 🐛

#2002 fix(settings): edit wallet connection details
  renderer/components/Home/WalletLauncher.js
Labels: type: bug 🐛

#2003 fix(launchpad): fallback wallet name incase host unknown
  renderer/components/Util/WalletName.js
Labels: scope: onboarding, type: bug 🐛

#2000 fix(lndconnect): support old style lndconnect links
  package.json
  renderer/components/Onboarding/Steps/ConnectionConfirm.js
  yarn.lock
Labels: type: bug 🐛

#2033 chore(hooks): add exhaustive deps check rule
  .eslintrc.js
Labels: scope: devops

#2039 refactor(hooks): fix potential issues with hooks
  renderer/components/App/App.js
  renderer/components/Pay/Pay.js
  renderer/components/UI/ActionButton.js
  renderer/containers/Logout.js
  renderer/hooks/useCloseOnUnmount.js
  renderer/hooks/useScrollDrag.js
Labels: type: refactor

#2032 fix(ui): potential syncing screen crash
  renderer/components/Syncing/Syncing.js
  renderer/hooks/index.js
  renderer/hooks/useTimeout.js
Labels: type: bug 🐛, type: refactor

#2043 fix(ui): fix input and textarea focus issue
  renderer/components/UI/Input.js
  renderer/components/UI/TextArea.js
Labels: type: bug 🐛

#2042 refactor: resolve circular dependencies
  package.json
  renderer/components/LoadingBolt/LoadingBolt.js
  renderer/reducers/balance.js
  webpack/dev/common/plugins.js
  yarn.lock
Labels: type: bug 🐛, type: refactor

#2045 fix(wallet): mainnet autopilot when recovering a wallet
  renderer/components/Onboarding/Onboarding.js
  renderer/components/Onboarding/Steps/WalletRecover.js
Labels: scope: onboarding, type: bug 🐛

#2011 fix(channels): prevent crash when closing a channel
  renderer/components/App/App.js
  renderer/components/Channels/ChannelDetail.js
  renderer/containers/Channels/ChannelDetailModal.js
  renderer/containers/ModalStack.js
  renderer/reducers/modal.js
  renderer/reducers/utils.js
Labels: scope: channels, type: bug 🐛, type: enhancement

#2044 fix(ui): select component initial value
  renderer/components/UI/Input.js
  renderer/components/UI/Select.js
  renderer/components/UI/messages.js
  test/unit/components/UI/Select.spec.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: bug 🐛

#2052 fix(i18n): select current locale in language menu
  electron/menuBuilder.js
Labels: type: bug 🐛

#2053 fix(wallet): show invoice final amount in activity list
  renderer/components/Activity/Invoice/Invoice.js
Labels: scope: wallet, type: bug 🐛

#2054 fix(ui): autofocus amount fields
  renderer/components/Channels/ChannelCreateForm.js
  renderer/components/UI/CurrencyFieldGroup.js
  renderer/containers/Channels/ChannelCreateForm.js
Labels: scope: ui/ux, type: bug 🐛, type: enhancement

#2050 fix(linux): provide desktop app icon
  electron/main.js
  package.json
  resources/linux/128x128.png
  resources/linux/16x16.png
  resources/linux/24x24.png
  resources/linux/256x256.png
  resources/linux/32x32.png
  resources/linux/48x48.png
  resources/linux/512x512.png
  resources/linux/64x64.png
Labels: type: bug 🐛

#2049 fix(ui): improve scrollbar visibility
  renderer/components/UI/GlobalStyle.js
Labels: scope: ui/ux, type: enhancement

#2010 fix(deps): update lnd to v0.6-beta
  package.json
  yarn.lock
Labels: scope: lnd, type: chore

#2067 fix(wallet): fix issues with failing tests
  electron/controller.js
  renderer/components/Dialog/DialogLndCrashed.js
  renderer/reducers/address.js
  renderer/reducers/app.js
  renderer/reducers/neutrino.js
  services/neutrino/neutrino.js
  test/unit/lnd/neutrino.spec.js
  utils/validateHost.js
Labels: scope: tests, type: bug 🐛

#2066 perf(channels): optimize list rendering
  package.json
  renderer/components/Channels/ChannelCardList.js
  renderer/components/Channels/ChannelCardListItem.js
  renderer/components/Channels/ChannelSummaryListItem.js
  yarn.lock
Labels: scope: channels, scope: performance

#2055 refactor: combine grpc services
  config/default.js
  package.json
  renderer/reducers/address.js
  renderer/reducers/balance.js
  renderer/reducers/channels.js
  renderer/reducers/info.js
  renderer/reducers/invoice.js
  renderer/reducers/lnd.js
  renderer/reducers/network.js
  renderer/reducers/neutrino.js
  renderer/reducers/pay.js
  renderer/reducers/payment.js
  renderer/reducers/peers.js
  renderer/reducers/transaction.js
  renderer/reducers/utils.js
  renderer/workers/grpc.worker.js
  renderer/workers/index.js
  renderer/workers/lightning.worker.js
  renderer/workers/walletUnlocker.worker.js
  services/grpc/grpc.js
  services/grpc/grpcService.js
  services/grpc/lightning/lightning.js
  services/grpc/lightning/lightning.methods.js
  services/grpc/lightning/lightning.subscriptions.js
  services/grpc/walletUnlocker/walletUnlocker.js
  services/grpc/walletUnlocker/walletUnlocker.methods.js
  test/unit/__helpers__/setup.js
  test/unit/reducers/__snapshots__/lnd.spec.js.snap
  test/unit/reducers/lnd.spec.js
  utils/log.js
  webpack/dev/workers.config.js
  webpack/prod/workers.config.js
Labels: type: refactor

#2065 build(webpack): fix broken source map links
  webpack/dev/common/devserver.js
  webpack/dev/main.config.js
  webpack/dev/preload.config.js
  webpack/dev/renderer.config.js
  webpack/dev/workers.config.js
  webpack/prod/workers.config.js
Labels: type: enhancement

#2081 docs: add notes on debugging tools
  docs/ADVANCED.md
  docs/DEBUGGING.md
Labels: scope: documentation

#2078 fix(electron): use os rather than platform name for releases
  package.json
Labels: type: enhancement

#2084 fix(lnd): increase lnd debug level
  lnd/neutrino.js
Labels: type: bug 🐛, type: enhancement

#2079 fix(electron): handle autoupdate errors
  electron/updater.js
Labels: scope: linux, type: bug 🐛

#2077 feat(config): read autoupdate settings from global config
  config/custom-environment-variables.json
  config/default.js
  electron/updater.js
Labels: type: enhancement

#2085 refactor: refactor neutrino class into smaller methods
  services/neutrino/neutrino.js
Labels: type: refactor

#2086 fix(i18n): add intl support for selects
  renderer/components/Activity/Activity.js
  renderer/components/Activity/ActivityActions/ActivityFilter.js
  renderer/components/Activity/ActivityActions/messages.js
  renderer/components/Channels/ChannelFilter.js
  renderer/components/Channels/messages.js
  renderer/components/UI/Select.js
  renderer/reducers/activity.js
  test/unit/reducers/__snapshots__/activity.spec.js.snap
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: i18n

#2102 ci: pin node to version 11.x
  .travis.yml
  appveyor.yml
Labels: scope: devops

#2106 refactor: disable autopay functionality
  config/default.js
  renderer/components/Home/WalletLauncher.js
  renderer/components/Wallet/WalletMenu.js
  renderer/reducers/autopay.js
  utils/featureFlag.js
Labels: type: refactor

#2101 refactor: combine create/import wallet actions
  config/default.js
  package.json
  renderer/components/Onboarding/Onboarding.js
  renderer/components/Onboarding/Steps/WalletCreate.js
  renderer/components/Onboarding/Steps/WalletRecover.js
  renderer/components/Onboarding/Steps/messages.js
  renderer/components/UI/PasswordInput.js
  renderer/containers/Onboarding.js
  renderer/reducers/lnd.js
  renderer/reducers/onboarding.js
  renderer/reducers/wallet.js
  services/grpc/grpc.js
  services/grpc/walletUnlocker/walletUnlocker.methods.js
  stories/containers/onboarding.stories.js
  test/unit/reducers/__snapshots__/lnd.spec.js.snap
  test/unit/reducers/lnd.spec.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
  yarn.lock
Labels: scope: onboarding, type: enhancement, type: feature, type: refactor

#2098 feat(wallet): improve fee estimation
  config/default.js
  package.json
  renderer/components/Pay/Pay.js
  renderer/components/Pay/PaySummaryOnChain.js
  renderer/reducers/pay.js
  services/grpc/lightning/lightning.methods.js
  test/unit/components/Pay/__snapshots__/PaySummaryOnchain.spec.js.snap
  utils/fee.js
  yarn.lock
Labels: scope: ui/ux, scope: wallet

#2118 refactor: rename Grpc service class
  services/grpc/grpc.js
  services/grpc/grpcService.js
  services/grpc/lightning/lightning.js
  services/grpc/walletUnlocker/walletUnlocker.js
Labels: type: refactor

#2104 fix(deps): update lnd to v0.6.0-beta-31-g43f1290e
  package.json
  renderer/reducers/lnd.js
  services/grpc/grpcService.js
  services/grpc/lightning/lightning.js
  test/unit/reducers/__snapshots__/lnd.spec.js.snap
Labels: type: enhancement

#2119 fix(lnd): subscriptions to Lightning service
  renderer/reducers/lnd.js
  services/grpc/grpcService.js
Labels: type: bug 🐛

#2115 test(e2e): fix tests getting stuck on win in some cases
  test/e2e/utils/helpers.js
Labels: scope: tests

#2110 feat(ui): allow to set default network and toggle autopilot for mainnet
  config/default.js
  renderer/components/Onboarding/Onboarding.js
  renderer/components/Onboarding/Steps/Network.js
  test/e2e/onboarding-create.spec.js
  test/e2e/onboarding-import.spec.js
  utils/featureFlag.js
Labels: scope: onboarding, type: enhancement

#2126 fix(wallet): store and reuse unused address
  renderer/reducers/address.js
Labels: scope: wallet, type: bug 🐛

#2120 feat(onboarding): paste seed support in wallet recover
  renderer/components/Onboarding/Steps/ConnectionDetailsManual.js
  renderer/components/Onboarding/Steps/Recover.js
  renderer/components/UI/Input.js
  renderer/components/UI/TextArea.js
  test/unit/utils/parseSeed.spec.js
  utils/parseSeed.js
Labels: scope: onboarding, scope: ui/ux, type: enhancement

#2116 fix(ui): constrain wallet name to 30 chars max
  renderer/components/Home/WalletSettingsFormLocal.js
  renderer/components/Home/WalletSettingsFormRemote.js
  renderer/components/Home/WalletUnlocker.js
  renderer/components/Onboarding/Steps/Login.js
  renderer/components/Onboarding/Steps/Name.js
  renderer/components/Onboarding/Steps/Password.js
  renderer/components/Onboarding/Steps/WalletRecover.js
  renderer/components/UI/CryptoAmountInput.js
  renderer/components/UI/Input.js
  renderer/components/UI/OpenDialogInput.js
  renderer/components/UI/PasswordInput.js
  renderer/components/UI/TextArea.js
  renderer/components/UI/index.js
  renderer/hocs/index.js
  renderer/hocs/withInputValidation.js
  test/unit/components/UI/__snapshots__/Input.spec.js.snap
  test/unit/components/UI/__snapshots__/NodePubkeyInput.spec.js.snap
  test/unit/components/UI/__snapshots__/Select.spec.js.snap
  test/unit/components/UI/__snapshots__/TextArea.spec.js.snap
Labels: scope: onboarding, type: enhancement

#2127 refactor: pluck unused props before passing to dom
  renderer/components/Pay/Pay.js
  renderer/components/Request/Request.js
Labels: type: refactor

#2121 fix(grpc): comlink callback error
  renderer/reducers/lnd.js
  services/grpc/grpc.js
Labels: type: bug 🐛

#2132 fix(security): update csp settings
  webpack/dev/renderer.config.js
  webpack/prod/renderer.config.js
Labels: scope: security, type: bug 🐛

#2134 perf(app): prevent superfluous top level re-renders
  renderer/components/App/App.js
  test/unit/utils/scheduler.spec.js
  utils/scheduler.js
Labels: scope: performance, type: refactor
