Repository LN-Zap/zap-desktop, pull requests merged in 2019-05, with the labels that each got.

#2138 fix(grpc): subscribe for topology update only after sync is done
  package.json
  services/grpc/grpc.js
  services/grpc/grpcService.js
  services/grpc/lightning/lightning.js
  services/grpc/lightning/lightning.subscriptions.js
  services/grpc/lightning/streamify.js
  services/grpc/walletUnlocker/walletUnlocker.js
  yarn.lock
Labels: scope: grpc, type: bug 🐛, type: refactor

#2133 feat(lnd): track wallet recovery process
  renderer/components/Syncing/Address.js
  renderer/components/Syncing/NewWalletHeader.js
  renderer/components/Syncing/OldWalletHeader.js
  renderer/components/Syncing/Progress.js
  renderer/components/Syncing/Syncing.js
  renderer/components/Syncing/Tutorials.js
  renderer/components/Syncing/index.js
  renderer/components/Syncing/messages.js
  renderer/containers/Syncing.js
  renderer/reducers/neutrino.js
  services/neutrino/neutrino.js
  stories/Provider.js
  stories/containers/syncing.stories.js
  test/unit/reducers/__snapshots__/neutrino.spec.js.snap
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: onboarding, type: enhancement

#2140 refactor: clean up neutrino args
  config/default.js
  services/neutrino/neutrino.js
  utils/lndConfig.js
Labels: type: refactor

#2141 refactor(grpc): notify after state transitions
  services/grpc/grpc.js
Labels: type: bug 🐛, type: refactor

#2135 chore: add new build flags to lnd build script
  scripts/lnd-release/.goreleaser.yml
Labels: scope: lnd, type: chore

#2143 refactor: migrate to node-lnd-grpc
  config/default.js
  electron/preload.js
  package.json
  renderer/reducers/channels.js
  renderer/reducers/lnd.js
  renderer/reducers/peers.js
  renderer/workers/grpc.worker.js
  renderer/workers/index.js
  services/grpc/grpc.js
  services/grpc/grpcService.js
  services/grpc/helpers.js
  services/grpc/lightning.methods.js
  services/grpc/lightning.subscriptions.js
  services/grpc/lightning/index.js
  services/grpc/lightning/lightning.js
  services/grpc/walletUnlocker/index.js
  services/grpc/walletUnlocker/walletUnlocker.js
  services/grpc/walletUnlocker/walletUnlocker.methods.js
  utils/createMacaroonCreds.js
  utils/createSslCreds.js
  utils/getDeadline.js
  utils/grpcOptions.js
  utils/lndConfig.js
  utils/lndGrpcProtoDir.js
  utils/streamify.js
  utils/waitForFile.js
  yarn.lock
Labels: type: refactor

#2153 feat(wallet): bech32 address support
  config/default.js
  renderer/components/Syncing/Syncing.js
  renderer/containers/Syncing.js
  renderer/containers/Wallet/ReceiveModal.js
  renderer/reducers/address.js
  renderer/reducers/info.js
  renderer/reducers/transaction.js
  test/unit/reducers/__snapshots__/address.spec.js.snap
  test/unit/reducers/address.spec.js
Labels: scope: wallet, type: feature

#2147 feat(wallet): apply BOS node scores to lnd autopilot
  config/default.js
  renderer/components/App/App.js
  renderer/containers/App.js
  renderer/containers/Root.js
  renderer/reducers/autopilot.js
  renderer/reducers/index.js
  services/neutrino/neutrino.js
  utils/api.js
  webpack/dev/renderer.config.js
  webpack/prod/renderer.config.js
Labels: type: feature

#2158 fix(onboarding): improve handling of empty form values
  electron/preload.js
  renderer/components/Home/WalletLauncher.js
  renderer/components/Home/WalletSettingsFormLocal.js
  renderer/components/Home/WalletSettingsFormRemote.js
  renderer/reducers/wallet.js
  renderer/store/db.js
Labels: type: bug 🐛, type: enhancement

#2159 fix(deps): update lnd to v0.6.1-beta-rc1-1-g83adaaa0
  package.json
  scripts/lnd-release/.goreleaser.yml
Labels: scope: lnd, type: chore

#2175 build(webpack): fix hot reload issue
  package.json
  webpack/webpack.config.dev.js
  webpack/webpack.config.preload.js
Labels: scope: devops, type: bug 🐛

#2176 test(e2e): ensure lnd is killed after tests
  electron/controller.js
  electron/preload.js
  package.json
  renderer/reducers/app.js
  renderer/reducers/ipc.js
  renderer/reducers/neutrino.js
  test/e2e/onboarding-connect-manual.spec.js
  test/e2e/onboarding-create.spec.js
  test/e2e/onboarding-import.spec.js
  test/e2e/utils/helpers.js
Labels: scope: tests

#2177 refactor: consolidate/optimise grpc subscription setup code
  services/grpc/grpc.js
Labels: scope: grpc, type: bug 🐛, type: refactor

#2201 refactor: fix appRootPath to run in main or preload process
  utils/appRootPath.js
Labels: type: bug 🐛

#2192 refactor: reduce listPeers polling frequency
  renderer/components/App/App.js
Labels: scope: performance, type: refactor

#2204 feat(wallet): additional activity search criteria
  renderer/reducers/activity.js
Labels: scope: wallet, type: enhancement

#2191 feat(wallet): ability to include invoice routing hints
  renderer/components/Request/Request.js
  renderer/components/Request/messages.js
  renderer/containers/Request.js
  renderer/reducers/invoice.js
  services/grpc/lightning.methods.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: wallet, type: feature

#2206 fix(onboarding): improved connection error messages
  renderer/reducers/lnd.js
Labels: scope: onboarding, type: enhancement

#2232 fix(onboarding): disable login button until success
  renderer/reducers/lnd.js
Labels: type: bug 🐛

#2234 fix(sync): improve sync progress bar reporting
  services/neutrino/neutrino.js
Labels: scope: lnd, scope: sync

#2239 refactor: use ProgressBar component in sync screen
  renderer/components/Syncing/Progress.js
Labels: type: refactor

#2245 Node v12 support
  .travis.yml
  appveyor.yml
  package.json
  utils/crypto.js
  yarn.lock
Labels: type: chore

#2248 ci(travis): enable artifacts addon
  .travis.yml
Labels: scope: devops

#2247 fix(deps): update lnd to v0.6.1-beta-1-g487677ec
  package.json
Labels: type: chore

#2235 fix(grpc): setup channel graph stream after sync
  services/grpc/grpc.js
  services/grpc/lightning.subscriptions.js
Labels: scope: grpc, scope: lnd, type: bug 🐛

#2255 fix(deps): update bitcoinjs-lib to v5.0.4
  package.json
  yarn.lock
Labels: type: chore

#2268 docs: fix links in welcome bot messages
  .github/config.yml
Labels: scope: documentation, type: bug 🐛

#2267 fix(ui): connection type radio with light theme
  renderer/components/Onboarding/Steps/ConnectionTypeItem.js
Labels: scope: onboarding, type: bug 🐛

#2287 fix(ui): ipv6 validation and formatting issues when connecting to a remote node
  electron/preload.js
  renderer/components/Onboarding/Steps/ConnectionConfirm.js
  test/unit/utils/splitHostname.spec.js
  utils/splitHostname.js
  utils/validateHost.js
Labels: scope: onboarding, type: bug 🐛, type: enhancement

#2294 refactor(i18n): add missing translation strings
  renderer/components/Channels/messages.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: bug 🐛

#2296 fix(ui): light green bg for success notification
  renderer/themes/dark/colors.js
  renderer/themes/light/colors.js
  renderer/themes/util.js
Labels: scope: ui/ux, type: bug 🐛

#2293 feat(wallet): set default address type to Bech32
  config/default.js
Labels: type: enhancement

#2300 fix(ui): retain selected theme on reload
  renderer/reducers/app.js
Labels: type: bug 🐛

#2298 fix(app): wait for settings on app init
  renderer/reducers/app.js
  renderer/reducers/settings.js
Labels: type: bug 🐛

#2260 docs: setup eslint-plugin-jsdoc and add jsdoc for all utility methods
  .eslintrc.js
  electron/preload.js
  package.json
  utils/api.js
  utils/appRootPath.js
  utils/blockExplorer.js
  utils/btcpayserver.js
  utils/connectionString.js
  utils/crypto.js
  utils/db.js
  utils/delay.js
  utils/dirExists.js
  utils/featureFlag.js
  utils/fee.js
  utils/fetchBlockHeight.js
  utils/fileExists.js
  utils/genId.js
  utils/getDisplayName.js
  utils/getLndListen.js
  utils/getPackageDetails.js
  utils/grpcSslCipherSuites.js
  utils/isBase64url.js
  utils/isStableVersion.js
  utils/isSubDir.js
  utils/lndBinaryName.js
  utils/lndBinaryPath.js
  utils/lndConfig.js
  utils/lndGrpcProtoDir.js
  utils/localWallets.js
  utils/log.js
  utils/notifications.js
  utils/parseSeed.js
  utils/promiseTimeout.js
  utils/promisifiedCall.js
  utils/sanitize.js
  utils/scheduler.js
  utils/streamify.js
  utils/truncate.js
  utils/userFriendlyErrors.js
  utils/validateHost.js
  yarn.lock
Labels: scope: documentation

#2289 build(icons): add ability to generate specific icons
  package.json
  scripts/genIcons.js
  yarn.lock
Labels: scope: devops

#2316 feat(ui): add ability to scroll dropdown menus with arrow buttons
  renderer/components/UI/Dropmenu.js
Labels: type: enhancement

#2312 fix(ui): fix pay form crash
  renderer/components/Pay/Pay.js
  renderer/components/UI/CurrencyFieldGroup.js
  renderer/components/UI/TextArea.js
Labels: type: bug 🐛
