Repository LN-Zap/zap-desktop, pull requests merged in 2019-06, with the labels that each got.

#2323 feat(ui): update Zap logo
  icons/zap-logo.svg
  renderer/components/Home/Home.js
  renderer/components/Icon/ZapLogo.js
  renderer/components/Onboarding/Steps/ConnectionType.js
  renderer/components/Settings/SettingsPage.js
  renderer/components/UI/Modal.js
  renderer/components/Wallet/Wallet.js
  renderer/components/Wallet/WalletLogo.js
Labels: scope: ui/ux, type: enhancement

#2333 fix(wallet): handle case when payment path is missing
  renderer/components/Activity/Payment/Payment.js
  renderer/components/Activity/Payment/messages.js
  renderer/reducers/channels.js
  renderer/reducers/contactsform.js
  renderer/reducers/network.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
  utils/truncateNodePubkey.js
Labels: type: bug 🐛

#2347 refactor: fix prop warnings
  renderer/components/Home/WalletUnlocker.js
  renderer/components/Onboarding/Onboarding.js
Labels: type: bug 🐛

#2348 fix(ui): display channel cards at equal heights
  renderer/components/Channels/ChannelCardList.js
  renderer/components/Channels/ChannelCardListItem.js
  renderer/components/UI/Card.js
  test/unit/components/UI/__snapshots__/Card.spec.js.snap
Labels: scope: channels, scope: ui/ux, type: enhancement

#2318 feat(wallet): ability to select block explorer
  config/default.js
  electron/preload.js
  renderer/components/Settings/SettingsFieldsWallet.js
  renderer/components/Settings/messages.js
  renderer/reducers/info.js
  test/unit/reducers/__snapshots__/info.spec.js.snap
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: feature

#2344 fix(ui): add padding to bottom of maincontent area
  renderer/components/Home/Home.js
  renderer/components/Settings/SettingsPage.js
Labels: scope: ui/ux, type: enhancement

#2367 fix: dom props warning
  renderer/components/Home/WalletUnlocker.js
Labels: type: refactor

#2366 fix(wallet): prevent crash when sending funds onchain
  renderer/components/Pay/Pay.js
  renderer/components/Pay/PaySummaryOnChain.js
  renderer/components/UI/TransactionFeeInput.js
  renderer/components/UI/index.js
Labels: type: bug 🐛

#2330 build: separate renderer webpack config to fix hmr
  package.json
  webpack/dev/common/devserver.js
  webpack/dev/main.config.js
  webpack/dev/preload.config.js
  webpack/dev/renderer.config.js
  webpack/dev/workers.config.js
  webpack/webpack.config.base.js
  webpack/webpack.config.dll.js
  webpack/webpack.config.eslint.js
  webpack/webpack.config.main.js
  webpack/webpack.config.preload.js
  webpack/webpack.config.renderer.js
Labels: scope: devops

#2358 refactor: use initialValue to set initial value for Select
  renderer/components/Activity/ActivityActions/ActivityFilter.js
  renderer/components/Settings/SettingsFieldsGeneral.js
  renderer/components/Settings/SettingsFieldsWallet.js
Labels: type: bug 🐛

#2346 feat(ui): implement new activity action bar design
  renderer/components/Activity/Activity.js
  renderer/components/Activity/ActivityActions/ActivityActions.js
  renderer/components/Activity/ActivityActions/ActivityFilter.js
  renderer/components/Activity/ActivityActions/ActivitySearch.js
  renderer/components/Activity/ActivityActions/messages.js
  renderer/components/UI/ActionButton.js
  renderer/components/Wallet/Wallet.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: ui/ux, type: enhancement

#2381 test(e2e): add basic ui test
  renderer/components/Activity/Activity.js
  renderer/components/Activity/ActivityListItem.js
  renderer/components/Activity/Transaction/Transaction.js
  renderer/components/Settings/SettingsMenu/SettingsMenu.js
  renderer/containers/Activity.js
  test/e2e/basic-ui.spec..js
  test/e2e/onboarding-connect-manual.spec.js
  test/e2e/pages/wallet.js
Labels: scope: tests

#2384 refactor: use single lodash dependency
  electron/main.js
  i18n/index.js
  package.json
  renderer/components/Activity/TransactionModal/TransactionModal.js
  renderer/components/Channels/ChannelCardListItem.js
  renderer/components/Channels/ChannelCreateForm.js
  renderer/components/Channels/ChannelNodeSearch.js
  renderer/components/Channels/ChannelSummaryListItem.js
  renderer/components/Channels/Channels.js
  renderer/components/Onboarding/Steps/BackupSetupLocal.js
  renderer/components/Pay/Pay.js
  renderer/components/Settings/SettingsFieldsWallet.js
  renderer/components/Settings/SettingsPage.js
  renderer/containers/Wallet/ReceiveModal.js
  renderer/hooks/useDebounce.js
  renderer/reducers/address.js
  renderer/reducers/backup.js
  renderer/reducers/channels.js
  renderer/reducers/contactsform.js
  renderer/reducers/info.js
  renderer/reducers/modal.js
  renderer/reducers/notification.js
  renderer/reducers/pay.js
  renderer/reducers/settings.js
  renderer/reducers/ticker.js
  scripts/genIcons.js
  services/grpc/grpc.js
  utils/btcpayserver.js
  utils/connectionString.js
  utils/crypto.js
  utils/difference.js
  utils/fee.js
  utils/fetchBlockHeight.js
  utils/lndConfig.js
  utils/streamify.js
  yarn.lock
Labels: type: refactor

#2368 fix(lnd): allow to simultaniously run lnd and local zap locally on win
  config/default.js
  config/production.js
Labels: type: bug 🐛

#2396 fix(ui): empty suggested nodes after logout
  renderer/components/App/App.js
  renderer/containers/App.js
  renderer/containers/Initializer.js
Labels: scope: channels, type: bug 🐛

#2390 feat(ui): make wallet connection indicator more informative
  renderer/components/Settings/SettingsMenu/SettingsMenu.js
  renderer/containers/Settings/SettingsMenu.js
  renderer/reducers/info.js
  renderer/reducers/lnd.js
  services/grpc/grpc.js
  services/grpc/lightning.subscriptions.js
  stories/containers/settingsmenu.stories.js
Labels: scope: ui/ux, type: enhancement

#2401 fix(ui): activity scrollbar
  renderer/components/App/App.js
Labels: scope: wallet, type: bug 🐛

#2400 fix: unknown dom prop warning
  renderer/components/Channels/ChannelCreateForm.js
Labels: type: refactor

#2399 perf: debounce updateNodeData
  renderer/reducers/channels.js
  renderer/reducers/network.js
  renderer/store/configureStore.dev.js
  renderer/store/configureStore.prod.js
  renderer/store/middleware/debounceMiddleware.js
  test/unit/utils/debouncedFuncQueue.spec.js
  utils/debouncedFuncQueue.js
Labels: scope: performance

#2407 fix(activity): LN invoice paid date
  renderer/components/Request/RequestSummary.js
Labels: scope: ui/ux, type: enhancement

#2411 fix(ui): prevent double scrollbars on windows
  renderer/components/UI/GlobalStyle.js
Labels: type: bug 🐛

#2412 fix(ui): activity and channels search clear button placement
  renderer/components/Activity/ActivityActions/ActivityActions.js
  renderer/components/Channels/ChannelFilter.js
  renderer/components/Channels/ChannelSort.js
  renderer/components/Channels/ChannelsActions.js
  renderer/components/UI/Dropdown.js
  test/unit/components/UI/__snapshots__/Dropdown.spec.js.snap
  test/unit/utils/debouncedFuncQueue.spec.js
Labels: type: bug 🐛

#2406 fix(deps): update lnd to v0.6.1-beta-255-gb3fd7cc8
  electron/migrations/delete-tmp-wallets.js
  electron/migrations/purge-local-wallets.js
  electron/migrator.js
  electron/preload.js
  package.json
  services/neutrino/neutrino.js
  utils/localWallets.js
Labels: scope: lnd, type: enhancement

#2417 fix(wallet): fetch upto 2500 invoices
  renderer/reducers/invoice.js
Labels: scope: wallet, type: bug 🐛

#2424 feat(settings): add ability to select exchange rate provider
  config/default.js
  renderer/components/App/App.js
  renderer/components/Settings/SettingsFieldsWallet.js
  renderer/components/Settings/SettingsForm.js
  renderer/components/Settings/messages.js
  renderer/containers/App.js
  renderer/containers/Initializer.js
  renderer/containers/Settings/SettingsForm.js
  renderer/containers/Settings/SettingsPage.js
  renderer/reducers/app.js
  renderer/reducers/ticker.js
  stories/Provider.js
  test/unit/reducers/__snapshots__/ticker.spec.js.snap
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
  utils/api.js
  utils/fiat/rateProvider.js
  webpack/dev/common/devserver.js
  webpack/dev/renderer.config.js
  webpack/prod/renderer.config.js
Labels: scope: wallet, type: feature

#2420 feat(wallet): button to copy transaction details
  renderer/components/Activity/ActivityModal/ActivityModal.js
  renderer/components/Activity/TransactionModal/TransactionModal.js
  renderer/components/Activity/TransactionModal/messages.js
  renderer/components/UI/CopyBox.js
  renderer/components/UI/CopyButton.js
  renderer/components/UI/index.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: ui/ux, scope: wallet, type: enhancement

#2421 chore(deps): pin electron-builder to v20.41.0
  package.json
  yarn.lock
Labels: scope: devops

#2427 feat(wallet): ability to customise invoice expire time
  config/default.js
  renderer/components/Home/AutopilotAllocation.js
  renderer/components/Home/WalletSettingsFormLocal.js
  renderer/components/Home/WalletSettingsFormRemote.js
  renderer/components/Settings/SettingsFieldHelpers.js
  renderer/components/Settings/SettingsFieldsWallet.js
  renderer/components/Settings/messages.js
  renderer/components/UI/Input.js
  renderer/reducers/invoice.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: wallet, type: feature

#2438 fix(ui): add top padding to autopay modal
  renderer/containers/ModalStack.js
Labels: scope: autopay, type: bug 🐛

#2432 fix(wallet): ensure minimum transaction fee of 1 sat per byte
  utils/fee.js
Labels: scope: wallet, type: bug 🐛

#2443 refactor: remove unused useInterval hook
  renderer/components/Util/hooks/useInterval.js
  renderer/hooks/index.js
  renderer/hooks/useInterval.js
Labels: type: refactor

#2436 fix(wallet): clear lightning link payment request after use
  electron/main.js
  renderer/components/App/App.js
  renderer/components/Pay/Pay.js
  renderer/containers/App.js
  renderer/containers/Pay.js
  renderer/reducers/pay.js
Labels: scope: wallet, type: bug 🐛

#2441 feat(ui): add copy button for channel transactions
  renderer/components/Activity/TransactionModal/TransactionModal.js
  renderer/components/Activity/TransactionModal/messages.js
  renderer/components/Channels/ChannelData.js
  renderer/components/Channels/messages.js
  renderer/components/UI/CopyButton.js
  renderer/components/UI/messages.js
  renderer/containers/UI/CopyButton.js
  renderer/containers/UI/index.js
  renderer/containers/UI/messages.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: wallet, type: feature

#2416 perf: reduce excess activity list rerenders
  renderer/components/Activity/Activity.js
  renderer/components/Activity/ActivityActions/ActivityActions.js
  renderer/components/Activity/ActivityActions/ActivitySearch.js
  renderer/components/Activity/ActivityListItem.js
  renderer/containers/Activity.js
  renderer/containers/Activity/Activity.js
  renderer/containers/Activity/ActivityActions.js
  renderer/containers/Activity/ActivityModal.js
  renderer/containers/Activity/Invoice.js
  renderer/containers/Activity/Payment.js
  renderer/containers/Activity/Transaction.js
  renderer/containers/Activity/index.js
  renderer/containers/Pay/PaySummaryLightning.js
  renderer/containers/Pay/PaySummaryOnChain.js
  renderer/reducers/activity.js
  renderer/reducers/channels.js
  renderer/reducers/contactsform.js
  renderer/reducers/invoice.js
  renderer/reducers/network.js
  renderer/reducers/payment.js
  renderer/reducers/transaction.js
  test/unit/reducers/__snapshots__/activity.spec.js.snap
  test/unit/reducers/__snapshots__/invoice.spec.js.snap
  test/unit/reducers/activity.spec.js
  test/unit/reducers/invoice.spec.js
  utils/crypto.js
Labels: scope: performance, scope: wallet

#2422 build(webpack): ensure NODE_ENV=production for prod build
  webpack/prod/main.config.js
Labels: scope: devops

#2445 fix(ui): use primary colour for dialog buttons
  renderer/components/UI/CloseButton.js
  renderer/themes/util.js
  test/unit/components/UI/__snapshots__/Modal.spec.js.snap
Labels: scope: ui/ux, type: bug 🐛

#2451 fix(wallet): adjust default target confs to 1/6/60
  config/default.js
Labels: scope: wallet, type: enhancement

#2446 fix(walet): ensure fallback when ticker provider is unavailable
  renderer/components/Settings/SettingsFieldsWallet.js
  renderer/reducers/ticker.js
  test/unit/utils/rateProvider.spec.js
  utils/rateProvider/index.js
  utils/rateProvider/providers.js
  utils/rateProvider/requestTicker.js
  utils/rateProvider/requestTickerWithFallback.js
Labels: scope: wallet, type: enhancement

#2455 perf: debounce sync progress updates
  renderer/components/UI/ProgressBar.js
  renderer/reducers/neutrino.js
  test/unit/reducers/__snapshots__/neutrino.spec.js.snap
  test/unit/reducers/neutrino.spec.js
Labels: scope: performance, scope: ui/ux

#2458 fix(wallet): use selector for sending payments
  renderer/reducers/activity.js
  renderer/reducers/payment.js
Labels: scope: wallet, type: bug 🐛

#2448 fix(deps): update lnd to v0.7.0-beta-rc1-1-g17986e83
  package.json
Labels: scope: lnd

#2464 fix(ui): ensure logo remains in constant position
  renderer/components/Wallet/Wallet.js
Labels: scope: ui/ux, scope: wallet, type: enhancement

#2460 fix(ui): ensure onboarding next button fully clickable
  renderer/components/Onboarding/Onboarding.js
  renderer/components/Onboarding/Steps/components/Container.js
  renderer/components/UI/Wizard.js
Labels: scope: ui/ux, type: bug 🐛

#2463 refactor: use danger variant for delete wallet button
  renderer/components/Home/WalletLauncher.js
Labels: scope: ui/ux, type: enhancement

#2468 fix(ui): adjust sizes of launchpad inputs
  renderer/components/Home/WalletSettingsFormLocal.js
  renderer/components/Home/WalletSettingsFormRemote.js
  renderer/components/UI/LndConnectionStringEditor.js
Labels: scope: ui/ux, type: enhancement

#2469 fix(wallet): use decorated selector for transactions sending
  renderer/reducers/activity.js
  renderer/reducers/transaction.js
Labels: type: bug 🐛

#2456 feat(backups): implement SCB restore
  config/default.js
  electron/preload.js
  electron/walletBackup/base/TokenBasedBackupService.js
  electron/walletBackup/dropbox/dbApi.js
  electron/walletBackup/dropbox/index.js
  electron/walletBackup/gdrive/gdrive.js
  electron/walletBackup/gdrive/gdriveApi.js
  electron/walletBackup/gdrive/index.js
  electron/walletBackup/local/index.js
  electron/walletBackup/service.js
  renderer/components/App/App.js
  renderer/components/Onboarding/Onboarding.js
  renderer/components/Onboarding/Steps/BackupSetup.js
  renderer/components/Onboarding/Steps/WalletCreate.js
  renderer/components/Onboarding/Steps/messages.js
  renderer/containers/Onboarding.js
  renderer/reducers/backup.js
  renderer/reducers/ipc.js
  renderer/reducers/lnd.js
  test/unit/__helpers__/setup.js
  test/unit/__mocks__/electron.js
  test/unit/utils/validateHost.spec.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
  utils/.eslintrc.js
  utils/backup.js
  utils/featureFlag.js
  utils/time.js
Labels: backups, type: feature

#2477 refactor: make "Creating wallet" string translatable
  renderer/components/Onboarding/Steps/WalletCreate.js
  renderer/components/Onboarding/Steps/messages.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: i18n

#2475 feat(ui): show spinner during sync whilst addresses load
  renderer/components/Syncing/Address.js
  renderer/components/Syncing/Syncing.js
  renderer/components/Syncing/messages.js
  renderer/containers/Syncing.js
  renderer/reducers/address.js
  stories/containers/syncing.stories.js
  test/unit/reducers/__snapshots__/address.spec.js.snap
  test/unit/reducers/address.spec.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: sync, scope: ui/ux, type: enhancement

#2476 feat(ui): display backup method in node profile page
  renderer/components/Profile/ProfilePaneNodeInfo/ProfilePaneNodeInfo.js
  renderer/components/Profile/ProfilePaneNodeInfo/messages.js
  renderer/containers/Profile/ProfilePaneNodeInfo.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: backups

#2478 refactor: don't mutate objects when decorating
  renderer/reducers/invoice.js
  renderer/reducers/payment.js
  renderer/reducers/transaction.js
Labels: type: refactor

#2461 fix(ui): use Select widget for invoice expiry
  renderer/components/Home/WalletLauncher.js
  renderer/components/Settings/SettingsFieldsWallet.js
  renderer/components/Settings/SettingsPage.js
  renderer/components/Settings/messages.js
  renderer/reducers/invoice.js
  test/unit/reducers/__snapshots__/invoice.spec.js.snap
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: ui/ux, type: enhancement

#2462 refactor: fix lodash import in generate-icon script
  package.json
  scripts/fetch-lnd-for-packaging.js
  scripts/genIcons.js
Labels: type: bug 🐛

#2479 refactor: improve fee estimation error handling
  utils/api.js
  utils/error.js
  utils/fee.js
Labels: type: enhancement, type: refactor

#2483 feat(activity): improve search
  renderer/reducers/activity.js
Labels: scope: ui/ux, type: enhancement

#2481 fix(deps): update lnd to v0.7.0-beta-rc2-1-g360a7fe6
  package.json
Labels: scope: lnd

#2480 feat(backups): allow skipping backup setup process
  renderer/components/Onboarding/Onboarding.js
  renderer/components/Onboarding/Steps/BackupSetup.js
  renderer/components/Onboarding/Steps/components/SkipBackupsDialog.js
  renderer/components/Onboarding/Steps/components/messages.js
  renderer/components/Onboarding/Steps/messages.js
  renderer/components/Onboarding/messages.js
  renderer/components/UI/DialogOverlay.js
  renderer/components/UI/Wizard.js
  renderer/containers/Onboarding.js
  renderer/reducers/onboarding.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: backups

#2465 fix(launchpad): ensure full form reset on cancel
  renderer/components/Home/WalletLauncher.js
Labels: scope: onboarding, type: bug 🐛

#2484 fix(ui): ensure lndconnect string is trimmed
  renderer/components/Onboarding/Steps/ConnectionConfirm.js
  renderer/components/UI/LndConnectionStringInput.js
Labels: scope: onboarding, type: bug 🐛

#2493 fix(ui): add CopyButton to preimage in Payment modal
  renderer/components/Activity/PaymentModal/PaymentModal.js
  renderer/components/Activity/PaymentModal/messages.js
  translations/da-DK.json
  translations/en.json
  translations/es-ES.json
  translations/ga-IE.json
Labels: scope: ui/ux, scope: wallet, type: bug 🐛, type: enhancement

#2501 fix: electron shutdown flow on win and linux
  electron/controller.js
  electron/main.js
  renderer/reducers/app.js
Labels: type: bug 🐛

#2494 fix(ui): prevent non-numeric chars in number input
  renderer/components/Onboarding/Steps/ConnectionConfirm.js
  renderer/components/Settings/SettingsFieldHelpers.js
  renderer/components/Settings/SettingsFieldsWallet.js
  renderer/components/UI/Input.js
  renderer/components/UI/IntegerInput.js
  renderer/components/UI/index.js
  renderer/reducers/backup.js
  stories/forms/form.stories.js
Labels: scope: ui/ux, scope: wallet, type: bug 🐛, type: enhancement

#2499 fix(grpc): do not include extra google protos
  package.json
  webpack/webpack.config.dll.js
  yarn.lock
Labels: scope: grpc, type: bug 🐛

#2482 refactor: stop using deprecated lnd props
  renderer/components/Activity/ActivityListItem.js
  renderer/components/Activity/Payment/Payment.js
  renderer/components/Activity/PaymentModal/PaymentModal.js
  renderer/containers/Activity/Payment.js
  renderer/reducers/activity.js
  renderer/reducers/invoice.js
  renderer/reducers/payment.js
  renderer/reducers/transaction.js
  renderer/reducers/utils.js
Labels: scope: lnd, type: refactor

#2467 build(lint): remove lint-staged and run lint in pre-push hook
  .huskyrc
  package.json
  yarn.lock
Labels: scope: devops

#2508 fix(ui): don't apply date grouping to raw activity list
  renderer/reducers/activity.js
Labels: type: bug 🐛

#2510 fix(grpc): deadlock when connecting to remote nodes in some cases
  package.json
  renderer/components/Home/WalletLauncher.js
  renderer/reducers/lnd.js
  services/grpc/grpc.js
  yarn.lock
Labels: type: bug 🐛

#2514 fix(settings): ensure number fields use number type
  renderer/components/UI/IntegerInput.js
Labels: scope: wallet, type: bug 🐛

#2519 fix(ui): make display of fees in summary pages consistent
  renderer/components/Channels/ChannelCreateForm.js
  renderer/components/Channels/ChannelCreateSummary.js
  renderer/components/Pay/PaySummaryOnChain.js
  renderer/components/UI/Dropdown.js
  renderer/components/UI/Dropmenu.js
  renderer/containers/UI/CryptoValueSelector.js
  renderer/containers/UI/index.js
  test/unit/components/Pay/__snapshots__/PaySummaryOnchain.spec.js.snap
  test/unit/components/UI/__snapshots__/Dropdown.spec.js.snap
Labels: type: bug 🐛

#2524 chore(i18n): fix payment request copy
  renderer/components/Request/messages.js
  translations/en.json
Labels: scope: ui/ux

#2527 fix(grpc): activate Lightning grpc after init wallet
  renderer/reducers/lnd.js
  services/grpc/grpc.js
Labels: scope: grpc, scope: lnd, type: bug 🐛

#2525 fix(ui): separate version/commit on profile pane
  renderer/components/Profile/ProfilePaneNodeInfo/ProfilePaneNodeInfo.js
  renderer/containers/Profile/ProfilePaneNodeInfo.js
  renderer/reducers/info.js
  services/grpc/lightning.methods.js
Labels: scope: ui/ux, type: bug 🐛
