Repository LN-Zap/zap-desktop, pull requests merged in 2019-09, with the labels that each got.

#2833 fix: crash in some cases when opening multiple modals
  renderer/components/ModalStack.js
  renderer/containers/Root.js
Labels: scope: ui/ux, scope: wallet, type: bug 🐛

#2835 fix(scheduler): buggy task replacement and removeAll behavior
  test/unit/utils/scheduler.spec.js
  utils/scheduler.js
Labels: type: bug 🐛

#2836 fix: ensure app is focused after menu interaction on windows/linux
  electron/menuBuilder.js
Labels: type: bug 🐛

#2840 chore: add rebass to restricted imports rule
  .eslintrc.js
  renderer/components/Form/InputContainer.js
  renderer/components/UI/CenteredContent.js
Labels: scope: devops

#2844 chore: allow overriding state props in sb components
  .storybook/patchedReactRedux.js
  .storybook/webpack.config.js
Labels: scope: devops

#2842 fix(ui): ensure select value from items list
  renderer/components/Form/Select.js
  stories/forms/form.stories.js
  test/unit/components/Form/__snapshots__/Select.spec.js.snap
Labels: type: bug 🐛

#2847 fix(checkbox): react uncontrolled component warning
  renderer/components/Form/Checkbox.js
  test/unit/components/Form/__snapshots__/Checkbox.spec.js.snap
Labels: type: bug 🐛

#2849 fix(ui): prevent dropdowns and selects from overflowing bottom screen bound
  renderer/components/Form/Select.js
  renderer/components/UI/Dropdown.js
  renderer/components/UI/Dropmenu.js
  renderer/hooks/index.js
  renderer/hooks/useMaxScreenHeight.js
  renderer/hooks/useWindowDimensions.js
Labels: type: bug 🐛, type: enhancement

#2848 fix(wallet): ensure address generation works
  renderer/reducers/address.js
Labels: type: bug 🐛

#2851 New Crowdin translations
  translations/ru-RU.json
Labels: type: chore

#2866 build: use @ln-zap/eslint-config and @ln-zap/prettier-config
  .eslintrc.js
  .prettierrc
  package.json
  yarn.lock
Labels: type: refactor

#2883 New Crowdin translations
  translations/de-DE.json
  translations/es-ES.json
Labels: scope: i18n

#2879 feat(ui): implement skeleton loading screen
  renderer/components/Loading/Loading.js
  renderer/components/Loading/LoadingApp.js
  renderer/components/Loading/LoadingBolt.js
  renderer/components/Loading/LoadingLaunchpad.js
  renderer/components/Loading/Placeholder.js
  renderer/components/Loading/Transition.js
  renderer/components/Loading/index.js
  renderer/components/Loading/messages.js
  renderer/components/LoadingBolt/index.js
  renderer/containers/Loading/Loading.js
  renderer/containers/Loading/index.js
  renderer/containers/Root.js
  renderer/hocs/withLoading.js
  renderer/reducers/lnd.js
  renderer/reducers/utils.js
  stories/components/loadingbolt.stories.js
  test/unit/components/LoadingBolt.spec.js
Labels: type: enhancement

#2906 fix(slack): update slack link
  README.md
Labels: scope: documentation

#2882 feat(ui): add ability to configure neutrino nodes for local wallets
  renderer/components/Form/FieldLabel.js
  renderer/components/Form/PositiveIntegerField.js
  renderer/components/Form/RowLabel.js
  renderer/components/Form/index.js
  renderer/components/Home/WalletLauncher.js
  renderer/components/Home/WalletSettingsFormLocal.js
  renderer/components/Home/messages.js
  renderer/components/Settings/SettingsFieldHelpers.js
  renderer/components/Settings/SettingsFieldsGeneral.js
  renderer/components/Settings/SettingsFieldsWallet.js
  renderer/store/schema/wallet.js
  services/neutrino/neutrino.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
  utils/lndConfig.js
Labels: type: enhancement

#2908 fix(ui): open dialog inputs
  renderer/components/Form/OpenDialogInput.js
  renderer/hocs/withOpenDialog.js
Labels: type: bug 🐛
