Repository LN-Zap/zap-desktop, pull requests merged in 2019-10, with the labels that each got.

#2909 fix(select): correctly update select when underlying field changes
  renderer/components/UI/Select.js
Labels: type: bug 🐛

#2922 fix(ui): restore RadioGroup label mb
  renderer/components/Form/RadioGroup.js
Labels: type: bug 🐛

#2915 chore(deps): update dependency electron to v6.0.10
  electron/menuBuilder.js
  package.json
  yarn.lock
Labels: type: refactor

#2934 build(travis): fix mac build issues
  .travis.yml
  package.json
Labels: scope: devops

#2924 fix(ui): center WalletCreate content
  renderer/components/Onboarding/Steps/WalletCreate.js
  renderer/components/UI/index.js
  stories/containers/onboarding/onboarding.component.stories.js
Labels: type: bug 🐛

#2923 fix(ui): close channel create modal after channel opening is finished
  renderer/containers/Channels/ChannelCreate.js
  renderer/reducers/channels.js
  services/grpc/lightning.methods.js
Labels: type: bug 🐛

#2937 feat(ui): show channel reserve amount in channel details view
  renderer/components/Channels/ChannelData.js
  renderer/components/Channels/messages.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: enhancement

#2911 perf(activity): implement activity list pagination
  config/default.js
  renderer/components/Activity/Activity.js
  renderer/components/App/App.js
  renderer/containers/Activity/Activity.js
  renderer/reducers/activity.js
  renderer/reducers/app.js
  renderer/reducers/invoice.js
  renderer/reducers/payment.js
  renderer/reducers/transaction.js
  test/unit/reducers/__snapshots__/activity.spec.js.snap
  test/unit/reducers/__snapshots__/invoice.spec.js.snap
  test/unit/reducers/__snapshots__/payment.spec.js.snap
  test/unit/reducers/activity.spec.js
  test/unit/reducers/invoice.spec.js
  test/unit/reducers/payment.spec.js
  test/unit/utils/pagination.test.js
  utils/pagination.js
Labels: type: bug 🐛, type: enhancement

#2852 New Crowdin translations
  translations/de-DE.json
  translations/fr-FR.json
  translations/it-IT.json
  translations/no-NO.json
  translations/zh-CN.json
Labels: type: chore

#2936 fix(ui): set delete wallet header width to same as content width
  renderer/components/Channels/ChannelCloseDialog.js
  renderer/components/Home/DeleteWalletDialog.js
  renderer/components/Onboarding/Steps/components/ErrorDialog.js
  renderer/components/Onboarding/Steps/components/SkipBackupsDialog.js
  renderer/components/UI/Dialog.js
  test/unit/components/UI/__snapshots__/Dialog.spec.js.snap
Labels: type: enhancement

#2954 fix(ui): crash when trying to save remote node settings
  renderer/components/Home/WalletLauncher.js
  renderer/components/Home/WalletSettingsFormLocal.js
Labels: type: bug 🐛

#2956 perf(routing): update query routes to use mission control
  renderer/reducers/pay.js
Labels: type: enhancement

#2982 revert: b47416e as mistake
  renderer/components/Channels/ChannelCreateForm.js
  renderer/components/Home/Home.js
  renderer/components/Home/WalletLauncher.js
  renderer/components/Onboarding/Steps/ConnectionDetails.js
  renderer/components/Onboarding/Steps/ConnectionDetailsManual.js
  renderer/components/Onboarding/Steps/ConnectionDetailsString.js
  renderer/components/Onboarding/Steps/ConnectionType.js
  renderer/components/Onboarding/Steps/SeedConfirm.js
  renderer/components/Onboarding/Steps/SeedView.js
  renderer/components/Onboarding/Steps/WalletCreate.js
  renderer/components/Onboarding/Steps/WalletRecover.js
  renderer/components/Pay/Pay.js
  renderer/components/Pay/PaySummaryOnChain.js
  renderer/components/UI/Countdown.js
  renderer/containers/Wallet/WalletStarter.js
Labels: type: bug 🐛

#2966 feat(ui): add autosuggest for seed recovery
  renderer/components/Onboarding/Steps/Recover.js
  renderer/components/Onboarding/Steps/components/SeedWordInput.js
  renderer/components/Onboarding/Steps/components/SeedWordList.js
  renderer/containers/Onboarding/Onboarding.js
  renderer/containers/Onboarding/Steps/Recover.js
  test/e2e/onboarding-import.spec.js
  test/e2e/pages/onboarding.js
Labels: type: enhancement

#2983 fix(app): store temp wallets in os tmpdir
  electron/migrator.js
  renderer/reducers/wallet.js
  utils/lndConfig.js
Labels: type: bug 🐛

#2917 refactor: activity list components
  renderer/components/Activity/Activity.js
  renderer/components/Activity/List.js
  renderer/components/Activity/Row.js
  renderer/reducers/activity.js
Labels: type: refactor

#2986 refactor: serve content over http server
  .testcafe-electron-rc
  electron/controller.js
  package.json
  webpack/webpack.config.dll.js
  yarn.lock
Labels: type: refactor

#3001 refactor: simplify scheduler code and handle key cornercase
  test/unit/utils/scheduler.spec.js
  utils/scheduler.js
Labels: type: bug 🐛, type: refactor

#3011 refactor: add secure storage namespacing based on environment
  config/default.js
Labels: scope: devops

#3005 fix(deps): update lnd to 0.8.0-beta-2-gb95a0a0f
  config/default.js
  package.json
Labels: type: enhancement

#2998 fix(ui): retain channel view mode on logout
  renderer/containers/Channels.js
  renderer/containers/Channels/ChannelsHeader.js
  renderer/reducers/channels.js
  test/unit/reducers/__snapshots__/channels.spec.js.snap
Labels: type: enhancement

#3015 fix(ui): clarify current balance wording
  renderer/components/Channels/messages.js
  renderer/components/Pay/messages.js
  translations/en.json
Labels: type: bug 🐛

#3009 fix(ui): incorrect open btn placement in OpenDialogInput errorneus state
  renderer/components/Form/OpenDialogButton.js
  renderer/components/Form/OpenDialogInput.js
Labels: type: bug 🐛

#3022 fix(lnd): switch to testnet1 and testnet2 neutrino peers
  config/default.js
Labels: type: bug 🐛

#3021 fix(lnd): connect to additional neutrino peers
  services/neutrino/neutrino.js
Labels: type: bug 🐛

#3024 fix(wallet): increase fee limit on payment retries
  config/default.js
  renderer/components/Pay/Pay.js
  renderer/reducers/payment.js
  test/unit/utils/crypto.spec.js
  utils/crypto.js
Labels: type: bug 🐛, type: enhancement

#3039 fix(db): wallet table sanitize routine
  renderer/store/schema/wallet.js
Labels: type: bug 🐛

#3050 fix(i18n): extract hardcoded strings to translation files
  renderer/components/Channels/ChannelsMenu/ChannelsMenu.js
  renderer/components/Onboarding/Steps/ConnectionDetailsString.js
  renderer/components/Onboarding/Steps/messages.js
  renderer/components/Pay/Pay.js
  renderer/components/Pay/messages.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: ui/ux, type: bug 🐛

#3049 fix(ui): minor display issues on macOS
  renderer/components/Activity/ActivityActions/ActivityFilter.js
  renderer/components/Channels/ChannelCloseDialog.js
  renderer/components/Dialog/DialogLndCrashed.js
  renderer/components/Home/DeleteWalletDialog.js
  renderer/components/Home/WalletSettingsFormLocal.js
  renderer/components/Home/WalletSettingsFormRemote.js
  renderer/components/Onboarding/Steps/components/ErrorDialog.js
  renderer/components/Onboarding/Steps/components/SkipBackupsDialog.js
  renderer/components/Profile/ProfilePaneNodeInfo/ProfilePaneNodeInfo.js
  renderer/components/UI/RadioCard.js
Labels: scope: ui/ux

#3048 fix(ui): disable app password on windows platform
  config/default.js
  renderer/components/Settings/SettingsPage.js
Labels: scope: security, status: needs rebase

#3055 New Crowdin translations
  translations/cs-CZ.json
Labels: scope: i18n

#3036 fix(ui): don't open channel management modal when not needed
  renderer/components/Channels/ChannelsMenu/ChannelsMenu.js
  test/e2e/basic-ui.spec.js
Labels: scope: ui/ux, type: enhancement

#3056 New Crowdin translations
  translations/fr-FR.json
Labels: scope: i18n

#3061 refactor: ensure window.Zap.getPlatform exists in storybook
  stories/Provider.js
Labels: type: bug 🐛

#3057 feat(ui): confirm password on wallet create
  renderer/components/Onboarding/Steps/Password.js
  renderer/components/Onboarding/Steps/messages.js
  renderer/components/Settings/Security/messages.js
  test/e2e/onboarding-create.spec.js
  test/e2e/onboarding-import.spec.js
  test/e2e/pages/onboarding.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: enhancement

#3067 fix(ui): no form error when form is empty
  renderer/components/Pay/Pay.js
  renderer/components/Pay/PayAddressField.js
  renderer/components/Pay/PayPanelBody.js
  renderer/components/Request/Request.js
  test/unit/components/Pay/PayAddressField.spec.js
  test/unit/components/Pay/__snapshots__/PayAddressField.spec.js.snap
  test/unit/components/Pay/__snapshots__/PayPanelBody.spec.js.snap
Labels: type: bug 🐛

#3078 fix(wallet): correctly handle protocol links on windows
  electron/main.js
Labels: type: bug 🐛

#3072 New Crowdin translations
  translations/de-DE.json
Labels: scope: i18n

#3071 New Crowdin translations
  translations/bg-BG.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hr-HR.json
  translations/it-IT.json
  translations/no-NO.json
  translations/ru-RU.json
Labels: scope: i18n

#3026 Refactor component to use useContext hook instead of withTheme HOC
  renderer/components/Autopay/AutopayAddButton.js
  renderer/components/Autopay/AutopayLimitBadge.js
  renderer/components/Channels/ChannelNodeSearch.js
  renderer/components/Form/Input.js
  renderer/components/Form/InputContainer.js
  renderer/components/Form/Range.js
  renderer/components/Form/TextArea.js
  renderer/components/Form/util.js
  renderer/components/Icon/Dropbox.js
  renderer/components/Loading/LoadingBolt.js
  renderer/components/UI/DialogOverlay.js
  renderer/components/UI/Donut.js
  renderer/components/UI/Dropdown.js
  renderer/components/UI/Dropmenu.js
  renderer/components/UI/QRCode.js
  renderer/containers/Syncing.js
  test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
Labels: type: refactor
