Repository LN-Zap/zap-desktop, pull requests merged in 2019-02, with the labels that each got.

#1431 fix(lnd): support latest version of lnd
  app/lib/lnd/config.js
  app/lib/lnd/lightning.js
  app/lib/lnd/methods/index.js
  app/lib/lnd/neutrino.js
  app/lib/lnd/util.js
  app/lib/lnd/walletUnlocker.js
  app/package.json
  app/reducers/info.js
  app/yarn.lock
  internals/scripts/lnd-release/.goreleaser.yml
  package.json
  resources/rpc.proto
  test/unit/__mocks__/electron.js
  test/unit/lnd/lnd-config.spec.js
  test/unit/reducers/__snapshots__/info.spec.js.snap
  test/unit/reducers/info.spec.js
  test/unit/utils/validateHost.spec.js
Labels: type: bug, type: enhancement

#1458 test(e2e): force kill lnd after e2e tests
  app/lib/lnd/neutrino.js
  app/lib/zap/controller.js
  app/preload.js
Labels: scope: devops, scope: tests

#1462 ci(travis): adjustments for testcafe
  .travis.yml
  package.json
Labels: scope: devops

#1468 refactor(js): fix invalid try/catch syntax
  app/lib/lnd/util.js
Labels: type: bug, type: refactor

#1469 chore(i18n): extract missing translation strings
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: type: refactor

#1466 docs(help): start a troubleshooting guide
  TROUBLESHOOTING.md
Labels: scope: documentation

#1471 feat(ui): add cross platform about menu
  app/lib/utils/getPackageDetails.js
  app/lib/utils/index.js
  app/lib/zap/about/index.js
  app/lib/zap/about/preload.js
  app/lib/zap/about/public/about.html
  app/lib/zap/about/public/renderer.js
  app/lib/zap/about/public/styles/ui.css
  app/lib/zap/menuBuilder.js
  internals/webpack/webpack.config.renderer.prod.js
  package.json
Labels: scope: wallet

#1472 test(e2e): delete lnd data dir after test fixtures
  app/preload.js
  test/e2e/onboarding-btcpay.spec.js
  test/e2e/onboarding-connect.spec.js
  test/e2e/onboarding-create.spec.js
  test/e2e/onboarding-import.spec.js
  test/e2e/utils/helpers.js
Labels: scope: devops, scope: tests

#1477 chore(deps): update lnd-grpc to v0.1.4
  app/package.json
  app/yarn.lock
Labels: type: chore

#1489 chore(deps): regenerate yarn.lock file
  app/yarn.lock
Labels: type: chore

#1488 docs(storybook): ensure story font colour correctly applied
  .storybook/preview-head.html
Labels: scope: documentation, type: enhancement

#1505 chore: bump version to 0.4.0-alpha
  app/package.json
  package.json
Labels: scope: devops, type: chore

#1503 chore(devops): set db name based on app version
  .eslintrc.js
  .gitignore
  app/index.js
  app/lib/lnd/config.js
  app/lib/utils/db.js
  app/main.js
  app/preload.js
  app/reducers/address.js
  app/reducers/info.js
  app/reducers/lnd.js
  app/reducers/locale.js
  app/reducers/theme.js
  app/reducers/ticker.js
  app/reducers/wallet.js
  app/store/db.js
  config/default.js
  internals/webpack/webpack.config.base.js
  internals/webpack/webpack.config.main.prod.js
  internals/webpack/webpack.config.renderer.dev.dll.js
  package.json
  stories/Provider.js
  yarn.lock
Labels: scope: devops, type: chore, type: refactor

#1507 fix(deps): update dependency lnd to v0.5.2-beta
  package.json
  yarn.lock
Labels: type: chore

#1511 fix(wallet): correctly identify active network
  app/components/Contacts/Network/Network.js
  app/components/Wallet/ReceiveModal/ReceiveModal.js
  app/components/Wallet/Wallet.js
  app/containers/Activity/TransactionModalContainer.js
  app/containers/App.js
  app/containers/Pay.js
  app/containers/Wallet.js
  app/reducers/contactsform.js
  app/reducers/info.js
  app/reducers/ticker.js
  test/unit/reducers/__snapshots__/info.spec.js.snap
Labels: scope: wallet, type: bug

#1518 fix(wallet): check node alias exists before using
  app/reducers/contactsform.js
Labels: scope: wallet, type: bug

#1521 fix(ui): improve channel list search and filter
  app/components/Contacts/Network/Network.js
  app/containers/App.js
  app/reducers/channels.js
  test/unit/reducers/__snapshots__/channels.spec.js.snap
  test/unit/reducers/channels.spec.js
Labels: scope: ui/ux, type: bug, type: enhancement

#1524 fix(ui): fix issue with suggested node list shrinking
  app/containers/Contacts/SubmitChannelForm.js
  app/reducers/contactsform.js
Labels: scope: wallet, type: bug

#1519 fix(ui): add missing channel search cancel button
  app/components/Contacts/Network/Network.js
  app/containers/App.js
  app/reducers/channels.js
  test/unit/reducers/__snapshots__/channels.spec.js.snap
Labels: type: bug, type: enhancement

#1526 fix(ui): fix missing show expired requests button
  app/components/UI/BackgroundPrimary.js
  test/unit/components/UI/__snapshots__/BackgroundDark.spec.js.snap
  test/unit/components/UI/__snapshots__/BackgroundPrimary.spec.js.snap
  test/unit/components/UI/__snapshots__/MainContent.spec.js.snap
Labels: scope: wallet, type: bug

#1528 refactor(typo): fix network search bar layout typo
  app/components/Contacts/Network/Network.js
Labels: type: refactor

#1527 fix: hscroll for current and suggested channels panels
  app/components/Contacts/AddChannel/AddChannel.js
  app/components/Contacts/Network/Network.js
  app/components/UI/Modal.js
  test/unit/components/UI/__snapshots__/Modal.spec.js.snap
Labels: scope: wallet, type: bug

#1491 feat(channels): implement new channel summary list
  app/components/Channels/ChannelBalance.js
  app/components/Channels/ChannelCount.js
  app/components/Channels/ChannelSummaryList.js
  app/components/Channels/ChannelSummaryListItem.js
  app/components/Channels/Channels.js
  app/components/Channels/ChannelsHeader.js
  app/components/Channels/index.js
  app/components/Channels/messages.js
  app/components/Contacts/Network/Network.js
  app/components/Form/Form.js
  app/components/Settings/Menu/Menu.js
  app/components/Settings/Menu/messages.js
  app/components/Settings/Settings.js
  app/containers/Channels.js
  app/containers/Settings.js
  app/lib/lnd/methods/channelController.js
  app/reducers/channels.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  stories/containers/channels/channel-balance.stories.js
  stories/containers/channels/channel-count.stories.js
  stories/containers/channels/channel-summary-list-item.stories.js
  stories/containers/channels/channel-summary-list.stories.js
  stories/containers/channels/channels-header.stories.js
Labels: scope: channels, type: feature

#1534 fix: delete button layout glitch
  app/components/Home/WalletLauncher.js
Labels: type: bug

#1540 fix(ui): wallet unlocker button disabled state
  app/components/Home/WalletUnlocker.js
Labels: scope: wallet, type: bug

#1544 fix(lnd): ensure lnd start errors are displayed
  app/reducers/lnd.js
Labels: scope: onboarding, type: bug

#1543 fix(launchpad): disable launch button when launch is in progress
  app/components/Home/Home.js
  app/components/Home/WalletLauncher.js
  app/containers/Home.js
Labels: scope: onboarding, type: bug

#1546 fix(ui): incorrect save wallet action bar visibility
  app/components/Home/WalletLauncher.js
Labels: scope: wallet, type: bug

#1545 refactor(lnd): clean remote node before start code
  app/lib/zap/controller.js
Labels: scope: lnd, type: refactor

#1551 fix(forms): more robust handling for amount inputs
  app/components/UI/CryptoAmountInput.js
  app/components/UI/FiatAmountInput.js
  app/components/withNumberInputMask/index.js
  app/components/withNumberInputMask/withNumberInputMask.js
  app/components/withRequiredValidation/withRequiredValidation.js
  app/lib/utils/getDisplayName.js
Labels: type: bug

#1500 feat(channels): new channel list search filters
  app/components/Channels/ChannelFilter.js
  app/components/Channels/ChannelSearch.js
  app/components/Channels/Channels.js
  app/components/Channels/ChannelsActions.js
  app/components/Channels/ChannelsHeader.js
  app/components/Channels/ChannelsInfo.js
  app/components/Channels/index.js
  app/components/Channels/messages.js
  app/components/Contacts/Network/NetworkActionBar.js
  app/components/UI/Input.js
  app/components/UI/Select.js
  app/components/UI/TextArea.js
  app/containers/Channels.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  stories/forms/form.stories.js
  test/unit/components/UI/Select.spec.js
  test/unit/components/UI/__snapshots__/Input.spec.js.snap
  test/unit/components/UI/__snapshots__/Select.spec.js.snap
  test/unit/components/UI/__snapshots__/TextArea.spec.js.snap
Labels: scope: channels, type: feature

#1539 feat(channels): channel card list and view switcher
  app/components/Channels/ChannelCardList.js
  app/components/Channels/ChannelCardListItem.js
  app/components/Channels/ChannelSummaryList.js
  app/components/Channels/Channels.js
  app/components/Channels/ChannelsActions.js
  app/components/Channels/ChannelsHeader.js
  app/components/Channels/ChannelsViewSwitcher.js
  app/components/Channels/index.js
  app/components/Channels/messages.js
  app/components/Icon/LayoutCards.js
  app/components/Icon/LayoutList.js
  app/containers/Channels.js
  app/icons/layout-cards.svg
  app/icons/layout-list.svg
  app/reducers/channels.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  stories/containers/channels/channel-card-list-item.stories.js
  stories/containers/channels/channel-card-list.stories.js
  stories/containers/channels/channel-summary-list-item.stories.js
  stories/icons/icon.stories.js
  test/unit/reducers/__snapshots__/channels.spec.js.snap
Labels: scope: channels, type: feature

#1561 fix(ui): remote node loading screen
  app/containers/Initializer.js
  app/containers/Root.js
  app/containers/WalletStarter.js
  app/lib/lnd/lightning.js
  app/lib/utils/index.js
  app/lib/utils/promisifiedCall.js
  app/reducers/app.js
  app/reducers/ipc.js
  app/reducers/lnd.js
  app/reducers/onboarding.js
  app/reducers/utils.js
  app/reducers/wallet.js
Labels: scope: wallet, type: bug, type: refactor

#1565 refactor: add missing proptypes
  app/components/withNumberInputMask/withNumberInputMask.js
Labels: type: refactor

#1566 refactor: add LightningChannel icon
  app/components/Icon/LightningChannel.js
  app/icons/lightning-channel.svg
  stories/icons/icon.stories.js
Labels: scope: channels, type: refactor

#1567 refactor: add NodePubkeyInput component
  app/components/UI/NodePubkeyInput.js
  app/components/UI/index.js
  app/components/UI/messages.js
  stories/forms/form.stories.js
  test/unit/components/UI/NodePubkeyInput.spec.js
  test/unit/components/UI/__snapshots__/NodePubkeyInput.spec.js.snap
Labels: scope: channels, type: refactor

#1573 chore(lint): add react hooks rule of hooks
  .eslintrc.js
  package.json
  yarn.lock
Labels: type: chore

#1578 refactor: make logout route redirect declarative
  app/containers/Logout.js
Labels: scope: wallet, type: refactor

#1580 chore(i18n): extract new translation strings
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: type: chore

#1581 refactor(forms): use input labels in pay/request
  app/components/Pay/Pay.js
  app/components/Request/Request.js
Labels: type: refactor

#1568 feat(channels): new create channel form
  app/components/Channels/ChannelBackButton.js
  app/components/Channels/ChannelCreateForm.js
  app/components/Channels/ChannelFooter.js
  app/components/Channels/ChannelList.js
  app/components/Channels/ChannelSummaryListItem.js
  app/components/Channels/Channels.js
  app/components/Channels/ChannelsActions.js
  app/components/Channels/ChannelsHeader.js
  app/components/Channels/index.js
  app/components/Channels/messages.js
  app/components/Form/Form.js
  app/containers/Channels.js
  app/containers/Channels/ChannelCreate.js
  app/containers/Channels/ChannelCreateForm.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  stories/Provider.js
  stories/containers/channels/channel-create-form.stories.js
Labels: scope: channels, type: feature

#1596 fix(wallet): do not crash after paying msat invoices
  app/components/Pay/Pay.js
  app/reducers/activity.js
  app/reducers/payment.js
Labels: scope: wallet, type: bug

#1574 fix(ui): introduce singleton loading screen
  app/components/LoadingBolt/LoadingBolt.js
  app/components/withLoading/withLoading.js
  app/containers/App.js
  app/containers/Root.js
  app/containers/Syncing.js
  app/reducers/utils.js
Labels: scope: wallet, type: bug, type: enhancement

#1593 refactor(channels): remove old network sidebar
  app/components/App/App.js
  app/components/Settings/Fiat/Fiat.js
  app/components/Settings/Locale/Locale.js
  app/components/Settings/Menu/Menu.js
  app/components/Settings/Settings.js
  app/components/Settings/Theme/Theme.js
  app/components/UI/Dropdown.js
  app/containers/App.js
  app/main.js
Labels: scope: channels, type: refactor

#1594 fix(wallet): ensure currency unit is saved on change
  app/reducers/ticker.js
Labels: scope: wallet, type: bug

#1576 feat(ui): add close channel dialog
  app/components/Channels/ChannelCloseDialog.js
  app/components/Channels/index.js
  app/components/Channels/messages.js
  app/components/Form/Form.js
  app/components/Home/DeleteWalletDialog.js
  app/components/UI/DialogOverlay.js
  app/components/UI/index.js
  app/components/Util/hooks/closeOnUnmount.js
  app/components/Util/hooks/index.js
  app/containers/Channels.js
  app/containers/Channels/ChannelCloseDialog.js
  app/reducers/channels.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: scope: channels, scope: wallet, type: feature

#1601 fix(ui): incorrect fiat to satoshi conversion
  app/components/UI/CryptoAmountInput.js
Labels: scope: wallet, type: bug

#1558 build: change product name from ZapDesktop to Zap
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .storybook/config.js
  TROUBLESHOOTING.md
  internals/scripts/lnd-release/README.md
  package.json
  stories/_general/_welcome.stories.js
Labels: scope: devops, type: chore

#1599 refactor(ui): multi-level modals
  app/components/App/App.js
  app/components/Channels/ChannelCardList.js
  app/components/Channels/ChannelCardListItem.js
  app/components/Channels/ChannelCloseDialog.js
  app/components/Channels/ChannelCreateForm.js
  app/components/Channels/ChannelDetail.js
  app/components/Channels/ChannelFooter.js
  app/components/Channels/ChannelList.js
  app/components/Channels/ChannelSummaryList.js
  app/components/Channels/ChannelSummaryListItem.js
  app/components/Channels/Channels.js
  app/components/Channels/ChannelsActions.js
  app/components/Channels/ChannelsHeader.js
  app/components/Channels/index.js
  app/components/Form/Form.js
  app/components/Form/index.js
  app/components/Onboarding/Steps/ConnectionDetails.js
  app/components/Onboarding/Steps/ConnectionDetailsTabs.js
  app/components/Settings/Menu/Menu.js
  app/components/Settings/Settings.js
  app/components/UI/Modal.js
  app/components/Wallet/Wallet.js
  app/containers/App.js
  app/containers/Channels.js
  app/containers/Channels/ChannelCreate.js
  app/containers/Channels/ChannelDetail.js
  app/containers/Modal.js
  app/containers/Root.js
  app/containers/Settings.js
  app/containers/Wallet.js
  app/lib/utils/genId.js
  app/reducers/form.js
  app/reducers/index.js
  app/reducers/modal.js
  app/reducers/notification.js
  app/reducers/pay.js
  app/reducers/payment.js
  app/reducers/transaction.js
  test/unit/components/Form.spec.js
  test/unit/components/UI/__snapshots__/Modal.spec.js.snap
  test/unit/reducers/__snapshots__/form.spec.js.snap
  test/unit/reducers/form.spec.js
Labels: scope: channels, scope: ui/ux, type: refactor

#1602 chore(version): bump version to v0.3.5-beta
  app/package.json
  package.json
Labels: type: chore

#1603 Update contributors list in README
  README.md
Labels: scope: documentation, type: chore

#1604 chore(devops): run deploy jobs on next branch
  .travis.yml
  appveyor.yml
Labels: scope: devops, type: chore

#1597 fix(ui): ensure amount input group has required flag
  app/components/Contacts/SubmitChannelForm/SubmitChannelForm.js
  app/components/Pay/Pay.js
  app/components/Request/Request.js
  app/components/UI/CurrencyFieldGroup.js
  app/components/UI/Input.js
Labels: type: bug

#1605 fix(ui): improve loading screen messages
  app/components/LoadingBolt/LoadingBolt.js
  app/components/LoadingBolt/messages.js
  app/components/withLoading/withLoading.js
  app/containers/Root.js
  app/lib/zap/controller.js
  app/reducers/ipc.js
  app/reducers/lnd.js
  app/reducers/utils.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  test/unit/components/LoadingBolt.spec.js
Labels: type: enhancement

#1595 fix(wallet): resolve broken link in help menu
  app/lib/zap/menuBuilder.js
Labels: type: bug

#1598 feat(channels): set fee rate when opening channel
  app/components/Channels/ChannelCreateForm.js
  app/components/Channels/constants.js
  app/components/Channels/messages.js
  app/components/UI/RadioGroup.js
  app/containers/Channels/ChannelCreateForm.js
  app/lib/lnd/methods/channelController.js
  app/reducers/channels.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  stories/forms/form.stories.js
Labels: scope: channels, type: feature

#1608 refactor: remove unused code
  app/components/Channels/ChannelFooter.js
Labels: type: refactor

#1609 feat(ui): modal system enhancement
  app/components/UI/Modal.js
  app/components/UI/index.js
  app/components/Util/hooks/index.js
  app/components/Util/hooks/useOnKeydown.js
  app/containers/ModalStack.js
  app/containers/Onboarding.js
  app/containers/Root.js
  app/containers/Syncing.js
  test/unit/components/UI/__snapshots__/Modal.spec.js.snap
Labels: scope: ui/ux, type: enhancement

#1612 fix(ui): ensure notifications don't cover modal close button
  app/components/GlobalNotification/GlobalNotification.js
Labels: type: bug

#1613 perf(ui): improve channel list rendering
  app/components/Channels/ChannelCardListItem.js
  app/components/Channels/ChannelSummaryListItem.js
Labels: scope: performance

#1616 fix(ui): node and activity modals overhaul
  app/components/Activity/ActivityModal/ActivityModal.js
  app/components/App/App.js
  app/components/Wallet/ReceiveModal/ReceiveModal.js
  app/containers/App.js
  app/containers/ModalStack.js
  app/containers/Wallet/ReceiveModal.js
  app/reducers/activity.js
  app/reducers/address.js
Labels: scope: wallet, type: bug, type: refactor

#1618 fix(ui): make incoming/outgoing transaction more obvious
  app/components/Activity/Invoice/Invoice.js
  app/components/Activity/Payment/Payment.js
  app/components/Activity/Transaction/Transaction.js
Labels: scope: ui/ux, scope: wallet, type: bug

#1623 fix(ui): disable pointer events on fade
  app/components/LoadingBolt/LoadingBolt.js
  app/containers/ModalStack.js
Labels: scope: ui/ux, type: bug

#1621 feat(channels): private channel toggle
  app/components/Channels/ChannelCreateForm.js
  app/components/Channels/messages.js
  app/components/Icon/Padlock.js
  app/components/UI/Toggle.js
  app/containers/Channels/ChannelCreateForm.js
  app/icons/padlock.svg
  app/reducers/channels.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  stories/icons/icon.stories.js
  test/unit/components/UI/__snapshots__/Toggle.spec.js.snap
Labels: scope: channels, type: feature

#1622 feat(channels): show notification when opening channel
  app/components/Channels/ChannelCreateForm.js
  app/components/Channels/messages.js
  app/containers/Channels/ChannelCreateForm.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: scope: channels, type: feature

#1634 fix(lnd): show sync screen as early as possible
  app/lib/lnd/neutrino.js
  app/reducers/utils.js
  test/e2e/utils/helpers.js
Labels: scope: lnd, scope: sync, type: bug

#1635 fix(lnd): defer fetching data until sync complete
  app/components/App/App.js
  app/containers/App.js
  app/reducers/activity.js
  app/reducers/lnd.js
Labels: scope: lnd, scope: sync, type: bug

#1617 feat(channels): suggested nodes on channel form
  app/components/Channels/ChannelCreate.js
  app/components/Channels/ChannelCreateForm.js
  app/components/Channels/ChannelNodeSearch.js
  app/components/Channels/NodeCardList.js
  app/components/Channels/NodeCardView.js
  app/components/Channels/index.js
  app/components/Channels/messages.js
  app/containers/Channels/NodeCardList.js
  app/containers/ModalStack.js
  app/lib/utils/api.js
  app/reducers/channels.js
  app/reducers/contactsform.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  internals/webpack/webpack.config.renderer.dev.js
  internals/webpack/webpack.config.renderer.prod.js
  stories/containers/channels/node-card-list.stories.js
  stories/containers/channels/node-card-view.stories.js
Labels: scope: channels, type: feature

#1639 perf(ui): use persistent tabs in channel management
  app/components/Channels/Channels.js
  app/components/TabControl/PersistentTabControl.js
  app/components/TabControl/Tab.js
Labels: scope: channels, scope: performance

#1620 feat(ui): add ability to edit host cert and macaroon
  app/components/Home/Home.js
  app/components/Home/WalletLauncher.js
  app/components/Home/WalletSettingsFormRemote.js
  app/components/Home/messages.js
  app/components/Onboarding/Steps/messages.js
  app/components/UI/OpenDialogButton.js
  app/components/UI/OpenDialogInput.js
  app/components/UI/RowLabel.js
  app/components/UI/index.js
  app/containers/Home.js
  app/lib/utils/index.js
  app/lib/utils/isBase64url.js
  app/lib/zap/controller.js
  app/reducers/lnd.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
Labels: scope: ui/ux, scope: wallet, type: feature

#1642 refactor: remove unused code
  app/components/Contacts/AddChannel/AddChannel.js
  app/components/Contacts/AddChannel/index.js
  app/components/Contacts/AddChannel/messages.js
  app/components/Contacts/ChannelForm/ChannelForm.js
  app/components/Contacts/ChannelForm/index.js
  app/components/Contacts/ConnectManually/ConnectManually.js
  app/components/Contacts/ConnectManually/index.js
  app/components/Contacts/ConnectManually/messages.js
  app/components/Contacts/Network/BrowseChannelButton.js
  app/components/Contacts/Network/ChannelDetails.js
  app/components/Contacts/Network/ChannelItem.js
  app/components/Contacts/Network/ChannelLimits.js
  app/components/Contacts/Network/ChannelPubkey.js
  app/components/Contacts/Network/CloseChannel.js
  app/components/Contacts/Network/ClosingChannel.js
  app/components/Contacts/Network/Header.js
  app/components/Contacts/Network/LoadingChannels.js
  app/components/Contacts/Network/Network.js
  app/components/Contacts/Network/NetworkActionBar.js
  app/components/Contacts/Network/NetworkBalance.js
  app/components/Contacts/Network/SearchBar.js
  app/components/Contacts/Network/index.js
  app/components/Contacts/Network/messages.js
  app/components/Contacts/SubmitChannelForm/SubmitChannelForm.js
  app/components/Contacts/SubmitChannelForm/index.js
  app/components/Contacts/SubmitChannelForm/messages.js
  app/components/Contacts/SuggestedNodes/SuggestedNodes.js
  app/components/Contacts/SuggestedNodes/index.js
  app/components/Contacts/SuggestedNodes/messages.js
  app/containers/Contacts/ConnectManually.js
  app/containers/Contacts/SubmitChannelForm.js
  app/containers/Contacts/SuggestedNodes.js
  app/lib/lnd/methods/index.js
  app/reducers/contactsform.js
  app/reducers/ipc.js
  app/reducers/network.js
  stories/containers/contacts.stories.js
  stories/containers/network.stories.js
  stories/containers/network/suggested-nodes.stories.js
Labels: scope: channels, type: refactor

#1651 perf(ui): use react virtualized in channels management screen
  app/components/Channels/ChannelCapacity.js
  app/components/Channels/ChannelCardList.js
  app/components/Channels/ChannelSummaryList.js
  app/components/Channels/Channels.js
  app/components/TabControl/PersistentTabControl.js
Labels: scope: channels, scope: performance, scope: ui/ux

#1658 fix(ui): prevent breaking channel status text in 2 lines
  app/components/Channels/ChannelStatus.js
Labels: scope: channels, type: bug

#1653 fix(channels): display wallet balance on create form
  app/components/Channels/ChannelCreateForm.js
  app/containers/Channels/ChannelCreateForm.js
Labels: scope: channels, type: bug

#1660 fix(ui): disable launch button when opening wallet
  app/components/Home/WalletLauncher.js
Labels: scope: wallet, type: bug

#1661 style(neutrino.js): spelling fixes
  app/lib/lnd/neutrino.js
Labels: type: chore

#1643 feat(channels): channel create form summary
  app/components/Channels/ChannelCreateForm.js
  app/components/Channels/ChannelCreateSummary.js
  app/components/Channels/index.js
  app/components/Channels/messages.js
  app/containers/Channels/ChannelCreateForm.js
  app/lib/utils/btc.js
  app/reducers/channels.js
  app/reducers/contactsform.js
  app/reducers/network.js
  app/translations/af-ZA.json
  app/translations/ar-SA.json
  app/translations/bg-BG.json
  app/translations/ca-ES.json
  app/translations/cs-CZ.json
  app/translations/da-DK.json
  app/translations/de-DE.json
  app/translations/el-GR.json
  app/translations/en.json
  app/translations/es-ES.json
  app/translations/fi-FI.json
  app/translations/fr-FR.json
  app/translations/ga-IE.json
  app/translations/he-IL.json
  app/translations/hi-IN.json
  app/translations/hr-HR.json
  app/translations/hu-HU.json
  app/translations/it-IT.json
  app/translations/ja-JP.json
  app/translations/ko-KR.json
  app/translations/nl-NL.json
  app/translations/no-NO.json
  app/translations/pl-PL.json
  app/translations/pt-BR.json
  app/translations/pt-PT.json
  app/translations/ro-RO.json
  app/translations/ru-RU.json
  app/translations/sr-SP.json
  app/translations/sv-SE.json
  app/translations/tr-TR.json
  app/translations/uk-UA.json
  app/translations/vi-VN.json
  app/translations/zh-CN.json
  app/translations/zh-TW.json
  stories/containers/channels/channel-create-summary.stories.js
Labels: scope: channels, type: feature

#1636 fix(lnd): update btcd & lnd and trigger a resync for local wallets.
  app/containers/Root.js
  app/lib/lnd/config.js
  app/lib/lnd/neutrino.js
  app/lib/utils/localWallets.js
  app/lib/zap/migrations/purge-local-wallets.js
  app/lib/zap/migrator.js
  app/main.js
  app/preload.js
  app/reducers/wallet.js
  config/default.js
  config/development.js
  config/production.js
  config/storybook.js
  config/test.js
  package.json
  test/unit/__helpers__/setup.js
  yarn.lock
Labels: type: enhancement, type: refactor

#1667 fix(ui): prevent long name break in channel search
  app/components/Channels/ChannelNodeSearch.js
Labels: scope: channels, type: bug

#1668 fix(ui): make channel search results header more informative
  app/components/Channels/ChannelNodeSearch.js
  app/components/Channels/messages.js
  app/translations/en.json
Labels: scope: channels, type: enhancement
