Repository LN-Zap/zap-desktop, pull requests merged in 2019-07, with the labels that each got.

#2528 fix(ui): ensure active wallet is set early
  renderer/reducers/lnd.js
Labels: scope: ui/ux, type: bug 🐛

#2530 fix(deps): update lnd to v0.7.0-beta-rc3-1-gf366eed4
  package.json
Labels: type: chore

#2536 fix(ui): ensure sidebar/main sizes respected
  renderer/components/UI/MainContent.js
  renderer/components/UI/Modal.js
  renderer/components/UI/Sidebar.js
  test/unit/components/UI/__snapshots__/MainContent.spec.js.snap
  test/unit/components/UI/__snapshots__/Modal.spec.js.snap
  test/unit/components/UI/__snapshots__/Sidebar.spec.js.snap
Labels: scope: ui/ux, type: bug 🐛

#2529 feat(ui): implement wallet creation error handling
  renderer/components/Onboarding/Onboarding.js
  renderer/components/Onboarding/Steps/ConnectionConfirm.js
  renderer/components/Onboarding/Steps/WalletCreate.js
  renderer/components/Onboarding/Steps/WalletRecover.js
  renderer/components/Onboarding/Steps/components/ErrorDialog.js
  renderer/components/Onboarding/Steps/components/messages.js
  renderer/components/Onboarding/Steps/messages.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: onboarding, scope: ui/ux

#2546 refactor: remove unused state entries
  renderer/reducers/channels.js
  renderer/reducers/invoice.js
  renderer/reducers/neutrino.js
  renderer/reducers/onboarding.js
  renderer/reducers/peers.js
  test/unit/reducers/__snapshots__/channels.spec.js.snap
  test/unit/reducers/__snapshots__/invoice.spec.js.snap
  test/unit/reducers/__snapshots__/peers.spec.js.snap
  test/unit/reducers/invoice.spec.js
Labels: type: refactor

#2540 fix(i18n): ensure translation files are available
  package.json
Labels: scope: i18n, type: bug 🐛

#2513 refactor: use immer in network and payment reducers
  package.json
  renderer/reducers/network.js
  renderer/reducers/payment.js
  renderer/reducers/utils/createReducer.js
  yarn.lock
Labels: type: refactor

#2538 fix(grpc): forward grpc options to getInfo
  package.json
  services/grpc/lightning.methods.js
  utils/promisifiedCall.js
  yarn.lock
Labels: type: bug 🐛

#2555 chore(deps): remove unused concurrently dependency
  package.json
  yarn.lock
Labels: dependencies, type: chore

#2564 fix(ui): display correct invoice expire time
  renderer/components/Request/RequestSummary.js
Labels: scope: ui/ux, type: bug 🐛

#2572 fix(backups): do not throw skip backup error
  renderer/reducers/backup.js
Labels: backups, type: bug 🐛

#2575 fix(wallet): fix LN fee estimates and add 1 sat buffer to fee limits
  renderer/reducers/pay.js
  utils/crypto.js
Labels: scope: wallet, type: bug 🐛

#2557 fix(wallet): improve handling of invalid invoices
  package.json
  renderer/components/UI/CryptoAmountInput.js
  renderer/components/UI/CurrencyFieldGroup.js
  renderer/components/UI/FiatAmountInput.js
  renderer/components/UI/LightningInvoiceInput.js
  renderer/hocs/index.js
  renderer/hocs/withInputValidation.js
  renderer/hocs/withNumberValidation.js
  test/e2e/basic-ui.spec..js
  yarn.lock
Labels: scope: wallet, type: bug 🐛

#2577 fix(wallet): update suggested-peers api uri
  config/default.js
  renderer/reducers/channels.js
  test/unit/reducers/__snapshots__/channels.spec.js.snap
  utils/api.js
  webpack/dev/common/devserver.js
  webpack/dev/renderer.config.js
  webpack/prod/renderer.config.js
Labels: scope: wallet, type: refactor

#2550 refactor: use immer in a number of reducers
  renderer/reducers/activity.js
  renderer/reducers/address.js
  renderer/reducers/app.js
  renderer/reducers/balance.js
  renderer/reducers/info.js
  renderer/reducers/notification.js
  renderer/reducers/pay.js
  test/unit/reducers/__snapshots__/address.spec.js.snap
  test/unit/reducers/address.spec.js
Labels: type: refactor

#2570 fix(deps): update all lodash variants to 4.17.14
  package.json
  yarn.lock
Labels: dependencies, scope: security

#2587 test(e2e): update lnd node credentials
  test/e2e/basic-ui.spec..js
  test/e2e/fixtures/readonly.macaroon
  test/e2e/fixtures/tls.cert
  test/e2e/onboarding-connect-btcpay.spec.js
  test/e2e/onboarding-connect-lndconnect.spec.js
Labels: scope: tests

#2579 refactor: continue immer migration
  renderer/reducers/autopilot.js
  renderer/reducers/backup.js
  renderer/reducers/channels.js
  renderer/reducers/contactsform.js
  renderer/reducers/invoice.js
  renderer/reducers/lnd.js
  renderer/reducers/utils/createReducer.js
Labels: type: refactor

#2588 refactor: finish immer migration
  renderer/reducers/modal.js
  renderer/reducers/neutrino.js
  renderer/reducers/onboarding.js
  renderer/reducers/peers.js
  renderer/reducers/settings.js
  renderer/reducers/settingsmenu.js
  renderer/reducers/theme.js
  renderer/reducers/ticker.js
  renderer/reducers/transaction.js
  renderer/reducers/utils/createReducer.js
  renderer/reducers/wallet.js
Labels: type: refactor

#2595 test(e2e): update testnet4 lnd credentials
  test/e2e/fixtures/readonly.macaroon
  test/e2e/fixtures/tls.cert
  test/e2e/onboarding-connect-btcpay.spec.js
  test/e2e/onboarding-connect-lndconnect.spec.js
Labels: scope: tests

#2585 fix(ui): display correct channel count when search or filter is applied
  renderer/components/Channels/ChannelCount.js
  renderer/components/Channels/ChannelSearch.js
  renderer/components/Channels/Channels.js
  renderer/components/Channels/ChannelsActions.js
  renderer/components/Channels/ChannelsHeader.js
  renderer/components/Channels/messages.js
  stories/containers/channels/channel-count.stories.js
  stories/containers/channels/channels-header.stories.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: status: needs rebase, type: bug 🐛

#2582 fix: use correct crypto unit names based on network
  renderer/components/UI/CurrencyFieldGroup.js
  renderer/components/UI/Dropdown.js
  renderer/containers/UI/CryptoSelector.js
  renderer/reducers/ticker.js
Labels: type: bug 🐛

#2584 feat(ui): implement activity item error dialog
  renderer/components/Activity/Activity.js
  renderer/components/Activity/ErrorDetailsDialog.js
  renderer/components/Activity/ErrorLink.js
  renderer/components/Activity/Payment/Payment.js
  renderer/components/Activity/Payment/messages.js
  renderer/components/Activity/Transaction/Transaction.js
  renderer/components/Activity/messages.js
  renderer/components/UI/DialogOverlay.js
  renderer/containers/Activity/Activity.js
  renderer/containers/Activity/Invoice.js
  renderer/containers/Activity/Payment.js
  renderer/containers/Activity/Transaction.js
  renderer/reducers/activity.js
  test/unit/reducers/__snapshots__/activity.spec.js.snap
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: enhancement

#2610 perf: simplify activity list renderer
  renderer/components/Activity/Activity.js
Labels: scope: performance

#2613 fix(lnd): increase autopilot minconfs to 1
  config/default.js
  stories/containers/home.stories.js
Labels: scope: lnd, type: bug 🐛

#2614 fix(i18n): add intl support to request expiry label
  renderer/components/Request/RequestSummary.js
  renderer/components/Request/messages.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: bug 🐛

#2623 fix(lnd): update lnd to 0.7.1-beta-rc2-3-g3d84693a
  package.json
  scripts/lnd-release/.goreleaser.yml
  services/neutrino/neutrino.js
  yarn.lock
Labels: scope: lnd

#2625 fix(ui): unknown recipient when sending ln payment
  renderer/reducers/payment.js
Labels: type: bug 🐛

#2624 fix(ui): ensure fiat and crypto inputs in agroup are always updated
  renderer/components/UI/CurrencyFieldGroup.js
Labels: type: bug 🐛

#2645 build: remove .deb linux target
  README.md
  package.json
Labels: scope: devops

#2611 refactor(utils): implement secureStorage util
  .travis.yml
  package.json
  test/unit/__mocks__/keytar.js
  test/unit/utils/secureStorage.spec.js
  utils/secureStorage.js
  webpack/dev/main.config.js
  webpack/prod/main.config.js
  webpack/webpack.config.dll.js
  yarn.lock
Labels: scope: security, type: refactor

#2583 fix(ui): show last on-chain updating tx in channels card view
  renderer/components/Channels/ChannelData.js
Labels: status: needs rebase, type: enhancement

#2662 fix(ui): improve channel list hamburger icon
  icons/layout-list.svg
  renderer/components/Icon/LayoutList.js
Labels: scope: ui/ux, type: bug 🐛

#2661 docs: add documentation for configuration options
  docs/ADVANCED.md
  docs/CONFIG.md
Labels: scope: documentation

#2664 fix(ui): remove gaps in pay/request form help text
  renderer/components/Pay/Pay.js
  renderer/components/Request/Request.js
Labels: scope: ui/ux, type: bug 🐛

#2665 docs: update contributors list
  README.md
Labels: scope: documentation

#2658 fix(deps): update lnd to v0.7.1-beta-3-g26af2265
  appveyor.yml
  package.json
Labels: scope: lnd

#2666 docs: add documentation index into main README
  README.md
Labels: scope: documentation

#2667 refactor: remove unused 386 lnd build targets
  scripts/lnd-release/.goreleaser.yml
Labels: scope: devops

#2669 fix(app): ensure autoupdate setting is honoured
  electron/updater.js
Labels: type: bug 🐛

#2671 fix(ui): disable delete wallet button in launching state
  renderer/components/Home/WalletLauncher.js
Labels: type: bug 🐛, type: enhancement
