Repository LN-Zap/zap-desktop, pull requests merged in 2019-08, with the labels that each got.

#2675 style(lint): fix lint issues
  electron/about/index.js
  electron/about/public/renderer.js
  electron/menuBuilder.js
  i18n/locale.js
  renderer/components/TabControl/PersistentTabControl.js
  renderer/components/UI/Wizard.js
  renderer/containers/Onboarding/Onboarding.js
  renderer/hooks/usePrevious.js
  test/unit/__helpers__/intl-enzyme-test-helper.js
Labels: type: chore

#2683 refactor: clean up dexie code
  renderer/reducers/address.js
  renderer/store/db.js
  renderer/store/dbVersions.js
  renderer/store/schema/node.js
  renderer/store/schema/setting.js
  renderer/store/schema/wallet.js
Labels: type: refactor

#2682 refactor: proxymise grpc calls
  renderer/reducers/address.js
  renderer/reducers/autopilot.js
  renderer/reducers/backup.js
  renderer/reducers/balance.js
  renderer/reducers/channels.js
  renderer/reducers/info.js
  renderer/reducers/invoice.js
  renderer/reducers/lnd.js
  renderer/reducers/network.js
  renderer/reducers/neutrino.js
  renderer/reducers/pay.js
  renderer/reducers/payment.js
  renderer/reducers/peers.js
  renderer/reducers/transaction.js
  renderer/workers/index.js
  renderer/workers/proxymise.js
  test/unit/__helpers__/setup.js
  utils/fee.js
Labels: scope: lnd, type: refactor

#2686 fix(ui): increment satoshi amount using up arrow
  renderer/components/UI/CryptoAmountInput.js
Labels: scope: ui/ux, type: bug 🐛

#2687 feat(ui): close dialogs with Escape key
  renderer/components/Activity/ErrorDetailsDialog.js
  renderer/components/Autopay/AutopayCreateModal.js
  renderer/components/Channels/ChannelCloseDialog.js
  renderer/components/Home/DeleteWalletDialog.js
  renderer/components/Onboarding/Steps/components/SkipBackupsDialog.js
  renderer/components/UI/Dialog.js
  renderer/hooks/useCloseOnUnmount.js
Labels: scope: ui/ux, type: enhancement

#2689 fix(ui): lighten shadows in light theme
  renderer/components/UI/Card.js
  renderer/components/UI/Dialog.js
  renderer/components/UI/Dropdown.js
  renderer/components/UI/GlobalStyle.js
  renderer/components/UI/Notification.js
  renderer/components/UI/Page.js
  renderer/components/UI/Select.js
  renderer/components/UI/Sidebar.js
  renderer/components/UI/Toggle.js
  renderer/components/UI/Tooltip.js
  renderer/themes/base.js
  renderer/themes/dark/index.js
  renderer/themes/light/index.js
  renderer/themes/light/shadows.js
  renderer/themes/util.js
  stories/_general/color.stories.js
  test/unit/components/UI/__snapshots__/Card.spec.js.snap
  test/unit/components/UI/__snapshots__/Dialog.spec.js.snap
  test/unit/components/UI/__snapshots__/Modal.spec.js.snap
  test/unit/components/UI/__snapshots__/Notification.spec.js.snap
  test/unit/components/UI/__snapshots__/Page.spec.js.snap
  test/unit/components/UI/__snapshots__/Sidebar.spec.js.snap
  test/unit/components/UI/__snapshots__/Toggle.spec.js.snap
Labels: scope: ui/ux, type: bug 🐛

#2696 feat: add ability to sign and verify messages
  renderer/components/Profile/ProfileMenu/ProfileMenu.js
  renderer/components/Profile/ProfileMenu/messages.js
  renderer/components/Profile/ProfilePage/ProfilePage.js
  renderer/components/Profile/ProfilePaneSignMessage/ProfilePaneSignMessage.js
  renderer/components/Profile/ProfilePaneSignMessage/index.js
  renderer/components/Profile/ProfilePaneSignMessage/messages.js
  renderer/components/Profile/ProfilePaneVerifyMessage/ProfilePaneVerifyMessage.js
  renderer/components/Profile/ProfilePaneVerifyMessage/index.js
  renderer/components/Profile/ProfilePaneVerifyMessage/messages.js
  renderer/components/Profile/constants.js
  renderer/components/UI/LightningInvoiceInput.js
  renderer/containers/Profile/ProfilePaneSignMessage.js
  renderer/containers/Profile/ProfilePaneVerifyMessage.js
  renderer/reducers/lnd.js
  test/unit/components/UI/__snapshots__/LightningInvoiceInput.spec.js.snap
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: wallet, type: feature

#2706 fix: ensure timeout is cleared asap in promiseTimeout
  utils/promiseTimeout.js
Labels: type: bug 🐛

#2537 fix(grpc): add connection timeout
  package.json
  yarn.lock
Labels: type: bug 🐛

#2711 fix(ui): correct select widget title position
  renderer/components/UI/Input.js
  renderer/components/UI/InputLabel.js
  renderer/components/UI/RadioGroup.js
  renderer/components/UI/Select.js
  renderer/components/UI/TextArea.js
  renderer/components/UI/index.js
  stories/forms/form.stories.js
Labels: scope: ui/ux, type: bug 🐛

#2716 fix(wallet): properly validate msat invoices
  renderer/components/UI/LightningInvoiceInput.js
Labels: scope: wallet, type: bug 🐛

#2717 docs: document build commands
  docs/ADVANCED.md
Labels: scope: documentation

#2722 feat(ui): show memo in outgoing LN payment summary
  renderer/components/Activity/PaymentModal/PaymentModal.js
  utils/crypto.js
Labels: type: enhancement

#2728 fix(app): disable app downgrade feature
  electron/updater.js
Labels: type: bug 🐛

#2738 fix(ui): add support for intl in reducers
  i18n/index.js
  i18n/intl.js
  renderer/reducers/address.js
  renderer/reducers/backup.js
  renderer/reducers/channels.js
  renderer/reducers/locale.js
  renderer/reducers/messages.js
  renderer/reducers/payment.js
  renderer/reducers/settings.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: bug 🐛, type: enhancement, type: refactor

#2741 fix: extract-messages issue introduced by 7b6a796
  renderer/reducers/messages/index.js
  renderer/reducers/messages/messages.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: devops

#2734 refactor: consolidate and clean up Input components
  renderer/components/Autopay/Autopay.js
  renderer/components/Form/Form.js
  renderer/components/Form/Input.js
  renderer/components/Form/TextArea.js
  renderer/components/Form/util.js
  renderer/themes/dark/index.js
  renderer/themes/light/index.js
  renderer/themes/util/createThemeVariant.js
  renderer/themes/util/extractSpaceProps.js
  renderer/themes/util/index.js
  test/unit/components/Form/__snapshots__/Form.spec.js.snap
  test/unit/components/Form/__snapshots__/Input.spec.js.snap
  test/unit/components/Form/__snapshots__/LightningInvoiceInput.spec.js.snap
  test/unit/components/Form/__snapshots__/NodePubkeyInput.spec.js.snap
  test/unit/components/Form/__snapshots__/Radio.spec.js.snap
  test/unit/components/Form/__snapshots__/Select.spec.js.snap
  test/unit/components/Form/__snapshots__/TextArea.spec.js.snap
Labels: type: refactor

#2742 fix(i18n): add missing memo translation
  renderer/components/Activity/PaymentModal/messages.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: bug 🐛

#2743 fix(ui): align amount and crypto unit
  renderer/components/Pay/PaySummaryLightning.js
  test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
Labels: type: bug 🐛

#2735 fix(autopay): correctly apply blue theme overrides
  renderer/components/Autopay/Autopay.js
Labels: scope: autopay, type: bug 🐛

#2751 fix(onboarding): show recover wallet passphrase form
  package.json
  renderer/components/Onboarding/Steps/WalletRecover.js
  services/grpc/grpc.js
  utils/promiseTimeout.js
  yarn.lock
Labels: type: bug 🐛

#2749 feat(ui): implement unexpected error UI
  renderer/components/App/AppErrorBoundary.js
  renderer/components/Dialog/AppCrashed.js
  renderer/components/Dialog/messages.js
  renderer/containers/App.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: ui/ux, type: enhancement, type: feature

#2754 [WIP] feat(ui): prefill gh uncaught error issues
  electron/preload.js
  package.json
  renderer/components/App/AppErrorBoundary.js
  renderer/components/Dialog/AppCrashed.js
  renderer/components/Dialog/messages.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
  utils/github.js
  yarn.lock
Labels: type: enhancement, type: feature

#2758 fix: add more error boundaries
  electron/preload.js
  renderer/components/App/AppErrorBoundary.js
  renderer/components/Dialog/AppCrashed.js
  renderer/components/ErrorBoundary/AppErrorBoundary.js
  renderer/containers/App/App.js
  renderer/containers/App/ErrorBoundary.js
  renderer/containers/App/index.js
  renderer/containers/Home/Home.js
  renderer/containers/Home/index.js
  renderer/containers/Onboarding/Onboarding.js
  renderer/containers/Root.js
  renderer/containers/Syncing.js
  renderer/containers/Wallet/Wallet.js
  renderer/containers/Wallet/WalletStarter.js
  renderer/containers/Wallet/index.js
  utils/github.js
Labels: type: enhancement

#2736 feat(ui): add "show/hide password" buttons
  icons/eye-off.svg
  renderer/components/Form/PasswordInput.js
  renderer/components/Form/index.js
  renderer/components/Home/WalletUnlocker.js
  renderer/components/Icon/EyeOff.js
  renderer/components/Onboarding/Steps/Login.js
  renderer/components/Onboarding/Steps/Password.js
  renderer/components/Onboarding/Steps/WalletRecover.js
  test/e2e/onboarding-create.spec.js
  test/e2e/pages/onboarding.js
  test/unit/components/Form/PasswordInput.spec.js
  test/unit/components/Form/__snapshots__/PasswordInput.spec.js.snap
Labels: scope: onboarding, type: feature

#2768 refactor: simplify streamify util
  services/grpc/lightning.subscriptions.js
  utils/streamify.js
Labels: type: refactor

#2770 build: add checksum signing script and docs
  README.md
  docs/RELEASING.md
  docs/SIGNATURES.md
  scripts/signedchecksum.sh
Labels: scope: devops, scope: documentation

#2697 feat(ui): add ability to specify fallback address in LN invoices
  config/default.js
  renderer/components/Request/Request.js
  renderer/components/Request/RequestSummary.js
  renderer/components/Request/messages.js
  renderer/components/Settings/SettingsFieldsWallet.js
  renderer/components/Settings/messages.js
  renderer/containers/Request.js
  renderer/reducers/address.js
  renderer/reducers/invoice.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: scope: wallet, type: enhancement

#2767 fix(ui): form input name and autofocus
  renderer/components/Form/CurrencyFieldGroup.js
  renderer/components/Form/Input.js
  renderer/components/Form/TextArea.js
  renderer/components/Request/Request.js
  renderer/containers/ModalStack.js
  renderer/hooks/index.js
  renderer/hooks/useAutoFocus.js
  stories/forms/form.stories.js
  test/unit/components/Form/__snapshots__/Input.spec.js.snap
  test/unit/components/Form/__snapshots__/NodePubkeyInput.spec.js.snap
  test/unit/components/Form/__snapshots__/Select.spec.js.snap
  test/unit/components/Form/__snapshots__/TextArea.spec.js.snap
Labels: type: refactor

#2720 feat(wallet): add ability to export on-chain tx invoices
  electron/main.js
  electron/pdfGenerator/invoice.js
  electron/pdfGenerator/service.js
  package.json
  renderer/components/Activity/ActivityModal/ActivityModal.js
  renderer/components/Activity/TransactionModal/TransactionModal.js
  renderer/components/Activity/TransactionModal/messages.js
  renderer/components/UI/Button.js
  renderer/containers/Activity/ActivityModal.js
  renderer/reducers/activity.js
  renderer/reducers/ipc.js
  renderer/reducers/messages/messages.js
  stories/components/button.stories.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
  yarn.lock
Labels: type: feature

#2688 refactor(pay-form): decompose into smaller components
  renderer/components/Pay/Pay.js
  renderer/components/Pay/PayAddressField.js
  renderer/components/Pay/PayAmountFields.js
  renderer/components/Pay/PayHeader.js
  renderer/components/Pay/PayHelpText.js
  renderer/components/Pay/PayPanelBody.js
  renderer/components/Pay/PayPanelFooter.js
  renderer/components/Pay/PayPanelHeader.js
  renderer/components/Pay/PaySummary.js
  renderer/components/Pay/constants.js
  renderer/components/Pay/index.js
  renderer/components/Pay/messages.js
  renderer/components/Pay/utils.js
  test/e2e/basic-ui.spec..js
  test/e2e/pages/wallet.js
  test/unit/components/Pay/PayAddressField.spec.js
  test/unit/components/Pay/PayAmountFields.spec.js
  test/unit/components/Pay/PayHelpText.spec.js
  test/unit/components/Pay/PayPanelBody.spec.js
  test/unit/components/Pay/PayPanelFooter.spec.js
  test/unit/components/Pay/PayPanelHeader.spec.js
  test/unit/components/Pay/PaySummary.spec.js
  test/unit/components/Pay/__snapshots__/PayAddressField.spec.js.snap
  test/unit/components/Pay/__snapshots__/PayAmountFields.spec.js.snap
  test/unit/components/Pay/__snapshots__/PayHelpText.spec.js.snap
  test/unit/components/Pay/__snapshots__/PayPanelBody.spec.js.snap
  test/unit/components/Pay/__snapshots__/PayPanelFooter.spec.js.snap
  test/unit/components/Pay/__snapshots__/PayPanelHeader.spec.js.snap
  test/unit/components/Pay/__snapshots__/PaySummary.spec.js.snap
Labels: type: refactor

#2775 fix: add intl support to notifications
  renderer/reducers/activity.js
  renderer/reducers/app.js
  renderer/reducers/invoice.js
  renderer/reducers/messages/messages.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: enhancement

#2776 fix: update download icon in TransactionModal
  docs/CONTRIBUTING.md
  icons/download.svg
  renderer/components/Activity/TransactionModal/TransactionModal.js
  renderer/components/Icon/Download.js
  scripts/genIcons.js
  scripts/genIconsStory.js
  stories/icons/icon.stories.js
Labels: scope: devops

#2786 build: add all icons list update when generating new icons
  scripts/genIcons.js
  scripts/genIconsStory.js
  stories/AllIcons/AllIcons.stories.js
Labels: scope: devops

#2797 refactor: remove unused svgs
  icons/channels.svg
  icons/contacts.svg
  icons/help-2.svg
  icons/help.svg
  icons/lnd-logo.svg
  icons/orbit.svg
  icons/peers.svg
  icons/wallet-2.svg
  icons/wallet.svg
  renderer/components/Icon/Channels.js
  renderer/components/Icon/Cloudbolt.js
  renderer/components/Icon/Contacts.js
  renderer/components/Icon/Help.js
  renderer/components/Icon/Help2.js
  renderer/components/Icon/LndLogo.js
  renderer/components/Icon/Orbit.js
  renderer/components/Icon/Peers.js
  renderer/components/Icon/Wallet.js
  renderer/components/Icon/Wallet2.js
  renderer/components/Icon/ZapLogoBolt.js
  renderer/components/Onboarding/Steps/ConnectionType.js
  stories/AllIcons/AllIcons.stories.js
  stories/icons/icon.stories.js
Labels: type: refactor

#2798 fix: layout issues
  renderer/components/Profile/ProfilePaneVerifyMessage/ProfilePaneVerifyMessage.js
  renderer/components/UI/Dropmenu.js
Labels: type: bug 🐛

#2796 fix: add intl support to desktop notifications
  renderer/reducers/messages/messages.js
  renderer/reducers/neutrino.js
  renderer/reducers/transaction.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: enhancement

#2795 feat: add LN invoice creation date to summary modal
  renderer/components/Request/RequestSummary.js
  renderer/components/Request/messages.js
  renderer/reducers/invoice.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: bug 🐛, type: enhancement

#2807 refactor: extract form styles to theme
  package.json
  renderer/components/Activity/ActivityActions/ActivitySearch.js
  renderer/components/Autopay/AutopaySearch.js
  renderer/components/Channels/ChannelNodeSearch.js
  renderer/components/Channels/ChannelSearch.js
  renderer/components/Form/CurrencyFieldGroup.js
  renderer/components/Form/Field.js
  renderer/components/Form/Input.js
  renderer/components/Form/InputLabel.js
  renderer/components/Form/Label.js
  renderer/components/Form/LndConnectionStringEditor.js
  renderer/components/Form/LndConnectionStringInput.js
  renderer/components/Form/OpenDialogButton.js
  renderer/components/Form/OpenDialogInput.js
  renderer/components/Form/PasswordInput.js
  renderer/components/Form/Radio.js
  renderer/components/Form/RadioGroup.js
  renderer/components/Form/SearchInput.js
  renderer/components/Form/Select.js
  renderer/components/Form/TextArea.js
  renderer/components/Form/index.js
  renderer/components/Form/util.js
  renderer/components/Home/WalletSettingsFormRemote.js
  renderer/components/Profile/ProfilePaneVerifyMessage/ProfilePaneVerifyMessage.js
  renderer/themes/base.js
  renderer/themes/dark/colors.js
  renderer/themes/light/colors.js
  renderer/themes/util/extractSpaceProps.js
  stories/forms/form.stories.js
  test/unit/components/Form/__snapshots__/Input.spec.js.snap
  test/unit/components/Form/__snapshots__/LightningInvoiceInput.spec.js.snap
  test/unit/components/Form/__snapshots__/NodePubkeyInput.spec.js.snap
  test/unit/components/Form/__snapshots__/PasswordInput.spec.js.snap
  test/unit/components/Form/__snapshots__/Radio.spec.js.snap
  test/unit/components/Form/__snapshots__/Select.spec.js.snap
  test/unit/components/Form/__snapshots__/TextArea.spec.js.snap
  yarn.lock
Labels: type: refactor

#2801 fix: handle uncaught modal React errors
  renderer/components/ModalStack.js
  renderer/containers/App/App.js
  renderer/containers/App/ModalStack.js
  renderer/containers/ModalStack.js
  renderer/containers/Root.js
  renderer/containers/RootModalStack.js
  test/e2e/basic-ui.spec.js
Labels: type: enhancement, type: refactor

#2814 refactor: always import from rebass/styled-components
  renderer/components/Form/Field.js
  renderer/components/Form/OpenDialogInput.js
  renderer/components/Pay/PayPanelFooter.js
  scripts/genIconsStory.js
  stories/AllIcons/AllIcons.stories.js
  test/unit/components/Form/__snapshots__/Input.spec.js.snap
  test/unit/components/Form/__snapshots__/LightningInvoiceInput.spec.js.snap
  test/unit/components/Form/__snapshots__/NodePubkeyInput.spec.js.snap
  test/unit/components/Form/__snapshots__/Select.spec.js.snap
  test/unit/components/Form/__snapshots__/TextArea.spec.js.snap
  test/unit/components/Pay/__snapshots__/PayPanelFooter.spec.js.snap
Labels: type: refactor

#2819 refactor: port various fixes
  renderer/components/Form/Field.js
  renderer/components/Form/Input.js
  renderer/components/Form/InputContainer.js
  renderer/components/Form/TextArea.js
  renderer/components/Form/index.js
  renderer/components/ModalStack.js
  renderer/components/UI/Button.js
  renderer/components/UI/CenteredContent.js
  renderer/containers/App/ModalStack.js
  renderer/containers/RootModalStack.js
  renderer/themes/base.js
  stories/forms/form.stories.js
  test/unit/components/Form/__snapshots__/Input.spec.js.snap
  test/unit/components/Form/__snapshots__/LightningInvoiceInput.spec.js.snap
  test/unit/components/Form/__snapshots__/NodePubkeyInput.spec.js.snap
  test/unit/components/Form/__snapshots__/Select.spec.js.snap
  test/unit/components/Form/__snapshots__/TextArea.spec.js.snap
  test/unit/components/UI/__snapshots__/ActionBar.spec.js.snap
  test/unit/components/UI/__snapshots__/Button.spec.js.snap
Labels: type: refactor

#2811 feat(ui): warn of potential liquidity issues when creating/paying invoices
  renderer/components/Pay/Pay.js
  renderer/components/Pay/PayPanelFooter.js
  renderer/components/Pay/PaySummary.js
  renderer/components/Pay/PaySummaryLightning.js
  renderer/components/Pay/messages.js
  renderer/components/Request/Request.js
  renderer/components/Request/messages.js
  renderer/components/UI/Value.js
  renderer/containers/Pay.js
  renderer/containers/Request.js
  renderer/reducers/channels.js
  test/unit/components/Pay/__snapshots__/PayPanelFooter.spec.js.snap
  test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: status: needs rebase, type: enhancement
