Repository LN-Zap/zap-desktop, pull requests merged in 2019-11, with the labels that each got.

#3088 Add ability to enforce connection only to whitelisted peers
  config/default.js
  renderer/components/Home/WalletLauncher.js
  renderer/components/Home/WalletSettingsFormLocal.js
  renderer/components/Home/messages.js
  renderer/store/schema/wallet.js
  services/neutrino/neutrino.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
  utils/lndConfig.js
Labels: type: enhancement

#3070 Implement lnurl withdrawals
  config/default.js
  electron/lnurl/index.js
  electron/lnurl/service.js
  electron/main.js
  package.json
  renderer/components/App/App.js
  renderer/components/Pay/LnurlWithdrawalPrompt.js
  renderer/components/Pay/index.js
  renderer/components/Pay/messages.js
  renderer/components/Settings/SettingsFieldsSecurity.js
  renderer/components/Settings/messages.js
  renderer/containers/App/App.js
  renderer/containers/Pay/LnurlWithdrawalPrompt.js
  renderer/containers/Settings/SettingsFieldsSecurity.js
  renderer/reducers/invoice.js
  renderer/reducers/ipc.js
  renderer/reducers/pay.js
  stories/dialogs/lnurl-withdrawal-prompt.stories.js
  test/unit/reducers/__snapshots__/pay.spec.js.snap
  test/unit/reducers/pay.spec.js
  test/unit/utils/lnurl.spec.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
  utils/lnurl/index.js
  yarn.lock
Labels: scope: ui/ux, scope: wallet, status: needs rebase

#3087 Fix more eslint6 warnings
  electron/walletBackup/dropbox/db.js
  electron/walletBackup/dropbox/dbApi.js
  electron/walletBackup/dropbox/index.js
  electron/walletBackup/gdrive/gdrive.js
  electron/walletBackup/gdrive/index.js
  renderer/components/Channels/ChannelCreateForm.js
  renderer/components/Form/IntegerInput.js
  renderer/components/Form/LightningInvoiceInput.js
  renderer/components/Form/LndConnectionStringInput.js
  renderer/components/Form/NodePubkeyInput.js
  renderer/components/Home/WalletLauncher.js
  renderer/components/Onboarding/Steps/ConnectionDetailsManual.js
  renderer/components/Pay/Pay.js
  renderer/hocs/withInputValidation.js
  renderer/hocs/withNumberValidation.js
  renderer/hooks/useTimeout.js
  renderer/reducers/autopay.js
  renderer/reducers/backup.js
  renderer/reducers/info.js
  renderer/reducers/onboarding.js
  renderer/store/dbVersions.js
  services/grpc/grpc.js
  stories/components/dialog.stories.js
  test/e2e/pages/wallet.js
  utils/lndConfig.js
Labels: type: refactor

#1890 feat(autopay): auto pay invoices based on autopay config
  electron/main.js
  renderer/reducers/autopay.js
  renderer/reducers/invoice.js
  renderer/reducers/messages/messages.js
  renderer/reducers/neutrino.js
  renderer/reducers/pay.js
  renderer/reducers/transaction.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
  utils/notifications.js
Labels: scope: autopay, type: enhancement

#3114 Update misleading wallet unlock description
  renderer/components/Onboarding/Steps/messages.js
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/en.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hr-HR.json
Labels: scope: i18n, scope: ui/ux, type: enhancement

#3101 Implement more advanced activity and channels filtering
  icons/filter.svg
  renderer/components/Activity/ActivityActions/ActivityActions.js
  renderer/components/Activity/ActivityActions/ActivityFilter.js
  renderer/components/Activity/ActivityActions/messages.js
  renderer/components/Channels/ChannelFilter.js
  renderer/components/Channels/ChannelsActions.js
  renderer/components/Channels/ChannelsHeader.js
  renderer/components/Channels/ChannelsViewButtons.js
  renderer/components/Channels/messages.js
  renderer/components/Icon/Filter.js
  renderer/components/Pay/Pay.js
  renderer/components/UI/Dropdown/Dropdown.js
  renderer/components/UI/Dropdown/IconDropdownButton.js
  renderer/components/UI/Dropdown/index.js
  renderer/containers/Activity/Activity.js
  renderer/containers/Activity/ActivityActions.js
  renderer/containers/Channels/ChannelsHeader.js
  renderer/reducers/activity.js
  renderer/reducers/channels.js
  stories/_general/icons.stories.js
  stories/components/dropdown.stories.js
  stories/icons/icon.stories.js
  test/unit/reducers/__snapshots__/activity.spec.js.snap
  test/unit/reducers/__snapshots__/channels.spec.js.snap
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: bug 🐛, type: enhancement

#3123 Ensure onboarding dialogs display on top of wizard controls
  renderer/components/Onboarding/Steps/BackupSetup.js
  renderer/components/Onboarding/Steps/WalletCreate.js
  renderer/components/Onboarding/Steps/WalletRecover.js
  renderer/components/Onboarding/Steps/components/ErrorDialog.js
  renderer/components/Onboarding/Steps/components/SkipBackupsDialog.js
Labels: scope: onboarding, scope: ui/ux, type: bug 🐛

#3124 Don't re-render SeedConfirm on mount
  renderer/components/Onboarding/Steps/SeedConfirm.js
Labels: scope: onboarding, type: bug 🐛

#3121 Improve address generation error handling
  renderer/reducers/address.js
Labels: type: bug 🐛

#3129 Upgrade consistent-return from warn to error
  .eslintrc.js
Labels: scope: devops

#2792 Show number of confs for incoming onchain txs in activity list
  config/default.js
  renderer/components/Activity/Transaction/Transaction.js
  renderer/components/Activity/Transaction/messages.js
  renderer/components/Settings/SettingsPage.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: enhancement

#3115 Skip generation of lndconnect qrcode links for temporary wallets
  utils/lndConfig.js
Labels: type: bug 🐛

#3131 Support bolt11 invoices encoded in bip21 uris
  electron/main.js
  renderer/reducers/pay.js
Labels: scope: wallet, type: enhancement

#3137 Fix LN/Onchain invoice validation
  renderer/components/Form/LightningInvoiceInput.js
  test/unit/components/Form/__snapshots__/LightningInvoiceInput.spec.js.snap
Labels: type: bug 🐛

#3138 Fix activity filters
  renderer/components/Pay/Pay.js
  renderer/containers/Pay.js
  renderer/reducers/activity.js
  test/unit/reducers/__snapshots__/activity.spec.js.snap
  test/unit/reducers/activity.spec.js
Labels: type: bug 🐛

#3143 Fix components focus issue
  package.json
  renderer/themes/base.js
  test/unit/components/Home/__snapshots__/CreateWalletButton.spec.js.snap
  test/unit/components/Home/__snapshots__/NoWallets.spec.js.snap
  test/unit/components/UI/__snapshots__/ActionBar.spec.js.snap
  test/unit/components/UI/__snapshots__/Button.spec.js.snap
  test/unit/components/UI/__snapshots__/Dialog.spec.js.snap
  yarn.lock
Labels: type: bug 🐛

#3139 Enable notarization for mac builds
  .travis.yml
  appveyor.yml
  package.json
  resources/mac/entitlements.mac.inherit.plist
  scripts/afterSignHook.js
  yarn.lock
Labels: scope: devops

#3145 Ensure failed payments marked as failed
  renderer/components/Form/util.js
  renderer/components/Pay/PaySummaryLightning.js
  renderer/components/Request/RequestSummary.js
  renderer/reducers/activity.js
  renderer/reducers/autopay.js
  renderer/reducers/invoice.js
  renderer/reducers/payment.js
  services/grpc/lightning.methods.js
  utils/crypto.js
Labels: type: bug 🐛

#3155 fix(wallet): present correct fee when no route
  renderer/components/Pay/PaySummary.js
  renderer/components/Pay/PaySummaryLightning.js
  renderer/reducers/pay.js
Labels: scope: wallet, type: bug 🐛

#3146 Ensure correct expire date for invoices with far future expiry
  renderer/components/UI/Countdown.js
  stories/components/countdown.stories.js
  test/unit/components/UI/Countdown.spec.js
  test/unit/components/UI/__snapshots__/Countdown.spec.js.snap
Labels: scope: ui/ux, type: bug 🐛

#3161 test(unit): use mock date in countdown tests
  test/unit/components/UI/Countdown.spec.js
  test/unit/components/UI/__snapshots__/Countdown.spec.js.snap
Labels: scope: tests

#3164 fix(wallet): ensure transaction sending error handled
  renderer/components/Activity/Transaction/Transaction.js
  renderer/components/Activity/Transaction/messages.js
  renderer/reducers/activity.js
  renderer/reducers/transaction.js
  translations/en.json
Labels: type: bug 🐛

#3165 Disable sign message functionality for local wallets
  renderer/components/Profile/ProfileMenu/ProfileMenu.js
  renderer/components/Profile/ProfilePage/ProfilePage.js
Labels: type: bug 🐛

#3168 Fix getInfo subscription cornercases
  renderer/hooks/useTimeout.js
  services/grpc/grpc.js
  services/grpc/lightning.subscriptions.js
  test/unit/utils/scheduler.spec.js
  utils/scheduler.js
  utils/streamify.js
Labels: type: bug 🐛

#3177 Fix number of issues in pay form
  renderer/components/Form/LightningInvoiceInput.js
  renderer/components/Pay/Pay.js
  renderer/components/Pay/PayAmountFields.js
  renderer/components/Pay/PayPanelFooter.js
Labels: scope: performance, type: bug 🐛

#3180 fix(grpc): ensure that protobuf has Long support
  renderer/workers/grpc.worker.js
Labels: scope: grpc, type: bug 🐛

#3181 Allow submitting any onboarding step with "return" key
  renderer/components/UI/Wizard.js
  renderer/hooks/useOnKeydown.js
Labels: type: bug 🐛

#3185 fix(onboarding): retain wallet addresses in state
  renderer/reducers/address.js
Labels: type: bug 🐛

#3167 refactor: rename transactionId to internalId
  renderer/reducers/transaction.js
Labels: type: refactor

#3193 fix(wallet): factor sent and received in channel capacity
  renderer/reducers/channels.js
Labels: type: bug 🐛

#3237 Refactor dialogs to use common dialog system (rebased)
  renderer/containers/Activity/Activity.js
  renderer/containers/Activity/Invoice.js
  renderer/containers/Activity/Payment.js
  renderer/containers/Activity/Transaction.js
  renderer/containers/Channels.js
  renderer/containers/Channels/ChannelCloseDialog.js
  renderer/containers/Channels/ChannelDetail.js
  renderer/containers/Channels/ChannelsHeader.js
  renderer/containers/Home/DeleteWalletDialog.js
  renderer/containers/Home/Home.js
  renderer/containers/Onboarding/Steps/BackupSetup.js
  renderer/reducers/activity/constants.js
  renderer/reducers/activity/reducer.js
  renderer/reducers/channels.js
  renderer/reducers/onboarding.js
  renderer/reducers/wallet.js
  test/e2e/basic-ui.spec.js
  test/unit/reducers/__snapshots__/activity.spec.js.snap
  test/unit/reducers/__snapshots__/channels.spec.js.snap
  test/unit/reducers/__snapshots__/onboarding.spec.js.snap
  test/unit/reducers/__snapshots__/wallet.spec.js.snap
  test/unit/reducers/activity.spec.js
  test/unit/reducers/channels.spec.js
  test/unit/reducers/onboarding.spec.js
  test/unit/reducers/wallet.spec.js
Labels: type: refactor

#3220 refactor: componentize wallet reducer
  renderer/reducers/wallet/constants.js
  renderer/reducers/wallet/index.js
  renderer/reducers/wallet/reducer.js
  renderer/reducers/wallet/selectors.js
Labels: type: refactor
