Repository LN-Zap/zap-desktop, pull requests merged in 2020-03, with the labels that each got.

#3340 feat: add tooltip to the Home.Autopilot section describing its function
  renderer/components/Home/WalletSettingsFormLocal.js
  renderer/components/Home/messages.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: enhancement

#3356 Update Renovate Configuration
  .renovaterc.json
Labels: type: chore

#3376 Set user-agent to `Chrome` for google oauth
  electron/walletBackup/gdrive/gdriveApi.js
Labels: backups, type: bug 🐛

#3415 chore(deps): update dependency informed to v3
  package.json
  test/unit/components/Form/__snapshots__/Checkbox.spec.js.snap
  yarn.lock
Labels: dependencies

#3179 fix(deps): update from comlinkjs v3.2.0 to comlink v4.2.0
  package.json
  renderer/reducers/lnd.js
  renderer/reducers/neutrino.js
  renderer/workers/grpc.worker.js
  renderer/workers/index.js
  renderer/workers/neutrino.worker.js
  services/grpc/grpc.js
  yarn.lock
Labels: dependencies

#3393 Update to lnd 0.9 and support keysend
  package.json
  renderer/components/Form/LightningInvoiceInput.js
  renderer/components/Pay/Pay.js
  renderer/components/Pay/PayAddressField.js
  renderer/components/Pay/PayPanelBody.js
  renderer/components/Pay/PayPanelFooter.js
  renderer/components/Pay/PayPanelHeader.js
  renderer/components/Pay/PaySummary.js
  renderer/components/Pay/PaySummaryLightning.js
  renderer/components/Pay/messages.js
  renderer/components/Request/RequestSummary.js
  renderer/components/Request/messages.js
  renderer/reducers/invoice.js
  renderer/reducers/messages/messages.js
  renderer/reducers/payment.js
  scripts/lnd-release/.goreleaser.yml
  services/grpc/lightning.methods.js
  services/neutrino/neutrino.js
  test/unit/components/Pay/PayAddressField.spec.js
  test/unit/components/Pay/PayPanelHeader.spec.js
  test/unit/components/Pay/__snapshots__/PayAddressField.spec.js.snap
  test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
  test/unit/utils/crypto.spec.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
  utils/crypto.js
Labels: scope: lnd, type: enhancement

#3401 Display transaction as unconfirmed if confs less than min finality
  renderer/components/Activity/Transaction/Transaction.js
Labels: type: bug 🐛

#3160 Use payment probing to improve fee estimate
  config/default.js
  renderer/components/Channels/ChannelCreateForm.js
  renderer/components/Pay/Pay.js
  renderer/components/Pay/PayAmountFields.js
  renderer/components/Pay/PayPanelBody.js
  renderer/components/Pay/PaySummary.js
  renderer/components/Pay/PaySummaryLightning.js
  renderer/components/Pay/PaySummaryOnChain.js
  renderer/components/UI/Value.js
  renderer/reducers/info.js
  renderer/reducers/pay.js
  renderer/reducers/payment.js
  services/grpc/grpc.js
  services/grpc/router.methods.js
  test/unit/components/Pay/__snapshots__/PaySummaryLightning.spec.js.snap
  test/unit/utils/btc.spec.js
  test/unit/utils/crypto.spec.js
  utils/btc.js
  utils/coin.js
  utils/crypto.js
  utils/fee.js
Labels: type: enhancement

#3430 Componentize pay and payment reducers
  renderer/reducers/messages/messages.js
  renderer/reducers/pay/constants.js
  renderer/reducers/pay/index.js
  renderer/reducers/pay/ipc.js
  renderer/reducers/pay/messages.js
  renderer/reducers/pay/reducer.js
  renderer/reducers/pay/selectors.js
  renderer/reducers/payment/constants.js
  renderer/reducers/payment/index.js
  renderer/reducers/payment/messages.js
  renderer/reducers/payment/reducer.js
  renderer/reducers/payment/selectors.js
  renderer/reducers/payment/utils.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
Labels: type: refactor

#3433 Clean up payments logic
  electron/preload.js
  renderer/components/Activity/Payment/Payment.js
  renderer/components/Activity/Payment/messages.js
  renderer/components/Activity/PaymentModal/PaymentModal.js
  renderer/components/Activity/PaymentModal/messages.js
  renderer/reducers/activity/reducer.js
  renderer/reducers/invoice.js
  renderer/reducers/pay/reducer.js
  renderer/reducers/payment/constants.js
  renderer/reducers/payment/messages.js
  renderer/reducers/payment/reducer.js
  renderer/reducers/payment/utils.js
  services/grpc/lightning.methods.js
  services/grpc/router.methods.js
  stories/Provider.js
  test/unit/utils/sha256.spec.js
  translations/af-ZA.json
  translations/ar-SA.json
  translations/bg-BG.json
  translations/ca-ES.json
  translations/cs-CZ.json
  translations/da-DK.json
  translations/de-DE.json
  translations/el-GR.json
  translations/en.json
  translations/es-ES.json
  translations/fi-FI.json
  translations/fr-FR.json
  translations/ga-IE.json
  translations/he-IL.json
  translations/hi-IN.json
  translations/hr-HR.json
  translations/hu-HU.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/ko-KR.json
  translations/nl-NL.json
  translations/no-NO.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/pt-PT.json
  translations/ro-RO.json
  translations/ru-RU.json
  translations/sr-SP.json
  translations/sv-SE.json
  translations/tr-TR.json
  translations/uk-UA.json
  translations/vi-VN.json
  translations/zh-CN.json
  translations/zh-TW.json
  utils/crypto.js
  utils/sha256.js
Labels: type: bug 🐛, type: refactor
